# Generated by Django 5.2 on 2026-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0047_album_mb_release_group_id_album_mb_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="mb_auto_match_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artista",
            name="mb_blocked_mbids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
