# Generated by Django 5.2 on 2026-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0048_artista_mb_auto_match_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
    ]
