# Generated by Django 5.2 on 2026-04-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0049_artista_instagram_url_artista_twitter_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="lastfm_bio_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_bio_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_bio_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_image_extralarge",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_image_large",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_image_medium",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_image_small",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_last_sync",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_listeners",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_ontour",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_playcount_total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artista",
            name="lastfm_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="nb_similars_lastfm",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
