# Generated by Django 5.2 on 2026-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0050_lastfm_artist_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="lastfm_auto_match_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
