# Generated by Django 5.2 on 2026-04-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0052_add_gestor_edita_artista_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short bio written by the artist's verified manager.",
            ),
        ),
    ]
