# Generated by Django 5.2 on 2026-05-01 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0056_alter_staffauditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistaLastfmAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Variant Last.fm name (e.g. 'Böira' alongside 'Boira'). Stored case-sensitive — Last.fm's URL is case-insensitive but the API requires the exact spelling for `autocorrect=0` queries.",
                        max_length=255,
                    ),
                ),
                ("descobert_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmat",
                    models.BooleanField(
                        default=False,
                        help_text="Staff has confirmed this alias is the same artist.",
                    ),
                ),
                ("confirmat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rebutjat",
                    models.BooleanField(
                        default=False,
                        help_text="Staff has explicitly rejected this candidate as a homonym. Kept in DB so re-running the detector doesn't re-propose it.",
                    ),
                ),
                (
                    "playcount_canonical",
                    models.IntegerField(
                        blank=True,
                        help_text="Last.fm playcount of the canonical page at detection time.",
                        null=True,
                    ),
                ),
                (
                    "playcount_variant",
                    models.IntegerField(
                        blank=True,
                        help_text="Last.fm playcount of this variant at detection time.",
                        null=True,
                    ),
                ),
                (
                    "top_tracks_overlap",
                    models.FloatField(
                        blank=True,
                        help_text="Share of top-5 tracks that match between the two pages (0..1). Higher is more confident; the detector requires ≥0.5.",
                        null=True,
                    ),
                ),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lastfm_aliases",
                        to="music.artista",
                    ),
                ),
                (
                    "confirmat_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Artista Last.fm alias",
                "verbose_name_plural": "Artista Last.fm aliases",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artista", "nom"), name="uniq_artista_lastfm_alias_nom"
                    )
                ],
            },
        ),
    ]
