# Generated by Django 5.2 on 2026-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0057_artistalastfmalias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("canco_aprovar", "Cançó: aprovar"),
                    ("canco_rebutjar", "Cançó: rebutjar"),
                    ("canco_rebutjar_album", "Cançó: rebutjar àlbum sencer"),
                    ("canco_edit", "Cançó: edició"),
                    ("artista_aprovar", "Artista: aprovar"),
                    ("artista_rebutjar", "Artista: rebutjar"),
                    ("artista_marcar_sense_deezer", "Artista: marcar sense Deezer"),
                    ("artista_fusionar", "Artista: fusionar"),
                    ("artista_crear", "Artista: crear"),
                    ("artista_edit", "Artista: edició"),
                    ("artista_mbid_auto_unassign", "Artista: MBID auto-rebutjat"),
                    (
                        "artista_mbid_auto_restore",
                        "Artista: MBID restaurat (correcció)",
                    ),
                    ("lastfm_alias_confirm", "Last.fm alias: confirmat"),
                    ("lastfm_alias_reject", "Last.fm alias: rebutjat (homònim)"),
                    ("lastfm_alias_delete", "Last.fm alias: eliminat"),
                    ("lastfm_alias_manual_add", "Last.fm alias: afegit manualment"),
                    ("pendent_aprovar", "Pendent: aprovar"),
                    ("pendent_descartar", "Pendent: descartar"),
                    ("album_edit", "Àlbum: edició"),
                    ("album_descartar", "Àlbum: descartar"),
                    ("proposta_aprovar", "Proposta: aprovar"),
                    ("proposta_rebutjar", "Proposta: rebutjar"),
                    ("sollicitud_aprovar", "Sol·licitud: aprovar"),
                    ("sollicitud_rebutjar", "Sol·licitud: rebutjar"),
                    ("config_update", "Configuració global: actualitzada"),
                    ("usuari_desactivar", "Usuari: desactivar"),
                    ("usuari_reactivar", "Usuari: reactivar"),
                    ("usuari_reset_2fa", "Usuari: reset 2FA"),
                    ("gestor_edita_artista", "Artista: edició per gestor"),
                    ("social_publicat", "Social: publicat (Instagram)"),
                ],
                max_length=40,
            ),
        ),
    ]
