# Generated by Django 5.2 on 2026-05-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0058_alter_staffauditlog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistaLastfmSimilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.FloatField(
                        blank=True,
                        help_text="Last.fm's similarity score for this pair (0–1).",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Artist whose getSimilar response surfaced this row.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similars_recomanats",
                        to="music.artista",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Artist being recommended (resolved through the alias table so 'Delên' and 'dêlen' map to the same target).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomanat_per",
                        to="music.artista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Last.fm similar (source→target)",
                "verbose_name_plural": "Last.fm similars (source→target)",
                "indexes": [
                    models.Index(
                        fields=["target"], name="music_artis_target__71e022_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target"),
                        name="uniq_lastfm_similar_source_target",
                    )
                ],
            },
        ),
    ]
