# Generated by Django 5.2 on 2026-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0060_album_last_album_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="source_deezer_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Which `ArtistaDeezer.deezer_id` of the album's artista this row was originally fetched from. Set by `_create_album` (cron) and `_upsert_album` (--force). Used by `_try_auto_unlink_homonym_deezer` to scope the homonym unlink to one specific Deezer profile when the artista has several. NULL on legacy rows (pre-2026-05-03); the smart unlink falls back to a defer-to-staff path in that case.",
                null=True,
            ),
        ),
    ]
