# Generated by Django 5.2.13 on 2026-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0061_album_source_deezer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="mb_sync_cursor",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
