# Generated by Django 6.0.4 on 2026-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0062_artista_mb_sync_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="artista",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="canco",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
