# Generated by Django 6.0.4 on 2026-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0064_seo_backfill_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="genere_canonical",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pop", "Pop"),
                    ("rock", "Rock"),
                    ("indie", "Indie / Alternatiu"),
                    ("punk", "Punk"),
                    ("hardcore", "Hardcore"),
                    ("metal", "Metal"),
                    ("ska", "Ska"),
                    ("reggae", "Reggae"),
                    ("folk", "Folk"),
                    ("cantautor", "Cantautor / a"),
                    ("electronica", "Electrònica"),
                    ("hip-hop", "Hip-hop / Rap"),
                    ("urba", "Urbà"),
                    ("jazz", "Jazz"),
                    ("experimental", "Experimental"),
                    ("infantil", "Infantil"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="genere_locked",
            field=models.BooleanField(default=False),
        ),
    ]
