# Generated by Django 6.0.4 on 2026-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0065_seo_genere_canonical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artista",
            name="genere_canonical",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cantautor", "Cantautor"),
                    ("electronica", "Electrònica"),
                    ("experimental", "Experimental"),
                    ("folk", "Folk"),
                    ("hardcore", "Hardcore"),
                    ("hip-hop", "Hip-hop"),
                    ("indie", "Indie"),
                    ("infantil", "Infantil"),
                    ("jazz", "Jazz"),
                    ("metal", "Metal"),
                    ("pop", "Pop"),
                    ("punk", "Punk"),
                    ("reggae", "Reggae"),
                    ("rock", "Rock"),
                    ("ska", "Ska"),
                    ("urba", "Urbà"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
    ]
