# Generated by Django 6.0.4 on 2026-05-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0068_alter_staffauditlog_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="cancons_obtingudes",
        ),
    ]
