# Generated by Django 6.0.4 on 2026-05-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0069_remove_album_cancons_obtingudes"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="label",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="canco",
            name="contributors_raw",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
