# Generated by Django 6.0.4 on 2026-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0070_album_label_canco_contributors_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialrevisio",
            name="artista_territori",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
