# Generated by Django 6.0.5 on 2026-05-20 12:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0071_alter_historialrevisio_artista_territori"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="imatge_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Imatge custom de l'artista. Si està buida, s'usa la del Last.fm o caratula d'album.",
                max_length=500,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="ultim_ping_revisio_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp de l'últim ping de revisió de cançons enviat pel gestor. Usat per al cooldown de 7 dies.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artistalastfmalias",
            name="prioritari",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Un sol prioritari per artista. Determina quin nom és el principal als CRUD i el mirror a Artista.lastfm_nom.",
            ),
        ),
        migrations.AddConstraint(
            model_name="artistalastfmalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("prioritari", True)),
                fields=("artista",),
                name="uniq_artista_lastfm_prioritari",
            ),
        ),
    ]
