# Generated by Django 6.0.5 on 2026-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0074_alter_staffauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialrevisio",
            name="reconsiderada",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Quan True, obtenir_novetats pot re-ingerir aquesta cançó (sortida del filtre de rebuigs).",
            ),
        ),
    ]
