# Generated by Django 6.0.5 on 2026-05-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0075_historialrevisio_reconsiderada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("canco_aprovar", "Cançó: aprovar"),
                    ("canco_rebutjar", "Cançó: rebutjar"),
                    ("canco_rebutjar_album", "Cançó: rebutjar àlbum sencer"),
                    ("canco_edit", "Cançó: edició"),
                    ("artista_aprovar", "Artista: aprovar"),
                    ("artista_rebutjar", "Artista: rebutjar"),
                    ("artista_marcar_sense_deezer", "Artista: marcar sense Deezer"),
                    ("artista_fusionar", "Artista: fusionar"),
                    ("artista_crear", "Artista: crear"),
                    ("artista_edit", "Artista: edició"),
                    ("artista_mbid_auto_unassign", "Artista: MBID auto-rebutjat"),
                    (
                        "artista_mbid_auto_restore",
                        "Artista: MBID restaurat (correcció)",
                    ),
                    ("artista_sync_mb", "Artista: re-sincronitzar des de MusicBrainz"),
                    ("lastfm_alias_confirm", "Last.fm alias: confirmat"),
                    ("lastfm_alias_reject", "Last.fm alias: rebutjat (homònim)"),
                    ("lastfm_alias_delete", "Last.fm alias: eliminat"),
                    ("lastfm_alias_manual_add", "Last.fm alias: afegit manualment"),
                    ("pendent_aprovar", "Pendent: aprovar"),
                    ("pendent_descartar", "Pendent: descartar"),
                    ("pendent_orphan_merged", "Pendent: fusionar òrfan amb canònic"),
                    ("album_edit", "Àlbum: edició"),
                    ("album_descartar", "Àlbum: descartar"),
                    ("proposta_aprovar", "Proposta: aprovar"),
                    ("proposta_rebutjar", "Proposta: rebutjar"),
                    ("sollicitud_aprovar", "Sol·licitud: aprovar"),
                    ("sollicitud_rebutjar", "Sol·licitud: rebutjar"),
                    ("config_update", "Configuració global: actualitzada"),
                    ("usuari_desactivar", "Usuari: desactivar"),
                    ("usuari_reactivar", "Usuari: reactivar"),
                    ("usuari_reset_2fa", "Usuari: reset 2FA"),
                    ("usuari_esborrar", "Usuari: esborrar (RGPD)"),
                    (
                        "usuari_reenviar_verificacio",
                        "Usuari: reenviar email de verificació",
                    ),
                    (
                        "usuari_enviar_reset_password",
                        "Usuari: enviar email de reset de contrasenya",
                    ),
                    ("feedback_resolt", "Feedback: marcat com a resolt"),
                    ("comentari_esborrar", "Comentari: esborrar (moderació)"),
                    ("gestor_edita_artista", "Artista: edició per gestor"),
                    (
                        "gestor_ping_revisio",
                        "Artista: ping de revisió de cançons (gestor)",
                    ),
                    ("sollicitud_revisio_creada", "Sol·licitud de revisió: creada"),
                    ("sollicitud_revisio_resolta", "Sol·licitud de revisió: resolta"),
                    ("rebutjada_reconsiderada", "Historial: rebutjada reconsiderada"),
                    ("social_publicat", "Social: publicat (Instagram)"),
                    ("mastodon_publicat", "Social: publicat (Mastodon)"),
                    ("bluesky_publicat", "Social: publicat (Bluesky)"),
                    ("telegram_publicat", "Social: publicat (Telegram)"),
                    ("newsletter_publicat", "Social: publicat (Newsletter)"),
                ],
                max_length=40,
            ),
        ),
    ]
