# Generated by Django 6.0.5 on 2026-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0076_alter_staffauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='chunk_index',
            field=models.IntegerField(blank=True, help_text='Window chunk for no_verificades playlists (0-based).', null=True),
        ),
        migrations.AlterField(
            model_name='spotifyplaylist',
            name='kind',
            field=models.CharField(choices=[('top', 'Top provisional'), ('novetats', 'Novetats'), ('no_verificades', 'No verificades (triage)')], max_length=20),
        ),
    ]
