# Generated by Django 6.0.5 on 2026-05-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0078_spotify_playlist_seed_fase_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="spotify_artist_dispersio",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Distinct principal spotify_artist_id count across this artist's enriched tracks. >1 suggests Deezer homonym merge.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="spotify_artist_ids_distints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sorted list of the distinct principal Spotify artist IDs seen across enriched cançons. Mirrors dispersio for debug.",
            ),
        ),
        migrations.CreateModel(
            name="SpotifyMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "spotify_artist_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("spotify_artist_ids", models.JSONField(blank=True, default=list)),
                ("spotify_artist_name", models.CharField(blank=True, max_length=255)),
                ("album_type", models.CharField(blank=True, max_length=32)),
                ("release_date", models.CharField(blank=True, max_length=10)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("explicit", models.BooleanField(null=True)),
                ("is_playable", models.BooleanField(null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("genres", models.JSONField(blank=True, default=list)),
                (
                    "enrichment_status",
                    models.CharField(
                        choices=[
                            ("not_attempted", "Encara no provada"),
                            ("found", "Trobada"),
                            ("not_found", "ISRC no a Spotify"),
                        ],
                        db_index=True,
                        default="not_attempted",
                        max_length=20,
                    ),
                ),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify",
                        to="music.canco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spotify metadata",
                "verbose_name_plural": "Spotify metadata",
            },
        ),
    ]
