# Generated by Django 6.0.5 on 2026-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0080_spotify_metadata_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyplaylist",
            name="freq",
            field=models.CharField(
                choices=[("daily", "Diari"), ("weekly", "Setmanal")],
                db_index=True,
                default="daily",
                help_text="Cadence: daily reads TopProvisional, weekly reads TopSetmanal.",
                max_length=10,
            ),
        ),
    ]
