# Generated by Django 6.0.5 on 2026-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0087_spotifymetadata_status_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifyplaylist",
            name="kind",
            field=models.CharField(
                choices=[
                    ("top", "Top provisional"),
                    ("novetats", "Novetats"),
                    ("no_verificades", "No verificades (triage)"),
                    ("novetats_per_verificar", "Novetats per verificar"),
                ],
                max_length=30,
            ),
        ),
    ]
