# Generated by Django 6.0.5 on 2026-06-11 11:37

from django.db import migrations, models


def _backfill(apps, schema_editor):
    # Recompute the homonym key for every existing artista. Mirrors
    # `music.models.normalitza_nom_homonim` (kept inline so the migration is
    # frozen against future changes to that function).
    import re
    import unicodedata

    strip_re = re.compile(r"[^a-z0-9]+")

    def key(nom):
        s = unicodedata.normalize("NFKD", nom or "")
        s = "".join(c for c in s if not unicodedata.combining(c))
        return strip_re.sub("", s.lower())

    Artista = apps.get_model("music", "Artista")
    to_update = []
    for a in Artista.objects.all().only("pk", "nom", "nom_normalitzat"):
        k = key(a.nom)
        if a.nom_normalitzat != k:
            a.nom_normalitzat = k
            to_update.append(a)
    Artista.objects.bulk_update(to_update, ["nom_normalitzat"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0090_deactivate_orphan_pendent_cancons"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="nom_normalitzat",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
