# Generated by Django 6.0.5 on 2026-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0092_alter_staffauditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historialrevisio",
            name="motiu",
            field=models.CharField(
                choices=[
                    ("ok", "Aprovada"),
                    ("auto_ml", "Aprovada per ML"),
                    ("auto_whisper", "Aprovada per Whisper (LID català)"),
                    ("desvincular_canco", "Desvincular la cançó"),
                    ("desvincular_album", "Desvincular l'àlbum"),
                    ("desvincular_artista", "Desvincular l'artista"),
                ],
                max_length=50,
            ),
        ),
    ]
