# Generated by Django 6.0.5 on 2026-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0093_auto_whisper_motiu"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="youtube_channel_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UC… id of the '<nom> - Topic' channel. Costs 100 quota units to discover, so it is resolved once and cached here.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="youtube_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last discovery attempt. Set even when nothing was found, so the quota budget doesn't re-spend 100 units on the same miss.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="youtube_uploads_playlist",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="canco",
            name="youtube_match",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exacte", "Títol normalitzat exacte"),
                    ("durada", "Títol aproximat + durada"),
                    ("manual", "Revisat per staff"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="canco",
            name="youtube_matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="canco",
            name="youtube_video_id",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
