# Generated by Django 6.0.5 on 2026-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0094_artista_youtube_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="youtube_canal_oficial",
            field=models.CharField(
                blank=True,
                help_text="UC… id del canal propi de l'artista. El tria una persona.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="artista",
            name="youtube_canal_revisat",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Algú ho ha mirat. Amb `youtube_canal_oficial` buit vol dir «revisat: no en té», que és un estat vàlid i final.",
            ),
        ),
    ]
