# Generated by Django 6.0.5 on 2026-08-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0095_artista_youtube_canal_oficial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancoYouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=16)),
                ("titol", models.CharField(blank=True, max_length=300)),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_videos",
                        to="music.canco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vídeo de YouTube d'una cançó",
                "verbose_name_plural": "Vídeos de YouTube de cançons",
                "indexes": [
                    models.Index(
                        fields=["canco"], name="music_canco_canco_i_1d23eb_idx"
                    )
                ],
                "unique_together": {("canco", "video_id")},
            },
        ),
    ]
