# Generated by Django 6.0.5 on 2026-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0096_cancoyoutubevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_rebutjat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
