# Generated by Django 6.0.5 on 2026-08-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0097_artista_instagram_rebutjat_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_revisat",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
