# Generated by Django 6.0.5 on 2026-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0098_artista_instagram_revisat"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_rebutjat_url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
