# Generated by Django 6.0.5 on 2026-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0099_artista_instagram_rebutjat_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_suggerit",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
