# Generated by Django 6.0.5 on 2026-08-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0100_artista_instagram_suggerit"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="instagram_suggerits_descartats",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
