# Generated by Django 6.0.5 on 2026-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0101_artista_instagram_suggerits_descartats"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="youtube_revisat",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Algú ha buscat el vídeo. Amb `youtube_video_id` buit vol dir «revisat: no en té», que és un estat vàlid i final.",
            ),
        ),
    ]
