# Generated by Django 6.0.5 on 2026-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0102_canco_youtube_revisat"),
    ]

    operations = [
        migrations.AddField(
            model_name="canco",
            name="youtube_publicat_at",
            field=models.DateField(
                blank=True,
                help_text="Data de publicació de l'Art Track. Evidència d'edat de la gravació per al rànquing.",
                null=True,
            ),
        ),
    ]
