# Generated by Django 6.0.5 on 2026-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0103_canco_youtube_publicat_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="anunciat_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Quan una publicació de novetats va portar aquest llançament. Buit = mai anunciat.",
                null=True,
            ),
        ),
    ]
