"""Hero phrase bank — the editorial opener of every post.

Thirteen scenario codes × three length tiers × 15 entries each =
585 templates (a1-a12 + fallback; see ADR-0008 for the four
expansion detectors a9-a12). Each template is a `.format(**data)`-ready string.

Conventions:
* `{de_artista}` is pre-rendered by the scenario detector via
  `apostrof_de(artista)` — templates write `de {de_artista}` is
  WRONG; write `{de_artista}` directly when you want "de X" or
  "d'X". (Or `{artista}` for the bare name.)
* Subject of any finite verb is either invariant (`«{canco}»`,
  `el cim`, `el top`, `la setmana`) or the artist in singular —
  per the Fase 4 reset decision, we accept `OBESES debuta`,
  `Manel actua`, `Els Catarres entra` (forced but acceptable).
* No em-dashes; we use the short-dash `—` only as a typographic
  separator, not as Catalan punctuation.
* 1–2 emojis per entry; no emoji appears more than twice within
  the same scenario bank.

The composer picks one entry per scenario via the registry and
interpolates the scenario data."""

from __future__ import annotations

# ── A1: outside / low to 1r ────────────────────────────────────────
# data: artista, de_artista, canco, posicio_anterior_str, territori_label
A1_OUTSIDE_TO_TOP1 = {
    "short": [
        "{artista} es planta al 1r {territori_ordinal} amb «{canco}» 🚀",
        "Cop al cim {territori_ordinal}: nou 1r, {artista} 💥",
        "Nou 1r {territori_ordinal}: «{canco}» {de_artista} 🆕",
        "Canvi al cim {territori_ordinal}: ara mana «{canco}» 👑",
        "{artista} arriba al 1r {territori_ordinal} 🥇",
        "«{canco}» és el nou 1r {territori_ordinal} ⭐",
        "Sorpresa al cim {territori_ordinal}: {artista} 🎯",
        "Ascens fulgurant: «{canco}» al 1r {territori_ordinal} 🔥",
        "Estrena de 1r {territori_ordinal}: {artista} ✨",
        "Recanvi al cim {territori_ordinal}: {artista} 🎬",
        "Salt al 1r {territori_ordinal} {de_artista} 🪂",
        "Cim conquerit {de_artista} {territori_ordinal} 🏔️",
        "Nova líder al top {territori_label}: «{canco}» 🌟",
        "{artista} arrabassa el 1r {territori_ordinal} 💫",
        "Top {territori_label} estrena 1r: {artista} 🎵",
    ],
    "medium": [
        "{artista} arrabassa el 1r {territori_ordinal} amb «{canco}»: la setmana anterior estava {posicio_anterior_str}. 🚀",
        "Cop d'efecte al cim {territori_ordinal}: «{canco}» {de_artista} salta de {posicio_anterior_str} al 1r directament. 💥",
        "Nou líder al top {territori_label}. «{canco}», {de_artista}, ascendeix de {posicio_anterior_str} al primer lloc en una setmana. 🆕",
        "Canvi de mans al cim {territori_ordinal}: després de venir de {posicio_anterior_str}, «{canco}» {de_artista} signa el 1r. 👑",
        "Sorpresa al cap del top {territori_label}: «{canco}», {de_artista}, salta de {posicio_anterior_str} al 1r sense escala. 🎯",
        "{artista} entra fort: «{canco}» passa de {posicio_anterior_str} al 1r {territori_ordinal} en una setmana. 🔥",
        "Recanvi al 1r {territori_ordinal}. «{canco}», {de_artista}, suplanta el cim després d'estar {posicio_anterior_str} la setmana anterior. ⭐",
        "Per primera vegada al cim {territori_ordinal}: {artista} amb «{canco}», que ve de {posicio_anterior_str}. ✨",
        "El cim {territori_ordinal} estrena nom: «{canco}», {de_artista}, salta de {posicio_anterior_str} al 1r. 🥇",
        "{artista} fa el camí complet en una setmana: de {posicio_anterior_str} al 1r {territori_ordinal} amb «{canco}». 🪂",
        "Salt vertiginós: «{canco}», {de_artista}, passa de {posicio_anterior_str} al 1r del top {territori_label}. 💫",
        "Conquesta del cim {territori_ordinal}: {artista} estrena 1r amb «{canco}», cançó que venia de {posicio_anterior_str}. 🏔️",
        "Setmana de canvi al top {territori_label}: «{canco}» {de_artista} arriba al 1r des de {posicio_anterior_str}. 🎬",
        "{artista} firma el nou cim {territori_ordinal}: «{canco}» puja de {posicio_anterior_str} al 1r i ja mana. 🌟",
        "Sense passar per la sala d'espera: «{canco}», {de_artista}, salta de {posicio_anterior_str} directament al 1r {territori_ordinal}. 🎵",
    ],
    "long": [
        "Hi ha setmanes en què el cim no es mou i n'hi ha de les altres. La d'avui és de les segones: «{canco}», {de_artista}, salta de {posicio_anterior_str} al 1r del top {territori_label} en una sola setmana. Un dels ascensos més fulgurants del mes. 🚀",
        "Canvi de cara al cim {territori_ordinal}: «{canco}», {de_artista}, ja és al 1r, després d'estar {posicio_anterior_str} la setmana passada. Els ascensos d'aquesta magnitud acostumen a indicar dues coses: una cançó forta, i un moment cultural que la sosté. 💥",
        "{artista} arriba al cim {territori_ordinal} per la porta gran. «{canco}» suma en una setmana el camí des de {posicio_anterior_str} fins al 1r, un salt que es veu poques vegades sense un context que el potenciï. 🆕",
        "Si la setmana passada algú hagués apostat per «{canco}» al 1r, hauria fet el pes: la cançó, {de_artista}, ha pujat de {posicio_anterior_str} al primer lloc del top {territori_label} sense passar per posicions intermèdies. 👑",
        "Sorpresa al top {territori_label}. «{canco}», {de_artista}, ocupa el 1r aquesta setmana i venia de {posicio_anterior_str}. La concatenació d'una bona cançó amb un viratge cultural sol donar aquestes lectures. 🎯",
        "Setmana de mobilitat al cim {territori_ordinal}. {artista} signa el nou 1r amb «{canco}», cançó que la setmana passada encara estava {posicio_anterior_str}. Un d'aquests salts que reordenen el panorama del mes. ⭐",
        "El cim {territori_ordinal} té nou propietari: «{canco}», {de_artista}, ha sumat el viatge de {posicio_anterior_str} al 1r en set dies. La velocitat de l'ascens diu tant com el destí. 🔥",
        "{artista} entra a la història del top {territori_label} pel cim: «{canco}» és el seu primer 1r, després d'haver estat {posicio_anterior_str} la setmana anterior. La pujada més neta de la setmana. ✨",
        "Pocs llocs canvien tan ràpidament com el cim {territori_ordinal}. «{canco}», {de_artista}, ho ha demostrat: en una setmana ha passat de {posicio_anterior_str} a manar el top. 🥇",
        "{artista} fa el camí complet en set dies. «{canco}» puja de {posicio_anterior_str} al 1r del top {territori_label} en una sola setmana, signant una de les ascensions més contundents del que portem de primavera. 🏔️",
        "Aquestes pujades són notícia per si mateixes: «{canco}», {de_artista}, passa de {posicio_anterior_str} al 1r {territori_ordinal} en una setmana. No és el primer cas, però sí un dels més clars d'aquest mes. 🪂",
        "Salt al cim {territori_ordinal}. «{canco}», {de_artista}, ja és al 1r, venint de {posicio_anterior_str}. La fila de cançons que arriben al podi en pocs dies s'està fent llarga aquesta primavera. 💫",
        "Recanvi al top {territori_label}. {artista} estrena 1r amb «{canco}», cançó que pujava com una traca des de {posicio_anterior_str}. Quan una cançó fa aquest camí, sol mantenir-se al cap més d'una setmana. 🎬",
        "Estrena de cim {territori_ordinal} {de_artista}. «{canco}» surt de {posicio_anterior_str} i s'enfila fins al 1r en set dies. El gruix d'ascensos d'aquesta intensitat coincideix amb singles que han estat sonant en directe. 🌟",
        "Estrena al cim {territori_ordinal}: «{canco}», {de_artista}, és la nova líder del top després d'haver estat {posicio_anterior_str} la setmana passada. Tipus d'ascens que reordena el top per a la resta del mes. 🎵",
    ],
}


# ── A2: streak at 1r ────────────────────────────────────────────────
# data: artista, de_artista, canco, streak, territori_label
A2_STREAK = {
    "short": [
        "{streak}a setmana de «{canco}» al 1r {territori_ordinal} 🎯",
        "{artista} repeteix 1r {territori_ordinal} amb «{canco}» 👑",
        "Cap canvi al cim {territori_ordinal}: encara {artista} ✨",
        "Ja són {streak} {de_artista} al 1r {territori_ordinal} 🔥",
        "El cim {territori_ordinal} no es belluga · {artista} 💪",
        "«{canco}» encara mana al top {territori_label} · {streak}a 🏆",
        "{streak} setmanes al cim per a «{canco}» ⚓",
        "{artista} no afluixa: {streak} setmanes al cim 🚩",
        "Al 1r {territori_ordinal}, encara, {artista} 🌟",
        "Resistència {de_artista}: {streak} setmanes 💫",
        "Tornem-hi: {artista} al 1r ({streak}a) 🎶",
        "«{canco}» no es mou del cim {territori_ordinal} 🪕",
        "Ja en porta {streak} {de_artista} al 1r ⚡",
        "Inamovibles al cim: {artista}, {streak}a setmana 🥇",
        "{artista} regna al top {territori_label} per {streak}a setmana 🎸",
    ],
    "medium": [
        "{streak}a setmana al 1r {territori_ordinal}: «{canco}», {de_artista}, no es mou del cim. 🎯",
        "Cap canvi al cim {territori_ordinal}. {artista} encadena {streak} setmanes consecutives amb «{canco}». ✨",
        "Inamovible al podi {territori_ordinal}: «{canco}», {de_artista}, suma {streak} setmanes al 1r. 🔥",
        "Setmana rere setmana, igual: el 1r {territori_ordinal} continua amb «{canco}» {de_artista}. Ja en porta {streak}. 👑",
        "El cim {territori_ordinal} fa {streak} setmanes que és terreny {de_artista} amb «{canco}». 💪",
        "{artista} no es deixa: {streak}a setmana al 1r {territori_ordinal} amb «{canco}». 🏆",
        "Resistència pura {de_artista}: «{canco}» tanca {streak} setmanes seguides al cim {territori_ordinal}. ⚓",
        "El 1r {territori_ordinal} segueix sent de «{canco}», {de_artista}. {streak}a setmana sense canvis al cap. 🚩",
        "Lideratge ferm: «{canco}» {de_artista} signa {streak}a setmana consecutiva al cim {territori_ordinal}. 🥇",
        "Ja és costum: {artista} ocupa el 1r {territori_ordinal} per {streak}a setmana amb «{canco}». 🌟",
        "{streak} setmanes ja porta «{canco}», {de_artista}, al capdamunt {territori_ordinal}. 💫",
        "Setmana redona, una més. {artista} segueix amb «{canco}» al 1r {territori_ordinal} ({streak}a). 🎶",
        "Sense sorpreses al cim {territori_ordinal}: «{canco}» {de_artista} aguanta el 1r per {streak}a setmana. 🪕",
        "Manat i remanat: «{canco}», {de_artista}, suma {streak} setmanes al 1r {territori_ordinal}. ⚡",
        "Sense moure-ho. {artista} encara és al 1r {territori_ordinal} amb «{canco}». Ja són {streak} setmanes. 🎸",
    ],
    "long": [
        "Una setmana més i el guió no canvia. «{canco}», {de_artista}, ja porta {streak} setmanes al 1r del top {territori_label}. No es belluga ni s'arronsa: és la cançó que aquest mes mana els hàbits d'escolta arreu. 🎯",
        "{artista} signa la {streak}a setmana consecutiva al cim {territori_ordinal} amb «{canco}». Una cançó que setmana rere setmana resisteix tot allò que prova de fer-la baixar: debuts, sortides estrenades, fenòmens virals. ✨",
        "El cim {territori_ordinal} fa ja {streak} setmanes que es diu igual: «{canco}», {de_artista}. Aquesta resistència acostuma a indicar més que un èxit puntual; és que la cançó s'ha posat al cap de la gent i hi viu. 🔥",
        "Continuem on érem. «{canco}» {de_artista} encadena {streak} setmanes al 1r del top {territori_label}, sense rivals que se li acostin. La inèrcia, més que la novetat, mana aquest mes al top {territori_label}. 👑",
        "Setmana {streak} al 1r {territori_ordinal}, i comptant. «{canco}», {de_artista}, defensa el cim setmana rere setmana, un d'aquests fenòmens que comencen sent una cançó del moment i acaben sent la cançó de l'any. 💪",
        "Pocs canvis al podi {territori_ordinal} aquesta setmana, però el primer lloc segueix on l'havíem deixat: amb «{canco}», {de_artista}. Ja són {streak} setmanes al cim. Diu molt sobre la fondària de la peça. 🏆",
        "Si vols una cançó que defineixi aquest mes al top {territori_label}, ja la tens: «{canco}», {de_artista}, amb {streak} setmanes consecutives al 1r del top. La resta del top es mou, ella no. ⚓",
        "{artista} continua manant al cim {territori_ordinal}: «{canco}» fa la {streak}a setmana al 1r, sense gairebé pertorbació. Aquestes ratxes són les que diferencien un single d'una cançó generacional. 🚩",
        "Quarta? Cinquena? Ja en perdem el compte: «{canco}», {de_artista}, va per la {streak}a setmana al cim del top {territori_label}, i ningú sembla disposat a fer-la baixar. 💫",
        "El cim {territori_ordinal} aquesta setmana sona, novament, a «{canco}», {de_artista}. Ja en són {streak} consecutives, una xifra que ja ha deixat de ser anecdòtica per a esdevenir notícia per si mateixa. 🌟",
        "{streak} setmanes ja. {artista} ha convertit «{canco}» en la cançó dels últims temps al top {territori_label}. La pregunta cada divendres és si aquesta serà l'última al 1r, i de moment la resposta és no. 🥇",
        "Persistència. {artista} signa, una altra vegada, el 1r del top {territori_label} amb «{canco}». Cap altra cançó ha aconseguit fer-li ombra durant aquestes {streak} setmanes consecutives. 🎶",
        "Hi ha cançons que tenen pic i s'esllavissen i n'hi ha que aguanten. La {de_artista} aquesta primavera és, clarament, de les segones: {streak} setmanes al 1r {territori_ordinal} amb «{canco}». 🪕",
        "Resistència ferma {de_artista} al cim {territori_ordinal}. «{canco}» fa la {streak}a setmana liderant el top, una xifra que confirma que no era un fenomen efímer sinó una cançó que ha agafat múscul. ⚡",
        "Quarta setmana, cinquena, sisena. {artista} manté «{canco}» al 1r del top {territori_label} per {streak}a vegada consecutiva. El podi setmanal s'està convertint en un domèstic recurrent. 🎸",
    ],
}


# ── A3: fall from 1r ────────────────────────────────────────────────
# data: artista, de_artista, canco, posicio_nova_str, territori_label
A3_FALL_FROM_TOP1 = {
    "short": [
        "{artista} cedeix el 1r {territori_ordinal} 📉",
        "«{canco}» cau del cim {territori_ordinal} 🔻",
        "Final de regnat {per_a_artista} {territori_ordinal} 👋",
        "El 1r {territori_ordinal} canvia de mans · {artista} ⬇️",
        "Adéu al cim per a «{canco}» {de_artista} 🕊️",
        "Recanvi al cim {territori_ordinal}: cau {artista} 🌪️",
        "Es trenca la ratxa de «{canco}» al cim 🪂",
        "{artista} ha de cedir el 1r {territori_ordinal} ↘️",
        "Fora del cim {territori_ordinal}: {artista} ara {posicio_nova_str} 🎯",
        "Es buida el cim {territori_ordinal}: cau «{canco}» 🌀",
        "{artista} deixa el cim {territori_ordinal} {posicio_nova_str} 📊",
        "Es trenca el regnat de «{canco}» al top 🔄",
        "Fi del lideratge {de_artista} {territori_ordinal} 🛬",
        "La setmana destrona «{canco}» del 1r {territori_ordinal} ⚖️",
        "El 1r {territori_ordinal} ja no és {de_artista} 🎬",
    ],
    "medium": [
        "{artista} cedeix el 1r {territori_ordinal}: «{canco}» queda {posicio_nova_str} aquesta setmana. 📉",
        "Final del regnat de «{canco}» al cim {territori_ordinal}. La cançó, {de_artista}, ha quedat {posicio_nova_str}. 🔻",
        "El 1r {territori_ordinal} canvia de mans: «{canco}» {de_artista} baixa {posicio_nova_str}. 👋",
        "Es trenca la ratxa {de_artista} al 1r {territori_ordinal}: «{canco}» queda {posicio_nova_str}. ⬇️",
        "Recanvi al cim {territori_ordinal}: «{canco}», {de_artista}, deixa el 1r i queda {posicio_nova_str}. 🌪️",
        "El cim {territori_ordinal} estrena propietari aquesta setmana. {artista} cau {posicio_nova_str} amb «{canco}». 🪂",
        "Adéu al lideratge {de_artista}: «{canco}» queda {posicio_nova_str} després d'haver estat al 1r. ↘️",
        "Es buida el primer lloc del top {territori_label}: {artista} baixa amb «{canco}» {posicio_nova_str}. 🎯",
        "Final d'una etapa al cim {territori_ordinal}: «{canco}», {de_artista}, ha quedat {posicio_nova_str}. 🌀",
        "La setmana destrona {artista}: «{canco}» surt del 1r {territori_ordinal} i queda {posicio_nova_str}. 🛬",
        "Trenca la ratxa: «{canco}» {de_artista}, fins ara al 1r {territori_ordinal}, baixa {posicio_nova_str}. 🔄",
        "Es tanca el regnat de «{canco}» al cim {territori_ordinal}: aquesta setmana queda {posicio_nova_str}. ⚖️",
        "El cim {territori_ordinal} té nou amo: {artista} ha cedit el 1r i «{canco}» queda {posicio_nova_str}. 🎬",
        "{artista} deixa enrere el cim {territori_ordinal} aquesta setmana: «{canco}» queda {posicio_nova_str}. 📊",
        "Adéu al primer lloc per a «{canco}», {de_artista}: cau {posicio_nova_str} al top {territori_label}. 🕊️",
    ],
    "long": [
        "Tota cançó té el seu moment al cim, i el de «{canco}» {de_artista} ha durat el que ha durat. Aquesta setmana queda {posicio_nova_str} al top {territori_label} després d'haver presidit el top. Una passada lluïda i un relleu net. 📉",
        "Es tanca el regnat. {artista} ha hagut de cedir el 1r {territori_ordinal} a una altra cançó, i «{canco}» queda {posicio_nova_str} aquesta setmana. Les desconnexions del cim acostumen a marcar el canvi cap a una nova fase del top. 🔻",
        "Final d'una etapa al cim {territori_ordinal}. «{canco}», {de_artista}, surt del 1r i queda {posicio_nova_str}. Cap cançó hi viu per sempre; el que distingeix una bona ratxa és la durada, i la d'aquesta ha estat notable. 👋",
        "Recanvi al cim {territori_ordinal} aquesta setmana. {artista} ha cedit el primer lloc i «{canco}» queda {posicio_nova_str}. El podi reorganitza les peces; la cançó que la setmana passada manava avui mira el top des d'una altra alçada. ⬇️",
        "La setmana porta una notícia que rebumbarà: «{canco}», {de_artista}, abandona el 1r del top {territori_label} i queda {posicio_nova_str}. Quan una cançó cau del cim després d'una temporada al cap, el top es renova de cop. 🪂",
        "Es trenca la ratxa. {artista} acaba la seva temporada al 1r {territori_ordinal}: «{canco}» queda {posicio_nova_str} aquesta setmana. Cap permanència és eterna; el rellevament és la salut natural d'un top setmanal. 🌪️",
        "El cim {territori_ordinal} té nou nom. «{canco}», {de_artista}, queda {posicio_nova_str} després del seu cicle al 1r. El final d'aquestes etapes acostuma a venir amb un canvi de paisatge per a la resta del top. ↘️",
        "Adéu al regnat al cim {territori_ordinal}. {artista} surt del 1r amb «{canco}»; la cançó queda {posicio_nova_str} aquesta setmana. Els canvis al cap del top acostumen a indicar un canvi de gust col·lectiu en marxa. 🌀",
        "Final del cicle al cim {territori_ordinal}. «{canco}» {de_artista} no defensa la corona aquesta setmana i queda {posicio_nova_str}. Tota cançó deixa pas a la següent; la durada del regnat és el que en queda. 🎯",
        "Es buida el primer lloc del top {territori_label} aquesta setmana: {artista} ha cedit el 1r i «{canco}» queda {posicio_nova_str}. Les cançons que han manat queden gravades al record encara que el top ja n'hagi canviat de nom. 🎬",
        "Trenca la ratxa al cim {territori_ordinal}. «{canco}», {de_artista}, queda {posicio_nova_str} després d'una temporada amb el 1r com a casa. Els relleus d'aquesta magnitud acostumen a canviar el to de tot el top. 🔄",
        "El 1r {territori_ordinal} canvia de mans aquesta setmana. {artista} no defensa la posició i «{canco}» queda {posicio_nova_str}. Les baixades a partir del primer lloc poden ser brusques o suaus; la d'avui pertany al segon grup. 📊",
        "La setmana destrona «{canco}» {de_artista} del cim {territori_ordinal} i la deixa {posicio_nova_str}. Cap altra notícia del top supera la del relleu al primer lloc: és la que organitza la resta del mes. 🛬",
        "Adéu al lideratge {de_artista} al cim {territori_ordinal}. «{canco}» queda {posicio_nova_str}. El seu pas pel 1r ha estat sòlid i ben aprofitat; la llista en surt amb una pàgina renovada. 🕊️",
        "Final d'una temporada al 1r {territori_ordinal}. {artista} es retira del primer lloc i «{canco}» queda {posicio_nova_str}. Els relleus que es produeixen amb el guard avall acostumen a ser els més recordats. ⚖️",
    ],
}


# ── A4: strong debut at top 3 ───────────────────────────────────────
# data: artista, de_artista, canco, posicio, territori_label
A4_DEBUT_ALT = {
    "short": [
        "{artista} debuta al {posicio_ordinal} {territori_ordinal} 🆕",
        "Entrada directa al {posicio_ordinal}: «{canco}» 🚀",
        "Debut al podi: {artista} al {posicio_ordinal} 💥",
        "{artista} ataca el podi des de la primera setmana 🎯",
        "«{canco}» entra al {posicio_ordinal} {territori_ordinal} 🌟",
        "Nou nom al podi {territori_ordinal}: {artista} 🏆",
        "Cop al {posicio_ordinal}: «{canco}» {de_artista} ⚡",
        "Estrena al podi {de_artista} al {posicio_ordinal} ✨",
        "Aparició al top 3: «{canco}» {de_artista} 🎬",
        "{artista} es planta al {posicio_ordinal} {territori_ordinal} 🪂",
        "Mira aquest debut: «{canco}» al {posicio_ordinal} 👀",
        "Debut a l'alça: {artista} al {posicio_ordinal} 📈",
        "{artista} entra directe al podi 💫",
        "Setmana de debut {de_artista}: {posicio_ordinal} 🎉",
        "Estrena de pes al top: {artista} {posicio_ordinal} 🥇",
    ],
    "medium": [
        "{artista} debuta al {posicio_ordinal} {territori_ordinal} amb «{canco}» a la primera setmana. 🆕",
        "Entrada directa de «{canco}», {de_artista}, al {posicio_ordinal} {territori_ordinal}. 🚀",
        "Nou nom al podi {territori_ordinal}: «{canco}», {de_artista}, debuta al {posicio_ordinal}. 💥",
        "{artista} es planta al {posicio_ordinal} {territori_ordinal} amb «{canco}» a la primera. 🎯",
        "Debut potent al top {territori_label}: «{canco}», {de_artista}, entra al {posicio_ordinal} sense passar pels llocs baixos. 🏆",
        "Aparició al podi {territori_ordinal}: {artista} arriba al {posicio_ordinal} amb «{canco}» de bones a primeres. ⚡",
        "Cop de debut: «{canco}», {de_artista}, debuta directament al {posicio_ordinal} {territori_ordinal}. ✨",
        "Estrena al top 3 {territori_label}: «{canco}» {de_artista} salta al {posicio_ordinal} aquesta setmana. 🎬",
        "{artista} entra a la llista {territori_label} pel {posicio_ordinal} amb «{canco}» — debut net. 🪂",
        "Sorpresa al podi {territori_ordinal}: «{canco}», {de_artista}, debuta al {posicio_ordinal}. 🌟",
        "Setmana de debut {per_a_artista}: «{canco}» entra al {posicio_ordinal} {territori_ordinal}. 📈",
        "Entrada per la porta gran: {artista} debuta al {posicio_ordinal} {territori_ordinal} amb «{canco}». 💫",
        "{artista} signa un debut al podi: «{canco}» arriba al {posicio_ordinal} {territori_ordinal} a la primera. 👀",
        "Aparició inesperada al cim {territori_ordinal}: «{canco}», {de_artista}, debuta al {posicio_ordinal}. 🥇",
        "Sense escala: {artista} arriba al {posicio_ordinal} {territori_ordinal} amb «{canco}» a la primera. 🎉",
    ],
    "long": [
        "{artista} no espera al segon assalt: «{canco}» debuta directament al {posicio_ordinal} del top {territori_label}. Els debuts d'aquest calibre acostumen a venir amb una campanya de promoció ben portada, o amb una cançó que connecta sense més. 🆕",
        "Entrada per la porta gran al top {territori_label}: «{canco}», {de_artista}, es planta al {posicio_ordinal} a la primera setmana. Quan un debut arriba directament al podi, sol indicar una connexió immediata amb l'oient. 🚀",
        "Aparició al podi {territori_ordinal}: {artista} debuta al {posicio_ordinal} amb «{canco}». Pocs noms aconsegueixen aquesta velocitat d'entrada; la llista acostuma a recompensar la paciència, però aquesta setmana ha estat al revés. 💥",
        "Setmana d'estrena al top {territori_label}. «{canco}», {de_artista}, entra al {posicio_ordinal} sense passar per posicions intermèdies. Quan una cançó comença on la majoria acaben, la història acaba sent llarga. 🎯",
        "Sorpresa al podi {territori_ordinal} aquesta setmana. {artista} firma un debut al {posicio_ordinal} amb «{canco}» que reorganitza la part alta del top. Aquests debuts són els que canvien el to del mes. 🏆",
        "Pocs debuts arriben tan amunt: «{canco}», {de_artista}, entra al top {territori_label} per la posició {posicio_ordinal} a la primera setmana. La velocitat d'entrada acostuma a predir la duració de la presència. ⚡",
        "Cop de debut al top {territori_label}: {artista} es planta al {posicio_ordinal} amb «{canco}». No hi ha rondalla prèvia; la cançó arriba al podi directament. Una entrada que mereix més que una mirada. ✨",
        "Estrena de pes a la llista {territori_label}. «{canco}», {de_artista}, entra al {posicio_ordinal} a la primera setmana, signant un d'aquests debuts que acostumen a marcar el to dels mesos següents. 🎬",
        "Mira qui s'ha plantat al podi {territori_ordinal} a la primera: {artista} amb «{canco}», directe al {posicio_ordinal}. Quan un debut és tan precoç, sol parlar tant del moment de l'artista com de la cançó en si. 🪂",
        "Setmana de novetat al podi {territori_ordinal}. «{canco}», {de_artista}, debuta al {posicio_ordinal} sense escala. Aquest tipus d'entrades acostumen a indicar que la cançó ja tenia recorregut fora del top abans d'arribar-hi. 🌟",
        "{artista} entra a la llista {territori_label} pel {posicio_ordinal} amb «{canco}» a la primera setmana. Un debut al podi és sempre una notícia per si mateixa, més enllà de la cançó concreta. 📈",
        "Aparició sorprenent al top 3 {territori_label}: «{canco}», {de_artista}, es planta al {posicio_ordinal} de bones a primeres. La velocitat d'aquest tipus d'entrades sol predir la trajectòria immediata. 💫",
        "No, no és un assaig. {artista} entra al top {territori_label} pel {posicio_ordinal} amb «{canco}» a la primera setmana, sense escala prèvia. Els debuts al podi continuen sent una raresa, i aquesta n'és una. 👀",
        "Entrada solta i contundent al top {territori_label}: «{canco}», {de_artista}, fa l'estrena al {posicio_ordinal} sense escala. El tipus de debut que canvia el guió d'una setmana. 🥇",
        "Setmana de naixement al top {territori_label}: {artista} signa un debut al {posicio_ordinal} amb «{canco}». La cançó arriba amb la força del que pot durar més d'un cicle. 🎉",
    ],
}


# ── A5: artist with multiple cançons in the top ─────────────────────
# data: artista, de_artista, n_cancons, territori_label
A5_ARTISTA_MULTIPLE = {
    "short": [
        "{n_cancons} cançons {de_artista} al top {territori_label} 🎶",
        "Setmana redona {per_a_artista}: x{n_cancons} 🔥",
        "{artista} ompla el top {territori_label}: {n_cancons} cançons 🎸",
        "Domini {de_artista}: {n_cancons} entrades simultànies 👑",
        "{artista} suma {n_cancons} cançons al top {territori_label} ⚡",
        "Top monopolitzat {per_artista} · x{n_cancons} 🌊",
        "Pluja {de_artista}: {n_cancons} cançons 🎤",
        "x{n_cancons} cançons {de_artista}: setmana brillant ✨",
        "{artista} per tot el top: {n_cancons} entrades 📈",
        "Pas a {artista}: {n_cancons} cançons al top 🚪",
        "{artista}, per partida {n_cancons}-uple 🪕",
        "Setmana {de_artista}: x{n_cancons} 🎙️",
        "{artista} colpeja {n_cancons} vegades el top 🥊",
        "{n_cancons} entrades {per_a_artista} aquesta setmana 🎼",
        "Vol {de_artista} pel top: {n_cancons} cançons 🚀",
    ],
    "medium": [
        "Setmana redona {per_a_artista}: {n_cancons} cançons seves al top {territori_label}. 🎶",
        "{artista} col·loca {n_cancons} cançons simultànies al top {territori_label} aquesta setmana. 🔥",
        "Domini clar {de_artista} aquesta setmana: {n_cancons} cançons a la llista {territori_label}. 👑",
        "{n_cancons} cançons {de_artista} es passegen alhora pel top {territori_label}. 🎸",
        "{artista} signa una de les setmanes amb més presència: {n_cancons} cançons al top {territori_label}. ⚡",
        "Pluja {de_artista} al top {territori_label}: {n_cancons} cançons diferents seves coexisteixen a la llista. 🌊",
        "Repàs {de_artista} a la llista {territori_label}: hi ha {n_cancons} cançons seves a la llista d'aquesta setmana. 🎤",
        "{artista} colpeja fort: {n_cancons} cançons seves simultànies al top {territori_label}. 🥊",
        "Setmana d'autoria {per_a_artista}: {n_cancons} cançons al top {territori_label}, una rere l'altra. 🎙️",
        "{artista} ocupa {n_cancons} llocs simultanis del top {territori_label} aquesta setmana. 📈",
        "Vol {de_artista} aquesta setmana: {n_cancons} cançons al top {territori_label}. 🚀",
        "Si vols saber qui domina el top {territori_label}, la resposta és clara: {artista} amb {n_cancons} cançons. 🎼",
        "Setmana monopolitzada {de_artista}: {n_cancons} cançons al top {territori_label}. ✨",
        "Pas a {artista}: el top {territori_label} té {n_cancons} cançons seves en circulació. 🚪",
        "{n_cancons} cançons, un sol nom al top {territori_label}: {artista}. 🪕",
    ],
    "long": [
        "Setmana redona {per_a_artista}: {n_cancons} cançons seves coexisteixen al top {territori_label}. És el tipus de presència que indica més que un single ben col·locat: l'artista té un catàleg que sona ara mateix. 🎶",
        "{artista} firma una de les setmanes amb més concentració de la llista {territori_label}: {n_cancons} cançons seves comparteixen el top. Un fenomen que acostuma a coincidir amb una gira o un disc recent. 🔥",
        "Domini ample {de_artista} a la llista {territori_label} aquesta setmana: {n_cancons} cançons coexisteixen al top. La dispersió de posicions és tan reveladora com el nombre total. 👑",
        "Pluja {de_artista} al top {territori_label}. {n_cancons} cançons seves circulen alhora per la llista, deixant clar que aquest mes és el seu mes. 🌊",
        "{n_cancons} entrades simultànies {de_artista} al top {territori_label}. Quan una mateixa firma omple aquest percentatge de la llista setmanal, vol dir que ha calat al gust general més enllà d'un únic single. ⚡",
        "Setmana de domini {de_artista}: el top {territori_label} té {n_cancons} cançons seves al cap. Acostuma a passar quan l'artista té múltiples singles vigents i una base sòlida que els consumeix tots. 🎸",
        "{artista} col·loca {n_cancons} cançons simultànies al top {territori_label} aquesta setmana. La capacitat de tenir diverses peces vives al mateix temps és més difícil del que sembla, i {artista} la té. 🎤",
        "Repàs {de_artista} a la llista {territori_label}: {n_cancons} cançons seves a la llista d'aquesta setmana, des del top alt fins a les posicions intermèdies. Un fenomen de profunditat de catàleg. 🎙️",
        "Setmana monopolitzada {de_artista}. {n_cancons} cançons seves coexisteixen al top {territori_label}: un nombre que fa setmanes que no veiem tan concentrat en una sola firma. ✨",
        "Vol {de_artista} aquesta setmana pel top {territori_label}: {n_cancons} cançons seves volten per la llista, omplint tant les posicions altes com el cos del top. 🚀",
        "{artista} signa {n_cancons} entrades simultànies a la llista {territori_label}. Aquest tipus de concentració acostuma a deixar empremta més enllà de la setmana en què es produeix. 📈",
        "Si havies de triar un nom que defineix la setmana al top {territori_label}, ja el tens: {artista}, amb {n_cancons} cançons seves vives a la llista. 🎼",
        "{n_cancons} cançons {de_artista} comparteixen el top {territori_label} aquesta setmana. La presència múltiple és el signe més clar que una artista està en un dels seus millors moments. 🥊",
        "Domini transversal {de_artista} a la llista {territori_label}: {n_cancons} cançons seves al top. Quan la presència s'estén per tot la llista en lloc de concentrar-se a dalt, sol indicar fidelitat de l'oient. 🪕",
        "Setmana {de_artista} al cor del top {territori_label}: {n_cancons} cançons seves a la llista, signant una de les concentracions més clares del trimestre. 🚪",
    ],
}


# ── A6: recent release in the top 10 ────────────────────────────────
# data: artista, de_artista, canco, posicio, dies_str, territori_label
#       (dies_str = "1 dia" / "N dies", agreement-correct; see utils)
A6_CANCO_RECENT = {
    "short": [
        "Cançó nova de pes: «{canco}» al {posicio_ordinal} 🆕",
        "Just sortida i ja al top: {artista} {posicio_ordinal} 🚀",
        "Cançó {de_artista} de {dies_str}, al {posicio_ordinal} ⚡",
        "Estrena recent al top: «{canco}» {posicio_ordinal} 🎬",
        "{artista} estrena i directe al {posicio_ordinal} 💫",
        "Cançó nova al top {territori_label}: «{canco}» 🌱",
        "Acabada de publicar i ja al top: {artista} 🪴",
        "«{canco}» {de_artista}, novetat al {posicio_ordinal} 🌟",
        "Nou material {de_artista} al top: {posicio_ordinal} 🎶",
        "Just publicada i ja al top {territori_label}: {artista} 📅",
        "Cançó fresca al top: «{canco}» {posicio_ordinal} 🍃",
        "{artista} llança «{canco}» i la veiem al {posicio_ordinal} 💥",
        "Acaba de sortir i ja és al top: «{canco}» ✨",
        "Estrena {de_artista}, al {posicio_ordinal} {territori_ordinal} 🎁",
        "Cançó d'aquest mes ja al top: «{canco}» 🔔",
    ],
    "medium": [
        "Cançó nova de pes: «{canco}», {de_artista}, ja és al {posicio_ordinal} {territori_ordinal} amb només {dies_str} des de la publicació. 🆕",
        "Just publicada i ja al top: {artista} entra al {posicio_ordinal} {territori_ordinal} amb «{canco}», cançó de fa només {dies_str}. 🚀",
        "Estrena recent al top {territori_label}: «{canco}», {de_artista}, debuta al {posicio_ordinal} {dies_str} després de sortir. ⚡",
        "Cançó nova {de_artista}: «{canco}» fa només {dies_str} que va sortir i ja és al {posicio_ordinal} {territori_ordinal}. 🎬",
        "Sortida de novetat al top {territori_label}: «{canco}» ({de_artista}, {dies_str} des de la publicació) ja és al {posicio_ordinal}. 💫",
        "{artista} llança «{canco}» i en {dies_str} arriba al {posicio_ordinal} {territori_ordinal}. Velocitat d'arribada. 🌱",
        "Acabada de sortir: «{canco}», {de_artista}, té {dies_str} de vida i ja figura al {posicio_ordinal} del top {territori_label}. 🪴",
        "Cançó d'aquest mes ja al top: «{canco}», {de_artista}, és al {posicio_ordinal} {territori_ordinal} amb només {dies_str} des de l'estrena. 🌟",
        "Estrena fresca a la llista {territori_label}: {artista} arriba al {posicio_ordinal} amb «{canco}», publicada fa {dies_str}. 📅",
        "Cançó fresca al top: «{canco}», {de_artista}, ja és al {posicio_ordinal} {territori_ordinal} després de només {dies_str}. 🎶",
        "{artista} treu «{canco}» i ja la trobem al {posicio_ordinal} {territori_ordinal}, amb tot just {dies_str} des de la publicació. 💥",
        "Acaba de sortir i ja és al top: «{canco}», {de_artista}, ocupa el {posicio_ordinal} {territori_ordinal} amb {dies_str} des de l'estrena. ✨",
        "Sortida + arribada en una setmana: «{canco}», {de_artista}, és al {posicio_ordinal} {territori_ordinal} amb {dies_str} de vida. 🎁",
        "Cançó nova al top {territori_label}: {artista} arriba al {posicio_ordinal} amb «{canco}», estrenada fa {dies_str}. 🍃",
        "Novetat de pes: «{canco}», {de_artista}, té {dies_str} des de la publicació i ja figura al {posicio_ordinal} {territori_ordinal}. 🔔",
    ],
    "long": [
        "Hi ha singles que tarden setmanes a obrir-se camí; «{canco}», {de_artista}, no ha estat d'aquests. Amb només {dies_str} des de la publicació, ja figura al {posicio_ordinal} {territori_ordinal}. La velocitat d'arribada al top sol predir la profunditat de l'arrelament. 🆕",
        "{artista} ha llançat «{canco}» fa {dies_str} i ja la veiem al {posicio_ordinal} del top {territori_label}. Aquestes corbes d'arribada ràpida acostumen a indicar una connexió immediata amb l'oient. 🚀",
        "Estrena recent que ja fa soroll a la llista {territori_label}: «{canco}», {de_artista}, ocupa el {posicio_ordinal} {dies_str} després de sortir. Les arribades així de ràpides sovint són singles ja rodats en directe abans de la sortida. ⚡",
        "Acabada de sortir: «{canco}», {de_artista}, té només {dies_str} des de la publicació i ja és al {posicio_ordinal} {territori_ordinal}. Pocs llançaments arriben a la llista amb aquesta velocitat de creuer. 🎬",
        "{artista} firma una de les arribades més ràpides de l'any: «{canco}» entra al {posicio_ordinal} {territori_ordinal} amb {dies_str} des de l'estrena. La música d'avui premia la velocitat, però aquesta és notable. 💫",
        "Cançó d'aquest mes al top {territori_label}: «{canco}», {de_artista}, ocupa el {posicio_ordinal} amb només {dies_str} des de la sortida. Les corbes d'arribada així són habitualment singles que ja sonaven en directe. 🌱",
        "{dies_str} són pocs per a treure'n lluc, però «{canco}», {de_artista}, ja és al {posicio_ordinal} {territori_ordinal}. La velocitat amb què s'instal·la a dalt sol ser un bon predictor de la durada. 🪴",
        "Sortida i arribada gairebé simultànies: «{canco}», {de_artista}, té {dies_str} des de l'estrena i ja figura al {posicio_ordinal} {territori_ordinal}. La capacitat d'entrar al top amb la cançó tan recent és una raresa cada cop més freqüent. 🌟",
        "Cançó fresca, arribada fresca. «{canco}» {de_artista} té només {dies_str} de vida i ja és al {posicio_ordinal} {territori_ordinal}. Quan un llançament fa aquest camí, la trajectòria immediata sol ser de pujada. 📅",
        "{artista} llança «{canco}» i en una setmana la trobem al {posicio_ordinal} {territori_ordinal}. La velocitat d'entrada acostuma a ser senyal d'una base sòlida d'oients esperant la sortida. 🎶",
        "Aquesta setmana al top {territori_label}, una de les notícies és la velocitat: «{canco}», {de_artista}, ha trigat només {dies_str} a arribar al {posicio_ordinal}. Material acabat de sortir, ja al cap de la llista. 💥",
        "Estrena ràpida a la llista {territori_label}: «{canco}», {de_artista}, ocupa el {posicio_ordinal} {dies_str} després de la publicació. Mig estrena, mig confirmació; la llista l'avala de seguida. ✨",
        "Sortida + top en menys d'un mes: «{canco}», {de_artista}, té {dies_str} i ja és al {posicio_ordinal} {territori_ordinal}. La velocitat d'aterratge a la llista diu tant com el lloc d'aterratge. 🎁",
        "Cançó fresca al top {territori_label}: {artista} estrena «{canco}» fa {dies_str} i ja la veiem al {posicio_ordinal}. Aquest tipus d'arribada acostuma a quedar-se. 🍃",
        "Una de les arribades més netes del mes al top {territori_label}: «{canco}», {de_artista}, debuta al {posicio_ordinal} amb només {dies_str} des de l'estrena. Cançó recent i ja consolidada a la llista. 🔔",
    ],
}


# ── A7: long-runner in the top 10 ───────────────────────────────────
# data: artista, de_artista, canco, mesos, territori_label
A7_LONG_RUNNER = {
    "short": [
        "«{canco}» segueix al top després de {mesos} mesos 🪨",
        "Marathonista: «{canco}» {de_artista} {mesos} mesos 🏃",
        "{mesos} mesos i seguim aquí: {artista} 🌳",
        "Veterana al top: «{canco}» fa {mesos} mesos 🌅",
        "Resistència de «{canco}»: {mesos} mesos al top 🕰️",
        "{artista} aguanta {mesos} mesos al top {territori_label} ⏳",
        "Cançó d'arrel: «{canco}», {mesos} mesos a la llista 📚",
        "Pas del temps: {artista} segueix al top ({mesos} mesos) 📆",
        "Aguanta i aguanta: «{canco}» {mesos} mesos 🪵",
        "Long-runner: {artista} amb «{canco}» 🛤️",
        "Memòria llarga: {artista} {mesos} mesos al top 📜",
        "Estable al top: «{canco}» {de_artista} ⚓",
        "Velocista convertit en fons: «{canco}» 🎯",
        "Sense pressa: «{canco}» encadena mesos al top 🦦",
        "{mesos} mesos al top {territori_label}: {artista} 🌷",
    ],
    "medium": [
        "Cançó persistent al top {territori_label}: «{canco}», {de_artista}, ja fa {mesos} mesos que figura a la llista. 🪨",
        "{artista} signa una de les resistències més clares: «{canco}» encadena {mesos} mesos al top {territori_label}. 🏃",
        "Memòria llarga al top {territori_label}: «{canco}», {de_artista}, segueix a la llista després de {mesos} mesos. 🌳",
        "Cap pressa per anar-se'n: «{canco}», {de_artista}, fa {mesos} mesos que viu al top {territori_label}. 🌅",
        "Sense afluixar el ritme: {artista} suma {mesos} mesos a la llista {territori_label} amb «{canco}». 🕰️",
        "Cançó d'arrel: «{canco}», {de_artista}, té {mesos} mesos al top {territori_label} i no afluixa. ⏳",
        "Cançó-fons: «{canco}» {de_artista} fa {mesos} mesos que sona al top {territori_label}. 📚",
        "Long-run consolidat: {artista} encadena {mesos} mesos a la llista {territori_label} amb «{canco}». 📆",
        "Estabilitat al top {territori_label}: «{canco}», {de_artista}, manté presència {mesos} mesos després de l'estrena. 🪵",
        "Cançó duradora a la llista {territori_label}: «{canco}», {de_artista}, viu al top {mesos} mesos. 🛤️",
        "Persistència rara aquesta: «{canco}», {de_artista}, suma {mesos} mesos al top {territori_label}. 📜",
        "{artista} té al top {territori_label} «{canco}» com a cançó-pilar des de fa {mesos} mesos. ⚓",
        "Veterana fidel a la llista: «{canco}» {de_artista} duu {mesos} mesos al top {territori_label}. 🦦",
        "{mesos} mesos de top per a «{canco}», {de_artista}. Resistència que es nota a la llista {territori_label}. 🎯",
        "Cançó d'estiu, de tardor i d'hivern a la llista {territori_label}: {artista} suma {mesos} mesos al top amb «{canco}». 🌷",
    ],
    "long": [
        "Hi ha cançons que entren i surten ràpid del top, i n'hi ha que s'hi instal·len. La {de_artista} aquest any és, clarament, de les segones: «{canco}» ja fa {mesos} mesos que figura a la llista {territori_label}. 🪨",
        "Persistència rara: «{canco}», {de_artista}, encadena {mesos} mesos al top {territori_label}. Les permanències així de llargues acostumen a indicar que la cançó ha trobat lloc més enllà del moment de l'estrena. 🏃",
        "Long-runner consolidat. {artista} té al top {territori_label} la seva «{canco}» com a presència fixa des de fa {mesos} mesos. Aquestes permanències llargues són les que defineixen els discos més recordats. 🌳",
        "Memòria llarga a la llista {territori_label}. «{canco}», {de_artista}, ha resistit {mesos} mesos al top: un nombre que fa que la cançó ja no sigui novetat sinó referència. 🌅",
        "{artista} ha fet de «{canco}» una cançó-pilar a la llista {territori_label}: {mesos} mesos al top, sense que el pas del temps li passi factura. La definició del long-run. 🕰️",
        "Sense afluixar. «{canco}», {de_artista}, suma {mesos} mesos al top {territori_label} i continua. Aquestes permanències són la diferència entre un single i una cançó que entra al repertori cultural. ⏳",
        "Cançó d'arrel a la llista {territori_label}: «{canco}», {de_artista}, ja fa {mesos} mesos que viu al top. Els long-runners d'aquesta durada són una raresa que mereix subratllat editorial. 📚",
        "{mesos} mesos a la llista {territori_label} per a «{canco}», {de_artista}. Quan una cançó arriba a aquesta xifra, ja s'ha guanyat un lloc estable al repertori comú de l'oient. 📆",
        "Veterana fidel al top {territori_label}. {artista} suma {mesos} mesos a la llista amb «{canco}», una xifra que comença a entrar al territori dels casos a recordar. 🪵",
        "Estabilitat curiosa al top {territori_label}. «{canco}», {de_artista}, fa {mesos} mesos que figura a la llista: gairebé un de cada quatre singles surten i tornen, però aquest no surt mai. 🛤️",
        "{artista} firma una de les permanències més llargues de la llista {territori_label}: {mesos} mesos al top amb «{canco}». La definició del clàssic instantani. 📜",
        "Cap pressa per anar-se'n. «{canco}», {de_artista}, ha sumat {mesos} mesos a la llista {territori_label}, i la seva presència sembla estable per a temporades més. ⚓",
        "Quan una cançó porta {mesos} mesos a la llista, ja no és la novetat sinó la columna vertebral. {artista} té «{canco}» exactament en aquest punt al top {territori_label}. 🦦",
        "Cançó de calaix i de directe alhora. {artista} suma {mesos} mesos al top {territori_label} amb «{canco}», una xifra que ja comença a entrar a les llistes d'arrelament generacional. 🎯",
        "Cançó d'estiu, tardor i hivern. {artista} encadena {mesos} mesos al top {territori_label} amb «{canco}»: la permanència durant tantes estacions consecutives diu més del que sembla. 🌷",
    ],
}


# ── A8: strong climb (>=10 positions, now in top 10) ────────────────
# data: artista, de_artista, canco, posicio, pujada, territori_label
A8_PUJADA_FORTA = {
    "short": [
        "Salt de {pujada} llocs: «{canco}» al {posicio_ordinal} 📈",
        "{artista} puja {pujada} posicions al top {territori_label} 🚀",
        "Pujada brutal: «{canco}» {pujada} llocs en una setmana ⚡",
        "{artista} es planta al {posicio_ordinal} amb un salt de {pujada} 🪂",
        "Cop de mà: «{canco}» {de_artista} +{pujada} 💪",
        "Ascens fulgurant {de_artista}: +{pujada} llocs 🌟",
        "«{canco}» grimpa {pujada} llocs: ara al {posicio_ordinal} 🏔️",
        "+{pujada} {de_artista} aquesta setmana 📊",
        "Empenta forta: {artista} salta {pujada} llocs ✨",
        "Pujada notable: «{canco}» al {posicio_ordinal} (+{pujada}) 🔥",
        "{artista} guanya {pujada} posicions al top {territori_label} 💫",
        "Salt de pell {de_artista}: +{pujada} 🎢",
        "Mou-te ràpid: «{canco}» +{pujada} llocs 🏃",
        "Ascens setmanal de {pujada} per a «{canco}» 📋",
        "{artista} grimpa {pujada} llocs al top 🧗",
    ],
    "medium": [
        "Salt de {pujada} posicions per a «{canco}» {de_artista}: ara és al {posicio_ordinal} del top {territori_label}. 📈",
        "{artista} signa una de les pujades més fortes de la setmana: +{pujada} llocs fins al {posicio_ordinal} {territori_ordinal}. 🚀",
        "Ascens fulgurant al top {territori_label}: «{canco}», {de_artista}, puja {pujada} llocs i es planta al {posicio_ordinal}. ⚡",
        "Setmana de pujada {per_a_artista}: «{canco}» fa +{pujada} posicions i arriba al {posicio_ordinal} {territori_ordinal}. 🪂",
        "Empenta forta al top {territori_label}: «{canco}», {de_artista}, puja {pujada} llocs en una setmana. 💪",
        "Ascens net a la llista {territori_label}: {artista} guanya {pujada} posicions amb «{canco}» fins al {posicio_ordinal}. 🌟",
        "Cop de mà al top {territori_label}: «{canco}», {de_artista}, salta +{pujada} llocs i es planta al {posicio_ordinal}. 🏔️",
        "Pujada de pes: {artista} grimpa {pujada} posicions i col·loca «{canco}» al {posicio_ordinal} {territori_ordinal}. 📊",
        "Setmana de força per a «{canco}», {de_artista}: +{pujada} llocs fins al {posicio_ordinal} de la llista {territori_label}. ✨",
        "Ascens del setmanari: {artista} fa pujar «{canco}» {pujada} posicions, ara al {posicio_ordinal} {territori_ordinal}. 🔥",
        "Salt notable al top {territori_label}: «{canco}», {de_artista}, suma +{pujada} llocs i arriba al {posicio_ordinal}. 💫",
        "Empenta de l'oient: {artista} guanya {pujada} posicions amb «{canco}», ara al {posicio_ordinal} {territori_ordinal}. 🏃",
        "{artista} grimpa la llista {territori_label}: «{canco}» fa +{pujada} llocs fins al {posicio_ordinal}. 🧗",
        "Pujada vertiginosa: «{canco}», {de_artista}, fa +{pujada} posicions i es planta al {posicio_ordinal} del top {territori_label}. 🎢",
        "Ascens consolidat: {artista} suma {pujada} llocs a la llista {territori_label} amb «{canco}», ara al {posicio_ordinal}. 📋",
    ],
    "long": [
        "Pujada de les que es noten a la llista {territori_label}. «{canco}», {de_artista}, ha sumat {pujada} llocs en una setmana i ara és al {posicio_ordinal}. Aquests salts acostumen a indicar un viratge cultural: una cançó que ha trobat el seu moment. 📈",
        "{artista} signa una de les ascensions més fortes de la setmana: «{canco}» fa +{pujada} posicions fins al {posicio_ordinal} {territori_ordinal}. Quan una cançó accelera així, la trajectòria immediata sol ser de continuar pujant. 🚀",
        "Ascens net al top {territori_label}: «{canco}», {de_artista}, puja {pujada} llocs en set dies i es planta al {posicio_ordinal}. La velocitat de pujada acostuma a ser tan reveladora com la posició final. ⚡",
        "Empenta forta a la llista {territori_label} aquesta setmana. {artista} guanya {pujada} posicions amb «{canco}» fins al {posicio_ordinal}: un d'aquests salts que canvien la fotografia d'un mes. 🪂",
        "Setmana de força {per_a_artista}. «{canco}» ha pujat {pujada} posicions al top {territori_label} fins al {posicio_ordinal}, signant un dels salts més clars del període. 💪",
        "Cop de mà a {artista} aquesta setmana. «{canco}» grimpa {pujada} posicions a la llista {territori_label} fins al {posicio_ordinal}. La diferència entre una pujada anecdòtica i una de notable es mesura amb les xifres. 🌟",
        "Pujada vertiginosa al top {territori_label}. «{canco}», {de_artista}, suma {pujada} llocs en set dies i ara és al {posicio_ordinal}. Quan els ascensos arriben a aquesta magnitud, els seguim de prop. 🏔️",
        "Ascens consolidat a la llista {territori_label}: «{canco}», {de_artista}, ha sumat {pujada} posicions i s'ha plantat al {posicio_ordinal}. La permanència de l'efecte sol mesurar-se a la setmana següent. 📊",
        "Empenta de l'oient feta xifra: {artista} puja {pujada} posicions amb «{canco}» al top {territori_label}, fins al {posicio_ordinal}. Les ascensions d'aquesta magnitud són les que indiquen el canvi de moment d'una cançó. ✨",
        "Setmana de força a la llista {territori_label}. {artista} fa pujar «{canco}» {pujada} llocs fins al {posicio_ordinal}, en un dels salts més vistosos del trimestre. 🔥",
        "Salt notable al top {territori_label}: «{canco}», {de_artista}, suma +{pujada} llocs i arriba al {posicio_ordinal}. Aquest tipus de pujada sol ser senyal d'un viratge cultural ben definit. 💫",
        "Empenta sostinguda: {artista} guanya {pujada} posicions amb «{canco}» a la llista {territori_label} fins al {posicio_ordinal}. Els ascensos que arriben a aquesta xifra acostumen a marcar el final d'una etapa i el principi d'una altra. 🏃",
        "{artista} grimpa a la llista {territori_label}: «{canco}» fa +{pujada} posicions i es planta al {posicio_ordinal}. Una de les pujades més contundents que veurem aquest mes. 🧗",
        "Pujada brutal al top {territori_label}. «{canco}», {de_artista}, salta {pujada} llocs en set dies fins al {posicio_ordinal}. La velocitat d'aquestes pujades sol predir si seran sostingudes. 🎢",
        "{pujada} posicions amunt en una setmana per a «{canco}», {de_artista}. La cançó ara és al {posicio_ordinal} del top {territori_label}, signant un ascens de pes. 📋",
    ],
}


# ── A9: debut at any position (4-40) — ADR-0008 ─────────────────────
# data: artista, de_artista, canco, posicio, posicio_ordinal, territori_label
A9_DEBUT_ANYWHERE = {
    "short": [
        "Debut al top {territori_label}: «{canco}» {de_artista} entra al {posicio_ordinal} 🆕",
        "Nova entrada al top {territori_label}: «{canco}» al {posicio_ordinal} 🚪",
        "«{canco}» {de_artista} estrena top al {posicio_ordinal} 🎬",
        "{artista} debuta al top {territori_label}: «{canco}» al {posicio_ordinal} ✨",
        "Cara nova a la llista {territori_label}: «{canco}» al {posicio_ordinal} 👋",
        "Entrada fresca al top {territori_label}: «{canco}» {de_artista} al {posicio_ordinal} 🌱",
        "S'estrena a la llista: «{canco}», {de_artista}, al {posicio_ordinal} 🎯",
        "Debut tranquil al top {territori_label}: {artista} al {posicio_ordinal} 🪴",
        "Aterratge al top {territori_label}: «{canco}» al {posicio_ordinal} 🛬",
        "{artista} pica a la porta del top al {posicio_ordinal} amb «{canco}» 🚀",
        "Estrena al cos del top {territori_label}: «{canco}» al {posicio_ordinal} 📍",
        "Nou nom a la llista {territori_label}: {artista} al {posicio_ordinal} 🔔",
        "Apareix al top {territori_label} «{canco}» {de_artista}, al {posicio_ordinal} 💡",
        "Primer cop al top {territori_label} per a «{canco}» al {posicio_ordinal} 🌟",
        "Entra a la llista {territori_label} «{canco}» {de_artista}, al {posicio_ordinal} 🎵",
    ],
    "medium": [
        "Debut al top {territori_label}: «{canco}», {de_artista}, entra al {posicio_ordinal} aquesta setmana. Una nova cara que ja ha trobat el seu lloc. 🆕",
        "Nova entrada a la llista {territori_label}: «{canco}» {de_artista} aterra al {posicio_ordinal} per estrenar-se. 🚪",
        "{artista} debuta al top {territori_label} amb «{canco}», que entra directament al {posicio_ordinal}. 🎬",
        "Cara nova a la llista {territori_label}: «{canco}», {de_artista}, irromp al {posicio_ordinal} amb una notícia tranquil·la però real. 👋",
        "Entrada fresca al top {territori_label}: «{canco}» entra al {posicio_ordinal} i confirma que el catàleg es renova setmana a setmana. 🌱",
        "S'estrena al top {territori_label} «{canco}», {de_artista}, al {posicio_ordinal}: una entrada modesta amb potencial de pujar. 🎯",
        "Debut tranquil al top {territori_label}: {artista} arriba a la llista al {posicio_ordinal} amb «{canco}». 🪴",
        "Aterratge net al top {territori_label}: «{canco}», {de_artista}, entra a la llista al {posicio_ordinal} sense estridències. 🛬",
        "{artista} pica a la porta del top {territori_label}: «{canco}» entra al {posicio_ordinal} i busca quedar-s'hi setmanes. 🚀",
        "Estrena al cos del top {territori_label}: «{canco}», {de_artista}, debuta al {posicio_ordinal}. 📍",
        "Nou nom a la llista {territori_label}: {artista} entra al top al {posicio_ordinal} amb «{canco}», una novetat per descobrir. 🔔",
        "Apareix al top {territori_label} «{canco}», {de_artista}: aterra al {posicio_ordinal} per quedar-se a prova. 💡",
        "Primer cop al top {territori_label} per a «{canco}» {de_artista}, que entra al {posicio_ordinal} aquesta setmana. 🌟",
        "Entra a la llista {territori_label} «{canco}» {de_artista}, al {posicio_ordinal}: el catàleg setmanal incorpora una nova proposta. 🎵",
        "Debut amb personalitat al top {territori_label}: «{canco}» {de_artista} arriba al {posicio_ordinal} i marca presència. ✨",
    ],
    "long": [
        "Debut al top {territori_label}: «{canco}», {de_artista}, entra al {posicio_ordinal} aquesta setmana. Una entrada moderada però real, que demostra que la llista té encara marge per a propostes que no han fet soroll de cop. 🆕",
        "Nova entrada a la llista {territori_label}: «{canco}» {de_artista} aterra al {posicio_ordinal} per estrenar-se. Veurem si el debut té continuïtat o si es queda en una sola visita al top. 🚪",
        "{artista} debuta al top {territori_label} amb «{canco}», que entra directament al {posicio_ordinal}. El primer cop a la llista mai és casualitat; sempre indica que alguna cosa s'està movent al territori. 🎬",
        "Cara nova a la llista {territori_label}: «{canco}», {de_artista}, irromp al {posicio_ordinal} amb una notícia tranquil·la però real. Aquest tipus de debut és sovint l'avantsala de pujades a l'alça. 👋",
        "Entrada fresca al top {territori_label}: «{canco}» entra al {posicio_ordinal} i confirma que el catàleg es renova setmana a setmana, sense necessitat d'un cop d'efecte als llocs alts. 🌱",
        "S'estrena al top {territori_label} «{canco}», {de_artista}, al {posicio_ordinal}: una entrada modesta amb potencial de pujar les properes setmanes, depenent del recorregut que sàpiga construir. 🎯",
        "Debut tranquil al top {territori_label}: {artista} arriba a la llista al {posicio_ordinal} amb «{canco}». La permanència és el que dirà si el debut consolida o si serà un pas curt. 🪴",
        "Aterratge net al top {territori_label}: «{canco}», {de_artista}, entra a la llista al {posicio_ordinal} sense estridències, però amb una posició respectable per a una primera setmana. 🛬",
        "{artista} pica a la porta del top {territori_label}: «{canco}» entra al {posicio_ordinal} i busca quedar-s'hi setmanes. Els debuts a la zona mitjana acostumen a ser els més estables. 🚀",
        "Estrena al cos del top {territori_label}: «{canco}», {de_artista}, debuta al {posicio_ordinal} amb un perfil discret però que mereix atenció els pròxims cicles. 📍",
        "Nou nom a la llista {territori_label}: {artista} entra al top al {posicio_ordinal} amb «{canco}», una novetat per descobrir abans que potser faci el salt cap a posicions més altes. 🔔",
        "Apareix al top {territori_label} «{canco}», {de_artista}: aterra al {posicio_ordinal} per quedar-se a prova. Els propers set dies dictaran si consolida la presència o si recula. 💡",
        "Primer cop al top {territori_label} per a «{canco}» {de_artista}, que entra al {posicio_ordinal} aquesta setmana. Una de les cares noves que cal seguir d'a prop a les pròximes edicions. 🌟",
        "Entra a la llista {territori_label} «{canco}» {de_artista}, al {posicio_ordinal}: el catàleg setmanal incorpora una nova proposta que ja ha trobat el seu lloc inicial al top. 🎵",
        "Debut amb personalitat al top {territori_label}: «{canco}» {de_artista} arriba al {posicio_ordinal} i marca presència. Caldrà veure si la setmana que ve manté o millora la posició d'avui. ✨",
    ],
}


# ── A10: artist's first-ever appearance — ADR-0008 ──────────────────
# data: artista, de_artista, canco, posicio, posicio_ordinal, territori_label
A10_ARTISTA_FIRST_EVER = {
    "short": [
        "Primera vegada al top {territori_label} {per_a_artista} amb «{canco}», al {posicio_ordinal} 🎉",
        "{artista} estrena top {territori_label}: «{canco}» al {posicio_ordinal} 🎊",
        "Cap aparició prèvia: {artista} arriba al top al {posicio_ordinal} amb «{canco}» 🆕",
        "Estrena absoluta al top {territori_label}: {artista} amb «{canco}», al {posicio_ordinal} ✨",
        "Primer cop de la història {per_a_artista} al top, al {posicio_ordinal} 🪄",
        "Debut històric al top {territori_label} {per_a_artista} amb «{canco}» 🏁",
        "{artista} entra per primera vegada al top {territori_label} al {posicio_ordinal} 🚪",
        "Cap aparició anterior: {artista} arriba a la llista al {posicio_ordinal} 🎬",
        "Top {territori_label} estrena nom: {artista} amb «{canco}», al {posicio_ordinal} 🌟",
        "Hola, top {territori_label}: {artista} debuta a la llista al {posicio_ordinal} 👋",
        "Una primera vegada a la llista {territori_label}: {artista} amb «{canco}» 💫",
        "Salt fundacional: {artista} entra al top al {posicio_ordinal} 🪜",
        "Inauguració al top {territori_label} {per_a_artista} al {posicio_ordinal} 🎀",
        "Mai havia tocat el top {territori_label} fins ara: «{canco}» {de_artista}, al {posicio_ordinal} 🔓",
        "Cara absolutament nova a la llista {territori_label}: {artista} al {posicio_ordinal} 🌅",
    ],
    "medium": [
        "Primera vegada al top {territori_label} {per_a_artista}: «{canco}» entra al {posicio_ordinal} sense cap aparició anterior a la llista. 🎉",
        "{artista} estrena top {territori_label} amb «{canco}», que el situa al {posicio_ordinal}: una porta oberta a futures presències. 🎊",
        "Cap aparició prèvia {per_a_artista}: el seu debut absolut al top {territori_label} arriba al {posicio_ordinal} amb «{canco}». 🆕",
        "Estrena absoluta al top {territori_label}: {artista} apareix per primer cop a la llista amb «{canco}», al {posicio_ordinal}. ✨",
        "Primer cop de la història al top {territori_label} {per_a_artista}: «{canco}» l'asseu al {posicio_ordinal} d'un cop. 🪄",
        "Debut històric al top {territori_label} {per_a_artista}: la setmana es marca al calendari amb «{canco}» al {posicio_ordinal}. 🏁",
        "{artista} entra per primera vegada al top {territori_label} al {posicio_ordinal}: cap edició anterior l'havia tingut. 🚪",
        "Cap aparició anterior a la llista {territori_label} {per_a_artista}: «{canco}» trenca el silenci al {posicio_ordinal}. 🎬",
        "Top {territori_label} estrena nom: {artista} hi entra per primera vegada amb «{canco}», al {posicio_ordinal}. 🌟",
        "Hola, top {territori_label}: {artista} es presenta a la llista al {posicio_ordinal} amb «{canco}», sense passat al top. 👋",
        "Una primera vegada a la llista {territori_label}: «{canco}», {de_artista}, situa l'artista al {posicio_ordinal} per estrena. 💫",
        "Salt fundacional al top {territori_label}: {artista} arriba al {posicio_ordinal} amb «{canco}» i obre el seu compte a la llista. 🪜",
        "Inauguració al top {territori_label} {per_a_artista}: «{canco}» l'estrena al {posicio_ordinal}, sense cap precedent a la llista. 🎀",
        "Mai havia tocat el top {territori_label} fins ara: «{canco}» {de_artista} arriba al {posicio_ordinal} per primer cop. 🔓",
        "Cara absolutament nova a la llista {territori_label}: {artista} debuta al top al {posicio_ordinal} amb «{canco}». 🌅",
    ],
    "long": [
        "Primera vegada al top {territori_label} {per_a_artista}: «{canco}» entra al {posicio_ordinal} sense cap aparició anterior a la llista. Aquestes estrenes absolutes són les que confirmen que el catàleg local continua creixent. 🎉",
        "{artista} estrena top {territori_label} amb «{canco}», que el situa al {posicio_ordinal}: una porta oberta a futures presències, sigui amb aquesta cançó o amb les properes. 🎊",
        "Cap aparició prèvia {per_a_artista}: el seu debut absolut al top {territori_label} arriba al {posicio_ordinal} amb «{canco}». Una entrada que mereix seguiment a llarg termini. 🆕",
        "Estrena absoluta al top {territori_label}: {artista} apareix per primer cop a la llista amb «{canco}», al {posicio_ordinal}. Les primeres vegades són dades; allò que diran els propers cicles és la veritable notícia. ✨",
        "Primer cop de la història al top {territori_label} {per_a_artista}: «{canco}» l'asseu al {posicio_ordinal} d'un cop. Una entrada significativa, perquè la història a la llista es comença aquesta setmana. 🪄",
        "Debut històric al top {territori_label} {per_a_artista}: la setmana es marca al calendari amb «{canco}» al {posicio_ordinal}. És el tipus de notícia que recolza la idea que el top setmanal és un termòmetre, no un mirall. 🏁",
        "{artista} entra per primera vegada al top {territori_label} al {posicio_ordinal} amb «{canco}»: cap edició anterior l'havia tingut, i això converteix aquesta entrada en una primera fita pública. 🚪",
        "Cap aparició anterior a la llista {territori_label} {per_a_artista}: «{canco}» trenca el silenci al {posicio_ordinal} i suma un nom més al cens d'artistes que han passat pel top. 🎬",
        "Top {territori_label} estrena nom: {artista} hi entra per primera vegada amb «{canco}», al {posicio_ordinal}. Els debuts absoluts són pocs cada any; aquest és un d'ells. 🌟",
        "Hola, top {territori_label}: {artista} es presenta a la llista al {posicio_ordinal} amb «{canco}», sense passat al top. La presència mereix aquesta primera línia abans de mirar com aguanta. 👋",
        "Una primera vegada a la llista {territori_label}: «{canco}», {de_artista}, situa l'artista al {posicio_ordinal} per estrena. Aquestes entrades sense precedents són les que evidencien la diversitat real del catàleg. 💫",
        "Salt fundacional al top {territori_label}: {artista} arriba al {posicio_ordinal} amb «{canco}» i obre el seu compte a la llista. Caldrà veure si aquesta primera setmana és el principi d'una sèrie o un episodi puntual. 🪜",
        "Inauguració al top {territori_label} {per_a_artista}: «{canco}» l'estrena al {posicio_ordinal}, sense cap precedent a la llista. La inauguració, com totes les inauguracions, demana confirmació en les setmanes vinents. 🎀",
        "Mai havia tocat el top {territori_label} fins ara: «{canco}» {de_artista} arriba al {posicio_ordinal} per primer cop. La llista setmanal s'eixampla amb una entrada netament nova. 🔓",
        "Cara absolutament nova a la llista {territori_label}: {artista} debuta al top al {posicio_ordinal} amb «{canco}». La història al top comença aquesta setmana; veurem com creix les properes. 🌅",
    ],
}


# ── A11: top-5 song drops out of top 10 — ADR-0008 ──────────────────
# data: artista, de_artista, canco, posicio_anterior, posicio_anterior_ordinal,
# posicio_nova_str, territori_label
A11_TOP5_DROP_GENERIC = {
    "short": [
        "Caiguda forta al top {territori_label}: «{canco}» {de_artista}, del {posicio_anterior_ordinal} a {posicio_nova_str} 📉",
        "«{canco}» {de_artista} surt del podi: del {posicio_anterior_ordinal} a {posicio_nova_str} 🪂",
        "Salta del top 5 «{canco}» {de_artista}: del {posicio_anterior_ordinal} a {posicio_nova_str} ⬇️",
        "Cau del cim {de_artista}: «{canco}» del {posicio_anterior_ordinal} a {posicio_nova_str} 🍂",
        "«{canco}» perd lloc al podi {territori_ordinal}: {posicio_nova_str} 🪨",
        "Recanvi al podi: «{canco}» {de_artista}, del {posicio_anterior_ordinal} a {posicio_nova_str} 🔁",
        "Sortida del podi {territori_ordinal}: «{canco}» del {posicio_anterior_ordinal} a {posicio_nova_str} 🚪",
        "Baixa al cos del top «{canco}» {de_artista}, del {posicio_anterior_ordinal} a {posicio_nova_str} 📊",
        "«{canco}» {de_artista} cedeix podi: del {posicio_anterior_ordinal} a {posicio_nova_str} 🛤️",
        "Caiguda notable al top {territori_label}: «{canco}» del {posicio_anterior_ordinal} a {posicio_nova_str} 🌬️",
        "Trànsit del podi al cos: «{canco}» {de_artista}, {posicio_nova_str} 🚏",
        "«{canco}» perd força aquesta setmana: del {posicio_anterior_ordinal} a {posicio_nova_str} 🌒",
        "El podi {territori_ordinal} reordena: «{canco}» {de_artista} surt del 5 ⛔",
        "Setmana de retrocés {per_a_artista} amb «{canco}»: {posicio_nova_str} ⏬",
        "{artista} cedeix el podi: «{canco}» a {posicio_nova_str} 🧭",
    ],
    "medium": [
        "Caiguda forta al top {territori_label}: «{canco}», {de_artista}, passa del {posicio_anterior_ordinal} a {posicio_nova_str} en una sola setmana. 📉",
        "«{canco}» {de_artista} surt del podi: del {posicio_anterior_ordinal} a {posicio_nova_str}, un salt cap avall que mereix nota. 🪂",
        "Salt fora del top 5: «{canco}» {de_artista} passa del {posicio_anterior_ordinal} a {posicio_nova_str} aquesta setmana. ⬇️",
        "Cau del cim {de_artista}: «{canco}» va del {posicio_anterior_ordinal} a {posicio_nova_str}, deixant lloc al podi. 🍂",
        "«{canco}» perd lloc al podi {territori_ordinal} després d'estar al {posicio_anterior_ordinal}: ara és {posicio_nova_str}. 🪨",
        "Recanvi al podi {territori_ordinal}: «{canco}» {de_artista} baixa del {posicio_anterior_ordinal} a {posicio_nova_str}. 🔁",
        "Sortida del podi al top {territori_label}: «{canco}» va del {posicio_anterior_ordinal} a {posicio_nova_str} en un cicle. 🚪",
        "Baixada al cos del top: «{canco}» {de_artista} passa del {posicio_anterior_ordinal} a {posicio_nova_str}. 📊",
        "«{canco}» {de_artista} cedeix el podi: del {posicio_anterior_ordinal} a {posicio_nova_str}, l'aterratge més dur de la setmana. 🛤️",
        "Caiguda notable al top {territori_label}: «{canco}» passa del {posicio_anterior_ordinal} a {posicio_nova_str} en set dies. 🌬️",
        "Trànsit del podi al cos del top: «{canco}», {de_artista}, és ara {posicio_nova_str} després de venir del {posicio_anterior_ordinal}. 🚏",
        "«{canco}» perd força aquesta setmana al top {territori_label}: del {posicio_anterior_ordinal} a {posicio_nova_str}. 🌒",
        "El podi {territori_ordinal} es reordena: «{canco}», {de_artista}, surt del top 5 i passa a {posicio_nova_str}. ⛔",
        "Setmana de retrocés {per_a_artista} amb «{canco}»: del {posicio_anterior_ordinal} a {posicio_nova_str} en un cicle complet. ⏬",
        "{artista} cedeix el podi: «{canco}» passa del {posicio_anterior_ordinal} a {posicio_nova_str} aquesta setmana. 🧭",
    ],
    "long": [
        "Caiguda forta al top {territori_label}: «{canco}», {de_artista}, passa del {posicio_anterior_ordinal} a {posicio_nova_str} en una sola setmana. El podi de la setmana anterior ja és història per a aquesta peça. 📉",
        "«{canco}» {de_artista} surt del podi: del {posicio_anterior_ordinal} a {posicio_nova_str}, un salt cap avall que sovint precedeix la sortida definitiva del top. 🪂",
        "Salt fora del top 5: «{canco}» {de_artista} passa del {posicio_anterior_ordinal} a {posicio_nova_str} aquesta setmana, un retrocés que cal contextualitzar amb les pròximes edicions. ⬇️",
        "Cau del cim {de_artista}: «{canco}» va del {posicio_anterior_ordinal} a {posicio_nova_str}, deixant lloc al podi. Les caigudes brusques no acostumen a recuperar-se en una setmana. 🍂",
        "«{canco}» perd lloc al podi {territori_ordinal} després d'estar al {posicio_anterior_ordinal}: ara és {posicio_nova_str}. El podi s'ha reordenat amb dues sortides i una entrada lateral. 🪨",
        "Recanvi al podi {territori_ordinal}: «{canco}» {de_artista} baixa del {posicio_anterior_ordinal} a {posicio_nova_str}, una caiguda sobtada al cos del top que demana atenció. 🔁",
        "Sortida del podi al top {territori_label}: «{canco}» va del {posicio_anterior_ordinal} a {posicio_nova_str} en un cicle. Aquest moviment no és casualitat; sovint es deu a una novetat que ha empès la cançó cap avall. 🚪",
        "Baixada al cos del top: «{canco}», {de_artista}, passa del {posicio_anterior_ordinal} a {posicio_nova_str}. La velocitat del salt és la que fa que mereixi una línia pròpia. 📊",
        "«{canco}» {de_artista} cedeix el podi: del {posicio_anterior_ordinal} a {posicio_nova_str}, l'aterratge més dur de la setmana al top {territori_label}. 🛤️",
        "Caiguda notable al top {territori_label}: «{canco}» passa del {posicio_anterior_ordinal} a {posicio_nova_str} en set dies, un dels moviments més bruscos d'aquest cicle. 🌬️",
        "Trànsit del podi al cos del top: «{canco}», {de_artista}, és ara {posicio_nova_str} després de venir del {posicio_anterior_ordinal}. Les caigudes des del top 5 acostumen a obrir lloc per a entrades fresques. 🚏",
        "«{canco}» perd força aquesta setmana al top {territori_label}: del {posicio_anterior_ordinal} a {posicio_nova_str}. Caldrà veure si toca fons o si manté la trajectòria a la baixa. 🌒",
        "El podi {territori_ordinal} es reordena: «{canco}», {de_artista}, surt del top 5 i passa a {posicio_nova_str}. La rotació del podi és el reflex del comportament de l'oient setmanal. ⛔",
        "Setmana de retrocés {per_a_artista} amb «{canco}»: del {posicio_anterior_ordinal} a {posicio_nova_str} en un cicle. Cal mirar el conjunt: a vegades les caigudes són temporals i a vegades són estructurals. ⏬",
        "{artista} cedeix el podi: «{canco}» passa del {posicio_anterior_ordinal} a {posicio_nova_str} aquesta setmana. La sortida del top 5 sempre marca un punt d'inflexió en la trajectòria de la cançó. 🧭",
    ],
}


# ── A12: artist emerging (no songs last week, ≥1 this week) — ADR-0008 ─
# data: artista, de_artista, canco, posicio, posicio_ordinal, territori_label
A12_ARTISTA_EMERGING = {
    "short": [
        "Torna al top {territori_label} {artista}: «{canco}» al {posicio_ordinal} 🔁",
        "Reapareix a la llista {artista} amb «{canco}» al {posicio_ordinal} 🌱",
        "{artista} torna a aparèixer al top {territori_label} al {posicio_ordinal} 🌿",
        "Setmana de retorn {per_a_artista}: «{canco}» al {posicio_ordinal} 🪴",
        "{artista} surt de pausa al top {territori_label} al {posicio_ordinal} 🌅",
        "Nova presència al top {territori_label} {per_a_artista}: «{canco}» al {posicio_ordinal} 🔔",
        "{artista} reentra a la llista {territori_label} al {posicio_ordinal} 🪜",
        "Retorn discret al top {territori_label} {per_a_artista}: «{canco}» al {posicio_ordinal} 🍃",
        "Es deixa veure de nou al top {territori_label} {artista} al {posicio_ordinal} 👀",
        "{artista} reapareix amb «{canco}» al top {territori_label} al {posicio_ordinal} 🌤️",
        "Tornada a la llista {territori_label} {per_a_artista} amb «{canco}» al {posicio_ordinal} 🚪",
        "{artista} torna a sumar setmana al top {territori_label} al {posicio_ordinal} 📒",
        "Nou tram al top {territori_label} {per_a_artista}: «{canco}» al {posicio_ordinal} 🪶",
        "La llista {territori_label} recupera {artista} al {posicio_ordinal} 🧭",
        "Retornen al top {territori_label} els noms {de_artista} al {posicio_ordinal} 🎈",
    ],
    "medium": [
        "Torna al top {territori_label} {artista}: «{canco}» entra al {posicio_ordinal} després d'haver estat fora de la llista la setmana passada. 🔁",
        "Reapareix a la llista {territori_label} {artista} amb «{canco}», ara al {posicio_ordinal}: una tornada modesta però comptable. 🌱",
        "{artista} torna a aparèixer al top {territori_label} al {posicio_ordinal} amb «{canco}» després d'un cicle absent. 🌿",
        "Setmana de retorn {per_a_artista}: «{canco}» el situa al {posicio_ordinal} del top {territori_label}. 🪴",
        "{artista} surt de pausa al top {territori_label}: «{canco}» l'asseu al {posicio_ordinal} aquesta setmana. 🌅",
        "Nova presència al top {territori_label} {per_a_artista}: «{canco}» entra al {posicio_ordinal}, recuperant lloc a la llista. 🔔",
        "{artista} reentra a la llista {territori_label} al {posicio_ordinal} després d'una setmana sense presència al top. 🪜",
        "Retorn discret al top {territori_label} {per_a_artista}: «{canco}» suma una entrada al {posicio_ordinal} aquesta setmana. 🍃",
        "Es deixa veure de nou al top {territori_label} {artista} amb «{canco}», al {posicio_ordinal} després de no aparèixer al cicle anterior. 👀",
        "{artista} reapareix amb «{canco}» al top {territori_label} al {posicio_ordinal}: una nota discreta, però útil per a la continuïtat. 🌤️",
        "Tornada a la llista {territori_label} {per_a_artista} amb «{canco}»: la cançó es col·loca al {posicio_ordinal} aquesta setmana. 🚪",
        "{artista} torna a sumar setmana al top {territori_label} al {posicio_ordinal}, recuperant el lloc a la llista. 📒",
        "Nou tram al top {territori_label} {per_a_artista}: «{canco}» reentra al {posicio_ordinal} aquesta setmana. 🪶",
        "La llista {territori_label} recupera {artista} al {posicio_ordinal}: una reaparició que es notarà en les setmanes properes. 🧭",
        "Retornen al top {territori_label} els noms {de_artista}: «{canco}» entra al {posicio_ordinal} aquesta setmana. 🎈",
    ],
    "long": [
        "Torna al top {territori_label} {artista}: «{canco}» entra al {posicio_ordinal} després d'haver estat fora de la llista la setmana passada. Les reaparicions són sovint el camí lent cap a una segona escalada. 🔁",
        "Reapareix a la llista {territori_label} {artista} amb «{canco}», ara al {posicio_ordinal}: una tornada modesta però comptable, que demana seguiment a llarg termini. 🌱",
        "{artista} torna a aparèixer al top {territori_label} al {posicio_ordinal} amb «{canco}» després d'un cicle absent. Sovint aquestes tornades són les que indiquen continuïtat real. 🌿",
        "Setmana de retorn {per_a_artista}: «{canco}» el situa al {posicio_ordinal} del top {territori_label}. La presència al top no és lineal; les pauses formen part del recorregut. 🪴",
        "{artista} surt de pausa al top {territori_label}: «{canco}» l'asseu al {posicio_ordinal} aquesta setmana, marcant una reentrada que mereix nota. 🌅",
        "Nova presència al top {territori_label} {per_a_artista}: «{canco}» entra al {posicio_ordinal}, recuperant lloc a la llista després d'una setmana de descans. 🔔",
        "{artista} reentra a la llista {territori_label} al {posicio_ordinal} després d'una setmana sense presència al top. Les reaparicions discretes consoliden trajectòries més que els salts brusques. 🪜",
        "Retorn discret al top {territori_label} {per_a_artista}: «{canco}» suma una entrada al {posicio_ordinal} aquesta setmana, un cicle després d'haver desaparegut de la llista. 🍃",
        "Es deixa veure de nou al top {territori_label} {artista} amb «{canco}», al {posicio_ordinal} després de no aparèixer al cicle anterior. La continuïtat en xifres és el millor termòmetre real. 👀",
        "{artista} reapareix amb «{canco}» al top {territori_label} al {posicio_ordinal}: una nota discreta, però útil per a la continuïtat del nom a la llista en cicles llargs. 🌤️",
        "Tornada a la llista {territori_label} {per_a_artista} amb «{canco}»: la cançó es col·loca al {posicio_ordinal} aquesta setmana, després d'una pausa breu al top. 🚪",
        "{artista} torna a sumar setmana al top {territori_label} al {posicio_ordinal}, recuperant el lloc a la llista. Aquestes reentrades són les que diferencien les trajectòries amb fons. 📒",
        "Nou tram al top {territori_label} {per_a_artista}: «{canco}» reentra al {posicio_ordinal} aquesta setmana i obre un nou capítol a la llista setmanal. 🪶",
        "La llista {territori_label} recupera {artista} al {posicio_ordinal} amb «{canco}»: una reaparició que es notarà en les setmanes properes si manté presència. 🧭",
        "Retornen al top {territori_label} els noms {de_artista} amb «{canco}», al {posicio_ordinal}: una entrada que tanca el cercle d'una absència curta. 🎈",
    ],
}


# ── Fallback: no scenario fired ────────────────────────────────────
# data: territori_label
FALLBACK_NO_EVENT = {
    "short": [
        "Setmana de manteniment al top {territori_label} 🌤️",
        "Sense grans sotragades a la llista {territori_label} 🪨",
        "Continuïtat al top {territori_label} aquesta setmana 🛤️",
        "Rànquing estable al territori {territori_label} 📊",
        "Les cares conegudes mantenen lloc al top 🪕",
        "Setmana sense grans canvis al top {territori_label} ☀️",
        "Top {territori_label} estable aquesta setmana 🌿",
        "Cap relleu fort al top {territori_label} 🕰️",
        "Setmana de calma a la llista {territori_label} 🌅",
        "Continua la setmana sense grans sorpreses 📆",
        "Rànquing {territori_label} sense canvis bruscos ✨",
        "Una setmana de continuïtat al top 🌳",
        "Sense recanvis al podi {territori_ordinal} aquesta setmana 🎼",
        "Top {territori_label}: tot a lloc 🎶",
        "Setmana plàcida a la llista {territori_label} 🍃",
    ],
    "medium": [
        "Setmana de continuïtat al top {territori_label}: les cares conegudes mantenen la seva posició al cim. 🌤️",
        "Sense grans sotragades a la llista {territori_label} aquesta setmana: el podi i el cos del top es mantenen com la setmana passada. 🪨",
        "Setmana de manteniment al top {territori_label}: no hi ha debuts forts ni caigudes notables, només la inèrcia de les cançons que segueixen sonant. 🛤️",
        "Rànquing estable al territori {territori_label}: les peces del podi setmanal queden on eren, sense grans pertorbacions. 📊",
        "Aquesta setmana al top {territori_label}, més del mateix: les cançons conegudes aguanten posició i la llista té poques sorpreses. 🪕",
        "Setmana de calma a la llista {territori_label}: sense canvis bruscos al cim ni al cos del top. ☀️",
        "El top {territori_label} no porta grans canvis aquesta setmana: les cares habituals mantenen la seva posició. 🌿",
        "Sense relleus forts al podi {territori_ordinal}: la llista es manté en línia amb la setmana passada. 🕰️",
        "Continuïtat al top {territori_label} d'aquesta setmana: el podi no es belluga, el cos de la llista tampoc. 🌅",
        "Setmana plàcida a la llista {territori_label}: cap esdeveniment ressenyable, només el manteniment de les posicions ja conegudes. 📆",
        "Rànquing {territori_label} sense canvis remarcables aquesta setmana: el top continua amb les seves cares conegudes al cap. ✨",
        "Continuïtat reposada a la llista {territori_label}: el top no canvia gaire i les cançons habituals continuen sumant setmanes. 🌳",
        "Sense recanvis al podi {territori_ordinal}: la setmana al top és més aviat d'inèrcia que de notícia. 🎼",
        "Setmana sense grans títols a la llista {territori_label}: les peces conegudes mantenen el lloc, i la novetat queda fora del podi aquesta vegada. 🎶",
        "Top {territori_label} en calma aquesta setmana: cap entrada destacada, cap caiguda notable. 🍃",
    ],
    "long": [
        "Setmana de continuïtat al top {territori_label}. Les cares conegudes mantenen la seva posició i no hi ha debuts ni relleus forts al podi. Aquestes setmanes són les que confirmen les tendències de les setmanes anteriors. 🌤️",
        "Sense grans sotragades a la llista {territori_label} aquesta setmana. El podi i el cos del top es mantenen com la setmana passada, una calma que sovint precedeix un canvi més significatiu al cap d'una o dues setmanes. 🪨",
        "El top {territori_label} no porta notícies de pes aquesta setmana. Les cançons habituals aguanten la posició; els canvis, si en arriben, hauran d'esperar a la propera setmana per a deixar empremta. 🛤️",
        "Rànquing estable al territori {territori_label}. Les peces del podi setmanal queden on eren, sense grans pertorbacions. La inèrcia és la veritable protagonista d'aquesta setmana. 📊",
        "Setmana de manteniment al top {territori_label}: no hi ha debuts forts ni caigudes notables. La continuïtat acostuma a indicar que la setmana anterior va consolidar tendències que avui resisteixen. 🪕",
        "Setmana de calma a la llista {territori_label}, sense canvis bruscos al cim ni al cos del top. Les setmanes així són les que serveixen per a aprofundir en les cançons que duren més d'un cicle. ☀️",
        "Sense grans titulars a la llista {territori_label} aquesta setmana. La continuïtat al podi i al cos del top és el principal valor periodístic; i això sol indicar la salut sòlida de la majoria de presències. 🌿",
        "Continuïtat al top {territori_label} d'aquesta setmana: el podi no es belluga, el cos de la llista tampoc. Aquestes setmanes serveixen per a observar amb calma quines cançons aguanten i quines comencen a flaquejar. 🕰️",
        "La llista {territori_label} no porta notícies de relleu aquesta setmana. La permanència de les cançons habituals al top és la millor manera de saber que estan consolidades més enllà de la novetat. 🌅",
        "Setmana plàcida a la llista {territori_label}: cap esdeveniment ressenyable, només el manteniment de les posicions ja conegudes. La inèrcia parla, i diu que el moment d'una cançó pot durar més enllà de l'estrena. 📆",
        "Setmana de continuïtat al top {territori_label}. La majoria de cançons mantenen la posició; els canvis, modestos, mai trenquen el bloc principal del podi. Una bona setmana per a tornar a les cançons que portem temps escoltant. ✨",
        "Sense recanvis al podi {territori_ordinal}: la setmana al top és més aviat d'inèrcia que de notícia. Les setmanes de manteniment són habitualment l'avantsala dels canvis que vindran. 🌳",
        "Continuïtat reposada a la llista {territori_label}: les cançons habituals continuen sumant setmanes, sense que cap entrada nova trasbalsi el podi. Una setmana més per als clàssics del moment. 🎼",
        "Top {territori_label} en calma aquesta setmana. Cap entrada destacada, cap caiguda notable. Les setmanes plàcides són les que premien la durada per damunt de l'efecte. 🎶",
        "Setmana sense grans títols a la llista {territori_label}: les peces conegudes mantenen el lloc, i la novetat queda fora del podi aquesta vegada. La continuïtat és la manera més silenciosa que té el top d'explicar-se. 🍃",
    ],
}


# ── A13: a song reclaims the #1 after a gap ─────────────────────────
# data: artista, de_artista, canco, territori_label, territori_ordinal,
#       gap_setmanes (int >= 2), gap_setmanes_str ("N setmanes")
A13_TOP1_RETURN = {
    "short": [
        "«{canco}» torna a manar {territori_ordinal} 👑",
        "{artista} recupera el 1r {territori_ordinal} 🔁",
        "Reconquesta del cim {territori_ordinal}: «{canco}» ⤴️",
        "{artista} reclama el cim després de {gap_setmanes_str} 🔝",
        "De nou al 1r {territori_ordinal}: «{canco}» {de_artista} 🎯",
        "«{canco}» recupera el cim {gap_setmanes_str} després 🪃",
    ],
    "medium": [
        "Retorn al cim {territori_ordinal}: «{canco}», {de_artista}, torna al 1r {gap_setmanes_str} després de la seva última vegada al capdamunt. 🔁",
        "{artista} reconquereix el 1r {territori_ordinal} amb «{canco}», que recupera el cim després de {gap_setmanes_str} fora del primer lloc. 👑",
        "«{canco}» torna a manar al top {territori_label}: {gap_setmanes_str} després del seu últim 1r, {de_artista} recupera el cim. ⤴️",
        "Segona volada per a «{canco}» {de_artista}: torna al 1r {territori_ordinal} {gap_setmanes_str} després d'haver-lo deixat. 🪃",
        "El cim {territori_ordinal} torna a ser de «{canco}», {de_artista}, després de {gap_setmanes_str} sense liderar. 🔝",
        "Recuperació al capdamunt {territori_ordinal}: {artista} retorna «{canco}» al 1r {gap_setmanes_str} després. 🎯",
    ],
    "long": [
        "Hi ha cançons que tornen. «{canco}», {de_artista}, recupera el 1r del top {territori_label} {gap_setmanes_str} després de la seva última setmana al capdamunt. Els retorns al cim acostumen a indicar una segona vida d'una peça que no s'havia acomiadat del tot. 🔁",
        "{artista} reconquereix el cim {territori_ordinal}. «{canco}» torna al 1r {gap_setmanes_str} després d'haver-lo cedit, una recuperació que poques cançons aconsegueixen un cop han deixat el primer lloc. 👑",
        "Segona coronació per a «{canco}», {de_artista}: la cançó torna a manar al top {territori_label} {gap_setmanes_str} després del seu darrer 1r. Quan una peça recupera el cim, sol ser senyal que el seu moment encara no s'havia esgotat. ⤴️",
        "El cim {territori_ordinal} torna a dir-se «{canco}». {gap_setmanes_str} després d'abandonar el primer lloc, {artista} el recupera, signant un d'aquests retorns que confirmen que la cançó tenia més recorregut del que semblava. 🪃",
        "Tornada al capdamunt {territori_ordinal} per a «{canco}», {de_artista}. La cançó recupera el 1r {gap_setmanes_str} després de deixar-lo, i els retorns d'aquesta mena solen marcar les peces que aguanten més enllà d'una única embranzida. 🔝",
        "Reconquesta al top {territori_label}: «{canco}», {de_artista}, torna a liderar {gap_setmanes_str} després del seu últim 1r. Recuperar el cim un cop perdut és una gesta rara, i sovint diu més de la cançó que la primera coronació. 🎯",
    ],
}


# ── Public registry ────────────────────────────────────────────────
HERO: dict[str, dict[str, list[str]]] = {
    "a1_outside_to_top1": A1_OUTSIDE_TO_TOP1,
    "a2_streak": A2_STREAK,
    "a3_fall_from_top1": A3_FALL_FROM_TOP1,
    "a4_debut_alt": A4_DEBUT_ALT,
    "a5_artista_multiple": A5_ARTISTA_MULTIPLE,
    "a6_canco_recent": A6_CANCO_RECENT,
    "a7_long_runner": A7_LONG_RUNNER,
    "a8_pujada_forta": A8_PUJADA_FORTA,
    "a9_debut_anywhere": A9_DEBUT_ANYWHERE,
    "a10_artista_first_ever": A10_ARTISTA_FIRST_EVER,
    "a11_top5_drop_generic": A11_TOP5_DROP_GENERIC,
    "a12_artista_emerging": A12_ARTISTA_EMERGING,
    "a13_top1_return": A13_TOP1_RETURN,
    "fallback_no_event": FALLBACK_NO_EVENT,
}
