# Generated by Django 6.0.4 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricaEsdeveniment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                (
                    "clau",
                    models.CharField(
                        db_index=True,
                        help_text="Snake-case event name, e.g. 'pageview', 'registre_complet'.",
                        max_length=80,
                    ),
                ),
                (
                    "dimensio_1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional low-cardinality discriminator. For 'pageview' this is the URL path; for 'utm_landing' the source; for 'social_publicat' the channel.",
                        max_length=80,
                    ),
                ),
                (
                    "dimensio_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Second discriminator slot. Use sparingly.",
                        max_length=80,
                    ),
                ),
                ("comptador", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Esdeveniment agregat",
                "verbose_name_plural": "Esdeveniments agregats",
                "indexes": [
                    models.Index(
                        fields=["clau", "-data"], name="analytics_m_clau_0c7742_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "clau", "dimensio_1", "dimensio_2"),
                        name="metricaesdeveniment_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("clau", models.CharField(db_index=True, max_length=80)),
                ("dimensio_1", models.CharField(blank=True, default="", max_length=80)),
                ("valor_int", models.BigIntegerField(blank=True, null=True)),
                ("valor_float", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Snapshot del pipeline",
                "verbose_name_plural": "Snapshots del pipeline",
                "indexes": [
                    models.Index(
                        fields=["clau", "-data"], name="analytics_m_clau_7ec1db_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "clau", "dimensio_1"),
                        name="metricapipeline_uniq",
                    )
                ],
            },
        ),
    ]
