# Generated by Django 6.0.4 on 2026-05-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("social", "0005_alter_socialpost_platform_alter_socialpost_tipus"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaSocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("platform", models.CharField(db_index=True, max_length=32)),
                ("metric", models.CharField(max_length=40)),
                ("valor", models.BigIntegerField()),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Mètrica de plataforma social",
                "verbose_name_plural": "Mètriques de plataformes socials",
                "indexes": [
                    models.Index(
                        fields=["platform", "metric", "-data"],
                        name="analytics_m_platfor_88d9d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "platform", "metric"),
                        name="metricasocialplatform_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaSocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("replies", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "socialpost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metriques",
                        to="social.socialpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mètrica de publicació social",
                "verbose_name_plural": "Mètriques de publicacions socials",
                "indexes": [
                    models.Index(
                        fields=["data", "socialpost"],
                        name="analytics_m_data_649f02_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("socialpost", "data"), name="metricasocialpost_uniq"
                    )
                ],
            },
        ),
    ]
