# Generated by Django 6.0.4 on 2026-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_metricasocialplatform_metricasocialpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaCWV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("url", models.CharField(max_length=400)),
                ("category", models.CharField(max_length=10)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("lcp_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("inp_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("cls", models.FloatField(blank=True, null=True)),
                ("fcp_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ttfb_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Core Web Vitals per URL",
                "verbose_name_plural": "Core Web Vitals per URL",
                "indexes": [
                    models.Index(
                        fields=["-data", "url", "category"],
                        name="analytics_m_data_00a3e6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "url", "category"), name="metricacwv_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaSEOQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("query", models.CharField(max_length=200)),
                ("page", models.CharField(max_length=400)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0)),
                ("position", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Mètrica SEO per query",
                "verbose_name_plural": "Mètriques SEO per query",
                "indexes": [
                    models.Index(
                        fields=["-data", "-clicks"], name="analytics_m_data_fae3db_idx"
                    ),
                    models.Index(
                        fields=["query", "-data"], name="analytics_m_query_1e09c1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "query", "page"), name="metricaseoquery_uniq"
                    )
                ],
            },
        ),
    ]
