# Generated by Django 6.0.5 on 2026-06-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_metricacwv_metricaseoquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaBingCrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("crawled_pages", models.PositiveIntegerField(default=0)),
                ("in_links", models.PositiveIntegerField(default=0)),
                ("crawl_errors", models.PositiveIntegerField(default=0)),
                ("blocked_by_robots", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mètrica Bing crawl",
                "verbose_name_plural": "Mètriques Bing crawl",
                "indexes": [
                    models.Index(fields=["-data"], name="analytics_m_data_acd6c3_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data",), name="metricabingcrawl_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaBingLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("inbound_links", models.PositiveIntegerField(default=0)),
                ("linking_domains", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mètrica Bing enllaços entrants",
                "verbose_name_plural": "Mètriques Bing enllaços entrants",
                "indexes": [
                    models.Index(fields=["-data"], name="analytics_m_data_13940a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data",), name="metricabinglinks_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaBingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("page", models.CharField(max_length=400)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("avg_click_position", models.FloatField(default=0.0)),
                ("avg_impression_position", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Mètrica Bing per pàgina",
                "verbose_name_plural": "Mètriques Bing per pàgina",
                "indexes": [
                    models.Index(
                        fields=["-data", "-clicks"], name="analytics_m_data_b6d7df_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "page"), name="metricabingpage_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaBingQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("query", models.CharField(max_length=200)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("avg_click_position", models.FloatField(default=0.0)),
                ("avg_impression_position", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Mètrica Bing per query",
                "verbose_name_plural": "Mètriques Bing per query",
                "indexes": [
                    models.Index(
                        fields=["-data", "-clicks"], name="analytics_m_data_538d76_idx"
                    ),
                    models.Index(
                        fields=["query", "-data"], name="analytics_m_query_28ad6e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "query"), name="metricabingquery_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricaBingTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Mètrica Bing tràfic",
                "verbose_name_plural": "Mètriques Bing tràfic",
                "indexes": [
                    models.Index(fields=["-data"], name="analytics_m_data_3a22c1_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data",), name="metricabingtraffic_uniq"
                    )
                ],
            },
        ),
    ]
