"""Album-cover URL resolution for the newsletter (Step 2).

Email clients can't fetch the Deezer CDN reliably (and we want our own
hosting + sizing), so the newsletter serves album art from the local
portades store (`ingesta.portades`, Caddy-served at `/portades/*`). JPG
is the email-safe format (no AVIF/WebP in Outlook/Gmail).

`album_cover_url(deezer_id, mida)` returns the absolute local JPG URL
when the file is on disk, else the placeholder. Existence is a
filesystem stat — never a network call.
"""

from __future__ import annotations

from django.conf import settings

from ingesta.portades import manager

# Generated by `manage.py generar_placeholder_newsletter` (run-once);
# committed PNG: 500×500, ink #0a0a0a, white brand logo centred.
PLACEHOLDER_PATH = "/static/web/img/newsletter/cover_placeholder.png"


def _site() -> str:
    return getattr(settings, "SITE_URL", "https://www.topquaranta.cat").rstrip("/")


def placeholder_url() -> str:
    return f"{_site()}{PLACEHOLDER_PATH}"


def album_cover_url(deezer_id: int | None, mida: int = 500) -> str:
    """Absolute URL of the album cover at `mida` px (250 or 500).

    Local JPG when present on disk, else the placeholder. No network."""
    if not deezer_id:
        return placeholder_url()
    try:
        present = manager.path_for("album", int(deezer_id), mida, "jpg").is_file()
    except Exception:  # noqa: BLE001 — a bad id must never break the send
        present = False
    if present:
        return f"{_site()}/portades/album/{int(deezer_id)}-{mida}.jpg"
    return placeholder_url()
