"""Album-cover URL resolution for the newsletter (Step 2).

Email clients can't fetch the Deezer CDN reliably (and we want our own
hosting + sizing), so the newsletter serves album art from the local
portades store (`ingesta.portades`, Caddy-served at `/portades/*`). JPG
is the email-safe format (no AVIF/WebP in Outlook/Gmail).

`album_cover_url(deezer_id, mida)` returns the absolute local JPG URL
when the file is on disk, else the placeholder. Existence is a
filesystem stat — never a network call.
"""

# Spec: docs/architecture/comptes-newsletter.md

from __future__ import annotations

import logging

from django.conf import settings

from ingesta.portades import manager

logger = logging.getLogger(__name__)

# Generated by `manage.py generar_placeholder_newsletter` (run-once);
# committed PNG: 500×500, ink #0a0a0a, white brand logo centred.
PLACEHOLDER_PATH = "/static/web/img/newsletter/cover_placeholder.png"


def _site() -> str:
    return getattr(settings, "SITE_URL", "https://www.topquaranta.cat").rstrip("/")


def placeholder_url() -> str:
    return f"{_site()}{PLACEHOLDER_PATH}"


def ensure_cover_downloaded(deezer_id: int | None, source_url: str | None) -> bool:
    """Guarantee the album cover JPGs the newsletter needs are on disk.

    The newsletter serves art from the local portades store and falls
    back to the brand logo when the file is absent. The nightly
    `descarregar_portades` cron may not have generated a cover for an
    album that only just entered the top, which is why a real cover
    (e.g. Rosalía) showed up as the logo (auditoria 2026-06-07, informe
    2c). This makes the policy a guarantee: before composing the send we
    pull any missing cover synchronously, reusing the SAME portades
    pipeline as the cron (`manager.download_and_convert`) — no
    hotlinking to Deezer inside the email.

    Best-effort and idempotent: returns True if the cover is present
    afterwards. Never raises — a download hiccup must not break the send
    (the row simply falls back to the logo, as before). A genuinely
    cover-less album (no `source_url`) returns False and stays on the
    logo, which is correct."""
    if not deezer_id:
        return False
    try:
        did = int(deezer_id)
    except (TypeError, ValueError):
        return False
    # The newsletter requests one JPG per configured variant (250/500).
    needed = [
        manager.path_for("album", did, mida, "jpg")
        for mida in settings.PORTADES_VARIANTS
    ]
    try:
        if all(p.is_file() for p in needed):
            return True
    except Exception:  # noqa: BLE001
        return False
    if not source_url:
        return False
    try:
        ok = manager.download_and_convert("album", did, source_url)
        if not ok:
            logger.warning(
                "newsletter: cover download failed for album deezer_id=%s", did
            )
        return ok
    except Exception:  # noqa: BLE001
        logger.warning("newsletter: cover download raised for album deezer_id=%s", did)
        return False


def album_cover_url(deezer_id: int | None, mida: int = 500) -> str:
    """Absolute URL of the album cover at `mida` px (250 or 500).

    Local JPG when present on disk, else the placeholder. No network."""
    if not deezer_id:
        return placeholder_url()
    try:
        present = manager.path_for("album", int(deezer_id), mida, "jpg").is_file()
    except Exception:  # noqa: BLE001 — a bad id must never break the send
        present = False
    if present:
        return f"{_site()}/portades/album/{int(deezer_id)}-{mida}.jpg"
    return placeholder_url()
