import dj_database_url
from decouple import Csv, config

from .base import *  # noqa: F401,F403

DEBUG = False
SECRET_KEY = config("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

DATABASES = {
    # P6: persistent connections. Without pooling, every request opens a
    # fresh psycopg2 connection (~5ms on localhost). `conn_max_age=600`
    # keeps the connection alive for up to 10 minutes per worker, and
    # `conn_health_checks=True` pings before reuse so a recycled-by-the-
    # server connection doesn't raise InterfaceError mid-request.
    "default": dj_database_url.config(
        default=config("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    ),
}

# Security
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Last.fm
LASTFM_API_KEY = config("LASTFM_API_KEY")
LASTFM_API_SECRET = config("LASTFM_API_SECRET", default="")

# Newsletter cloud-routine bearer token (2026-06-07). Generated by an
# operator and set in the server `.env`; empty default keeps token auth
# disabled until it is configured.
NEWSLETTER_ROUTINE_TOKEN = config("NEWSLETTER_ROUTINE_TOKEN", default="")

# Spotify. The client-credentials ingesta flow has been blocked since
# 2024, but playlist management via user OAuth still works fine (no
# Premium required). Used by the `actualitzar_playlists_spotify` cron
# to sync the public top-40 + novetats playlists.
SPOTIFY_CLIENT_ID = config("SPOTIFY_CLIENT_ID", default="")
SPOTIFY_CLIENT_SECRET = config("SPOTIFY_CLIENT_SECRET", default="")
# OAuth callback URL. The React SPA serves a tiny page at
# /spotify/callback that displays the `code` query param so the admin
# can copy it back into the `autoritzar_spotify` command. The URL
# must be registered exactly in the Spotify app dashboard's
# "Redirect URIs" list.
SPOTIFY_REDIRECT_URI = config(
    "SPOTIFY_REDIRECT_URI",
    default="https://www.topquaranta.cat/spotify/callback",
)

# SMTP via Brevo (formerly Sendinblue) as transactional + newsletter
# relay. Login + Master Password come from .env. Sender domain
# (topquaranta.cat) is verified at Brevo with DKIM via the two
# `brevoN._domainkey` CNAMEs on CDMON. Falls back to a file-based
# backend if EMAIL_HOST_PASSWORD is empty so dev / a fresh clone
# doesn't raise on `mail_admins()`.
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = config("EMAIL_HOST", default="smtp-relay.brevo.com")
    EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
    EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
    EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
    EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="noreply@topquaranta.cat")
    # Brevo's SMTP login (a97491001@smtp-brevo.com) is NOT the
    # sender — that's noreply@topquaranta.cat. Keep them apart.
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@topquaranta.cat")
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    EMAIL_TIMEOUT = 20
else:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = "/var/log/topquaranta/admin_mail"

# ── Sprint I: Instagram credentials ─────────────────────────────────────
# Empty token forces DRY_RUN in `social.instagram_client`.
INSTAGRAM_ACCESS_TOKEN = config("INSTAGRAM_ACCESS_TOKEN", default="")
INSTAGRAM_USER_ID = config("INSTAGRAM_USER_ID", default="")
INSTAGRAM_TOKEN_EXPIRES_AT = config("INSTAGRAM_TOKEN_EXPIRES_AT", default="")

# ── Sprint S Bloc D: SEO monitoring (GSC + PSI) ─────────────────────────
# Service Account JSON for GSC search-analytics. Path-based so we don't
# inline the private key into env. Empty path = feature disabled
# (cron writes a warning + exits gracefully).
GSC_SERVICE_ACCOUNT_FILE = config("GSC_SERVICE_ACCOUNT_FILE", default="")
GSC_SITE_URL = config("GSC_SITE_URL", default="sc-domain:topquaranta.cat")
PSI_API_KEY = config("PSI_API_KEY", default="")
# OAuth fallback (workaround for the SA-on-sc-domain GSC UI bug):
# mint a refresh_token via the OAuth Playground once and pin here.
GSC_OAUTH_CLIENT_ID = config("GSC_OAUTH_CLIENT_ID", default="")
GSC_OAUTH_CLIENT_SECRET = config("GSC_OAUTH_CLIENT_SECRET", default="")
GSC_OAUTH_REFRESH_TOKEN = config("GSC_OAUTH_REFRESH_TOKEN", default="")
