# Generated by Django 6.0.5 on 2026-06-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingProsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("territori", "Territori"),
                            ("genere", "Gènere"),
                            ("decada", "Dècada"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("clau", models.CharField(max_length=80)),
                ("prosa", models.TextField(blank=True, default="")),
                ("font", models.CharField(blank=True, default="", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "clau"), name="uniq_landingprosa_kind_clau"
                    )
                ],
            },
        ),
    ]
