# Generated by Django 6.0.5 on 2026-06-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingprosa",
            name="kind",
            field=models.CharField(
                choices=[
                    ("territori", "Territori"),
                    ("genere", "Gènere"),
                    ("decada", "Dècada"),
                    ("top", "Top"),
                    ("mapa", "Mapa"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
