"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db.models import (
    Count,
)
from rest_framework.permissions import BasePermission
from rest_framework.request import Request

from music.models import (
    Artista,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()


# Accent + apostrophe insensitive search helpers — implementation lives
# in `web/api/search_utils.py` so the public endpoints can reuse it.


class IsStaff(BasePermission):
    """Authenticated + is_staff + OTP-verified session."""

    message = "Staff access required."

    def has_permission(self, request, view):  # noqa: D401 — DRF signature
        user = request.user
        if not (user and user.is_authenticated and user.is_staff):
            return False
        # django-otp attaches is_verified(); missing attr means no OTP middleware.
        is_verified = getattr(user, "is_verified", None)
        return True if is_verified is None else bool(is_verified())


def noms_amb_homonims() -> set[str]:
    """Set of `Artista.nom_normalitzat` values shared by >1 artista — the
    homonym keys (same name modulo accents + punctuation). One GROUP BY;
    callers flag a row with `a.nom_normalitzat in this_set`. Empty key is
    never a homonym (names that are all punctuation)."""
    return set(
        Artista.objects.exclude(nom_normalitzat="")
        .values("nom_normalitzat")
        .annotate(_n=Count("id"))
        .filter(_n__gt=1)
        .values_list("nom_normalitzat", flat=True)
    )


def _paginate(qs, request: Request, default_per_page: int = 50):
    """Staff variant of :func:`web.api.utils.paginate` with a 200-cap.

    Kept as a thin wrapper because staff endpoints surface high-density
    tables where 100 rows can feel cramped; bumping the cap to 200
    lets power users self-serve without a code change. The wrapper
    preserves the existing call signature (positional default) so
    callers don't churn.
    """
    from web.api.utils import paginate

    return paginate(qs, request, default=default_per_page, cap=200)
