"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()


# Accent + apostrophe insensitive search helpers — implementation lives
# in `web/api/search_utils.py` so the public endpoints can reuse it.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field


class IsStaff(BasePermission):
    """Authenticated + is_staff + OTP-verified session."""

    message = "Staff access required."

    def has_permission(self, request, view):  # noqa: D401 — DRF signature
        user = request.user
        if not (user and user.is_authenticated and user.is_staff):
            return False
        # django-otp attaches is_verified(); missing attr means no OTP middleware.
        is_verified = getattr(user, "is_verified", None)
        return True if is_verified is None else bool(is_verified())


def noms_amb_homonims() -> set[str]:
    """Set of `Artista.nom_normalitzat` values shared by >1 artista — the
    homonym keys (same name modulo accents + punctuation). One GROUP BY;
    callers flag a row with `a.nom_normalitzat in this_set`. Empty key is
    never a homonym (names that are all punctuation)."""
    return set(
        Artista.objects.exclude(nom_normalitzat="")
        .values("nom_normalitzat")
        .annotate(_n=Count("id"))
        .filter(_n__gt=1)
        .values_list("nom_normalitzat", flat=True)
    )


def _paginate(qs, request: Request, default_per_page: int = 50):
    """Staff variant of :func:`web.api.utils.paginate` with a 200-cap.

    Kept as a thin wrapper because staff endpoints surface high-density
    tables where 100 rows can feel cramped; bumping the cap to 200
    lets power users self-serve without a code change. The wrapper
    preserves the existing call signature (positional default) so
    callers don't churn.
    """
    from web.api.utils import paginate

    return paginate(qs, request, default=default_per_page, cap=200)
