"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()


# Accent + apostrophe insensitive search helpers — implementation lives
# in `web/api/search_utils.py` so the public endpoints can reuse it.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field


class IsStaff(BasePermission):
    """Authenticated + is_staff + OTP-verified session."""

    message = "Staff access required."

    def has_permission(self, request, view):  # noqa: D401 — DRF signature
        user = request.user
        if not (user and user.is_authenticated and user.is_staff):
            return False
        # django-otp attaches is_verified(); missing attr means no OTP middleware.
        is_verified = getattr(user, "is_verified", None)
        return True if is_verified is None else bool(is_verified())


def _paginate(qs, request: Request, default_per_page: int = 50):
    """Return (page_obj, metadata dict) tuple for a queryset."""
    try:
        per_page = min(int(request.GET.get("per_page") or default_per_page), 200)
    except ValueError:
        per_page = default_per_page
    paginator = Paginator(qs, per_page)
    page = paginator.get_page(request.GET.get("page") or 1)
    return page, {
        "page": page.number,
        "num_pages": paginator.num_pages,
        "total": paginator.count,
        "per_page": per_page,
        "has_next": page.has_next(),
        "has_previous": page.has_previous(),
    }
