"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Albums — list + simple edit
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def albums_list(request: Request) -> Response:
    """Album directory for staff. Filters: q, tipus, descartat, artista_pk."""
    qs = Album.objects.select_related("artista").annotate(
        n_cancons=Count("cancons"),
        n_verificades=Count("cancons", filter=Q(cancons__verificada=True)),
    )
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(
            _alb_norm=_unaccent_field("nom"),
            _art_norm=_unaccent_field("artista__nom"),
        ).filter(
            Q(_alb_norm__contains=_normalize_search_term(cerca))
            | Q(_art_norm__contains=_normalize_search_term(cerca))
        )
    tipus = request.GET.get("tipus", "")
    if tipus in {"album", "single", "ep"}:
        qs = qs.filter(tipus=tipus)
    descartat = request.GET.get("descartat", "")
    if descartat == "1":
        qs = qs.filter(descartat=True)
    elif descartat == "0":
        qs = qs.filter(descartat=False)
    # MB confirmation filter — symmetric to the cançons one.
    mb = request.GET.get("mb", "")
    if mb == "confirmat":
        qs = qs.filter(mbrainz_confirmed=True)
    elif mb == "no_confirmat":
        qs = qs.filter(mbrainz_confirmed=False)
    elif mb == "desconegut":
        qs = qs.filter(mbrainz_confirmed__isnull=True)
    artista_pk = request.GET.get("artista_pk", "")
    if artista_pk:
        try:
            qs = qs.filter(artista_id=int(artista_pk))
        except ValueError:
            pass
    qs = qs.order_by("-data_llancament", "nom")
    page, meta = _paginate(qs, request)
    return Response(
        {
            "results": [
                {
                    "pk": a.pk,
                    "nom": a.nom,
                    "slug": a.slug,
                    "tipus": a.tipus,
                    "data_llancament": (
                        a.data_llancament.isoformat() if a.data_llancament else None
                    ),
                    "imatge_url": a.imatge_url or "",
                    "deezer_id": a.deezer_id,
                    "descartat": a.descartat,
                    "n_cancons": a.n_cancons,
                    "n_verificades": a.n_verificades,
                    "artista": {
                        "pk": a.artista_id,
                        "nom": a.artista.nom if a.artista else "",
                        "slug": a.artista.slug if a.artista else "",
                    },
                }
                for a in page.object_list
            ],
            **meta,
        }
    )


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def album_detail(request: Request, pk: int) -> Response:
    album = get_object_or_404(Album.objects.select_related("artista"), pk=pk)
    if request.method == "PATCH":
        data = request.data or {}
        was_descartat = album.descartat
        if "nom" in data:
            album.nom = (data.get("nom") or "").strip()
        if "data_llancament" in data:
            raw = (data.get("data_llancament") or "").strip()
            # Parse to a real date object. Assigning the raw string works
            # for the SQL UPDATE (Django's DateField casts on write) but
            # leaves the in-memory attribute as a str, and the response
            # serializer below calls .isoformat() on it → 500. parse_date
            # returns None on empty or on invalid input.
            album.data_llancament = parse_date(raw) if raw else None
        if "tipus" in data:
            album.tipus = (data.get("tipus") or "").strip()
        if "deezer_id" in data:
            raw = str(data.get("deezer_id") or "").strip()
            album.deezer_id = int(raw) if raw else None
        if "imatge_url" in data:
            album.imatge_url = (data.get("imatge_url") or "").strip()
        if "descartat" in data:
            album.descartat = bool(data["descartat"])

        # Reassign to a different artist. `cascade_cancons` (default True)
        # also re-points every Canco whose current artista_id matches the
        # album's old artista_id — the common case after a mis-split. Set
        # to False to leave the tracks' attributions intact (rare, but
        # useful when an album mixes tracks from several artists).
        if "artista_pk" in data:
            raw = data.get("artista_pk")
            if raw in (None, ""):
                return Response({"error": "L'artista és obligatori."}, status=400)
            try:
                new_artista = Artista.objects.get(pk=int(raw))
            except (ValueError, Artista.DoesNotExist):
                return Response({"error": "Artista no trobat."}, status=404)
            if album.artista_id != new_artista.pk:
                old_id = album.artista_id
                old_nom = album.artista.nom if album.artista else ""
                album.artista = new_artista
                cancons_changed = 0
                if data.get("cascade_cancons", True):
                    cancons_changed = Canco.objects.filter(
                        album=album, artista_id=old_id
                    ).update(artista=new_artista)
                log_staff_action(
                    request,
                    "album_edit",
                    target=album,
                    field="artista",
                    old_artista=old_nom,
                    new_artista=new_artista.nom,
                    cancons_reassignades=cancons_changed,
                )
        album.save()
        log_staff_action(request, "album_edit", target=album)
        if album.descartat and not was_descartat:
            log_staff_action(request, "album_descartar", target=album)
    return Response(
        {
            "pk": album.pk,
            "nom": album.nom,
            "slug": album.slug,
            "data_llancament": (
                album.data_llancament.isoformat() if album.data_llancament else None
            ),
            "tipus": album.tipus or "",
            "deezer_id": album.deezer_id,
            "imatge_url": album.imatge_url or "",
            "descartat": album.descartat,
            "mb_release_group_id": album.mb_release_group_id or "",
            "mb_type_secondary": album.mb_type_secondary or "",
            "mb_status": album.mb_status or "",
            "mbrainz_confirmed": album.mbrainz_confirmed,
            "artista": {
                "pk": album.artista_id,
                "nom": album.artista.nom if album.artista else "",
                "slug": album.artista.slug if album.artista else "",
            },
            "cancons": [
                {
                    "pk": c.pk,
                    "nom": c.nom,
                    "slug": c.slug,
                    "verificada": c.verificada,
                }
                for c in album.cancons.order_by("nom").only(
                    "pk", "nom", "slug", "verificada"
                )
            ],
            # Collaborators per canço, so the album page can display
            # them inline next to the track name. Separate query to
            # avoid N+1 — one prefetched fetch over artistes_col M2M.
            "cancons_col": {
                c.pk: [
                    {"pk": a.pk, "nom": a.nom, "slug": a.slug}
                    for a in c.artistes_col.all()
                ]
                for c in album.cancons.prefetch_related("artistes_col").only("pk")
            },
        }
    )
