"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime
import logging
import re

from django.contrib.auth import get_user_model
from django.db import IntegrityError, transaction
from django.db.models import (
    Count,
    F,
    IntegerField,
    OuterRef,
    Q,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import UserArtista
from ingesta.clients.lastfm import to_noredirect_url
from music.audit import log_staff_action
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

logger = logging.getLogger(__name__)
Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate, noms_amb_homonims
from web.api.staff.estat import _homonym_suspects_qs
from web.api.staff.pendents import _artista_card

# ═════════════════════════════════════════════════════════════════════════
# Artistes — approved artists management
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def artistes_list(request: Request) -> Response:
    qs = Artista.objects.prefetch_related(
        "territoris", "localitats__municipi", "deezer_ids", "lastfm_aliases"
    )
    aprovat = request.GET.get("aprovat", "1")
    if aprovat == "1":
        qs = qs.filter(aprovat=True)
    elif aprovat == "0":
        qs = qs.filter(aprovat=False)
    # Descartat is the terminal state (aprovat=False AND pendent_review=False;
    # kept only for FK integrity). It must never flood the list when the
    # "actius" filter is lifted to hunt duplicates — staff needs pendents +
    # approved, not the ~10k descartats. Exclude it by default; reachable
    # only via the explicit opt-in `inclou_descartats=1`. Does NOT touch
    # pendents (pendent_review=True) nor approved.
    if request.GET.get("inclou_descartats") != "1":
        qs = qs.exclude(aprovat=False, pendent_review=False)
    deezer = request.GET.get("deezer", "")
    if deezer == "si":
        qs = qs.filter(deezer_ids__isnull=False)
    elif deezer == "no":
        qs = qs.filter(deezer_ids__isnull=True)
    territori = request.GET.get("territori", "")
    if territori:
        qs = qs.filter(territoris__codi=territori)
    # MusicBrainz filters — surface artists that still need manual MBID
    # resolution, or those flagged as dissolved. The two new filters
    # `provat_sense_mbid` / `mai_provat` split the legacy `sense_mbid`
    # bucket so staff can act on the right subset.
    mb = request.GET.get("mb", "")
    if mb == "sense_mbid":
        qs = qs.filter(Q(musicbrainz_id__isnull=True) | Q(musicbrainz_id=""))
    elif mb == "amb_mbid":
        qs = qs.exclude(musicbrainz_id__isnull=True).exclude(musicbrainz_id="")
    elif mb == "dissolt":
        qs = qs.filter(mb_end_date__isnull=False)
    elif mb == "no_sincronitzat" or mb == "mai_provat":
        qs = qs.filter(mb_last_sync__isnull=True)
    elif mb == "provat_sense_mbid":
        qs = qs.filter(Q(musicbrainz_id__isnull=True) | Q(musicbrainz_id="")).filter(
            mb_last_sync__isnull=False
        )
    elif mb == "bloquejat":
        qs = qs.filter(mb_auto_match_disabled=True)

    # Homonym-collision suspects: at least one Cançó rejected as
    # `artista_incorrecte` AND at least one still active. See
    # `_homonym_suspects_qs` for the rationale.
    if request.GET.get("homonim_sospitos") == "1":
        qs = qs.filter(pk__in=_homonym_suspects_qs().values("pk"))

    # Per-social filter: handy when staff needs to chase down missing
    # social handles for outreach (Instagram is the most relevant for
    # publication, hence first-class; the rest can be added the same way).
    instagram = request.GET.get("instagram", "")
    if instagram == "no":
        qs = qs.filter(Q(instagram_url="") | Q(instagram_url__isnull=True))
    elif instagram == "si":
        qs = qs.exclude(instagram_url="").exclude(instagram_url__isnull=True)
    elif instagram == "pendent":
        # Third state, mirroring `youtube=pendent`: no URL AND nobody has
        # looked. An artist reviewed as genuinely having no Instagram is
        # DONE, not outstanding. `instagram=no` keeps its old meaning
        # (simply has no URL) so existing callers don't shift under them.
        qs = qs.filter(
            Q(instagram_url="") | Q(instagram_url__isnull=True),
            instagram_revisat=False,
        )
    elif instagram == "rebutjat":
        # Handles Meta refused while publishing. They HAVE a URL, so they
        # never show up in the `instagram=no` queue — a separate hole.
        qs = qs.filter(instagram_rebutjat_at__isnull=False)

    # YouTube official-channel workflow (2026-08). Three states, so the
    # filter is `pendent` (nobody has looked) rather than "empty": an
    # artist reviewed and confirmed to have no own channel is DONE, not
    # outstanding, and must not come back in the queue forever.
    youtube = request.GET.get("youtube", "")
    if youtube == "pendent":
        qs = qs.filter(youtube_canal_revisat=False)
    elif youtube == "revisat":
        qs = qs.filter(youtube_canal_revisat=True)

    # "Al top" workflow (Fase 2 D2): artistes appearing in the latest
    # weekly PPCC top, for the social tagging flow. `te_gestor_email` in
    # the payload tells staff whether the artist has a reachable
    # verified-manager email (the D1 alert audience).
    al_top = request.GET.get("al_top", "")
    want_gestor_email = al_top == "1" or request.GET.get("include_gestor_email") == "1"
    if al_top == "1":
        from ranking.models import TopSetmanal as _TS

        latest_setmana = (
            _TS.objects.filter(territori="PPCC")
            .order_by("-setmana")
            .values_list("setmana", flat=True)
            .first()
        )
        if latest_setmana is None:
            qs = qs.none()
        else:
            qs = qs.filter(
                cancons__rankings__territori="PPCC",
                cancons__rankings__setmana=latest_setmana,
            )
    if want_gestor_email:
        from django.db.models import Exists

        from comptes.models import UserArtista

        qs = qs.annotate(
            _te_gestor_email=Exists(
                UserArtista.objects.filter(
                    artista=OuterRef("pk"),
                    verificat=True,
                    estat="aprovat",
                    usuari__is_active=True,
                ).exclude(usuari__email="")
            )
        )

    # Last.fm alias state — surfaces the 35 candidates the detector
    # produced (or any future runs). `pendents` = ≥1 candidate
    # awaiting staff review; `confirmats` = ≥1 alias actively summing
    # into the signal; `rebutjats` = ≥1 candidate explicitly rejected
    # (kept in DB so the detector doesn't re-propose homonyms).
    lastfm_alias = request.GET.get("lastfm_alias", "")
    if lastfm_alias == "pendents":
        qs = qs.filter(
            lastfm_aliases__confirmat=False,
            lastfm_aliases__rebutjat=False,
        )
    elif lastfm_alias == "confirmats":
        qs = qs.filter(lastfm_aliases__confirmat=True)
    elif lastfm_alias == "rebutjats":
        qs = qs.filter(lastfm_aliases__rebutjat=True)

    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(_nom_norm=_unaccent_field("nom")).filter(
            _nom_norm__contains=_normalize_search_term(cerca)
        )

    # Sort: default is alphabetical, but the publication workflow
    # benefits from "artistes amb més presència històrica al top" so
    # we annotate distinct charted Cançons (main artist) and sort by
    # that. TopSetmanal stores one row per (canço, territori,
    # setmana) — distinct on the canço so a track appearing 10 weeks
    # in the CAT top doesn't outweigh a track in 9 distinct top tracks.
    sort_raw = (request.GET.get("sort") or "").strip()
    # Opt-in `n_top` annotation: distinct count of every TopSetmanal
    # row across the artist's cançons, including BOTH the cançons
    # where this artist is principal AND those where they appear as
    # a collaborator (FASE 2 of the Sprint Triple, 2026-05-23).
    #
    # The earlier annotation counted only `cancons__rankings`
    # (principal-only) which under-weighted artists that collaborate
    # heavily but rarely lead. Tagging them on Instagram is just as
    # valuable; the queue should rank them accordingly.
    #
    # Implementation: subquery per path with COUNT(DISTINCT
    # TopSetmanal.id) to avoid the Cartesian inflation that two
    # LEFT JOIN annotations would produce. Gated by `?include_n_top=1`
    # so the general list endpoint stays cheap.
    include_n_top = request.GET.get("include_n_top") == "1"
    if include_n_top or sort_raw == "-n_top":
        from django.db.models import Subquery
        from django.db.models.functions import Coalesce

        from ranking.models import TopSetmanal

        principal_n = Subquery(
            TopSetmanal.objects.filter(canco__artista=OuterRef("pk"))
            .order_by()
            .values("canco__artista")
            .annotate(n=Count("id", distinct=True))
            .values("n")[:1],
            output_field=IntegerField(),
        )
        collab_n = Subquery(
            TopSetmanal.objects.filter(canco__artistes_col=OuterRef("pk"))
            .order_by()
            .values("canco__artistes_col")
            .annotate(n=Count("id", distinct=True))
            .values("n")[:1],
            output_field=IntegerField(),
        )
        # `Coalesce(..., 0)` so the Subquery returning NULL (no rows)
        # contributes 0 to the sum rather than poisoning it.
        qs = qs.annotate(
            n_top_principal=Coalesce(principal_n, 0),
            n_top_collab=Coalesce(collab_n, 0),
        ).annotate(n_top=F("n_top_principal") + F("n_top_collab"))

        # Live approved cançons (verificada=True, activa=True) where the
        # artist takes part — as principal (FK `artista`) OR as a
        # collaborator (M2M `artistes_col`). Same distinct-Subquery shape
        # as `n_top` above: each path is a scalar subquery so the two
        # never LEFT JOIN together and can't Cartesian-inflate. The two
        # paths are disjoint PER cançó — the D5 signal
        # (`music/signals.py`) forbids an artist from being a
        # collaborator on their own track — so summing them double-counts
        # nothing; no overlap correction is needed (identical reasoning
        # to `n_top`). Used as the second sort key so novetats artists
        # (0 tops, but with live songs) rise to the top of their block.
        viva = {"verificada": True, "activa": True}
        vives_principal = Subquery(
            Canco.objects.filter(artista=OuterRef("pk"), **viva)
            .order_by()
            .values("artista")
            .annotate(n=Count("pk", distinct=True))
            .values("n")[:1],
            output_field=IntegerField(),
        )
        vives_collab = Subquery(
            Canco.objects.filter(artistes_col=OuterRef("pk"), **viva)
            .order_by()
            .values("artistes_col")
            .annotate(n=Count("pk", distinct=True))
            .values("n")[:1],
            output_field=IntegerField(),
        )
        qs = qs.annotate(
            n_cancons_vives=Coalesce(vives_principal, 0) + Coalesce(vives_collab, 0)
        )

    if sort_raw == "cancons_tops_desc":
        qs = (
            qs.annotate(
                n_cancons_tops=Count(
                    "cancons__rankings",
                    filter=Q(cancons__rankings__posicio__lte=40),
                    distinct=True,
                )
            )
            .distinct()
            .order_by("-n_cancons_tops", Lower("nom"))
        )
    elif sort_raw == "-n_top":
        # Tops first, then live-songs as the tiebreaker (novetats artists
        # with 0 tops but active songs surface above the 0-top silence),
        # then alphabetical. `n_cancons_vives` is guaranteed annotated
        # here (this branch is inside the annotation gate above).
        qs = qs.distinct().order_by("-n_top", "-n_cancons_vives", Lower("nom"))
    else:
        qs = qs.distinct().order_by(Lower("nom"))

    page, meta = _paginate(qs, request)
    homset = noms_amb_homonims()
    cards = []
    for a in page.object_list:
        card = _artista_card(a, homset)
        if want_gestor_email:
            card["te_gestor_email"] = bool(getattr(a, "_te_gestor_email", False))
        cards.append(card)
    return Response({"results": cards, **meta})


@api_view(["GET"])
@permission_classes([IsStaff])
def artistes_search(request: Request) -> Response:
    """Light-weight lookup for the reassignment typeaheads.

    Returns up to 10 candidate artists (aprovats=True by default, but
    we surface pending/descartats too when the search is explicit, so
    staff can pick a pending artist to land a mis-assigned track on).
    """
    q = (request.GET.get("q") or "").strip()
    if len(q) < 2:
        return Response({"results": []})
    qs = (
        Artista.objects.annotate(_nom_norm=_unaccent_field("nom"))
        .filter(_nom_norm__contains=_normalize_search_term(q))
        .order_by("-aprovat", "nom")[:10]
    )
    return Response(
        {
            "results": [
                {
                    "pk": a.pk,
                    "nom": a.nom,
                    "slug": a.slug,
                    "aprovat": a.aprovat,
                    "pendent_review": a.pendent_review,
                }
                for a in qs
            ]
        }
    )


_CANAL_ID = re.compile(r"^UC[\w-]{20,30}$")
_CANAL_URL = re.compile(r"youtube\.com/channel/(UC[\w-]{20,30})", re.I)
_CANAL_HANDLE = re.compile(r"(?:youtube\.com/)?@([\w.-]+)", re.I)


def _resol_canal_youtube(brut: str) -> tuple[str, str]:
    """Accept an id, a /channel/ URL or a handle; return `(id, error)`.

    Resolving here rather than in the browser keeps the API key server-
    side, and it is where a bad value can still be refused: better a 400
    the operator reads than a channel id that silently points nowhere.
    """
    from ingesta.clients import youtube as yt

    brut = (brut or "").strip()
    kwargs: dict[str, str] = {}
    if _CANAL_ID.match(brut):
        kwargs = {"channel_id": brut}
    elif _CANAL_URL.search(brut):
        kwargs = {"channel_id": _CANAL_URL.search(brut).group(1)}
    elif _CANAL_HANDLE.search(brut):
        kwargs = {"handle": _CANAL_HANDLE.search(brut).group(1)}
    else:
        return "", (
            "No reconec això com un canal. Enganxa l'enllaç del canal "
            "(youtube.com/@nom o youtube.com/channel/UC…) o l'id UC…"
        )

    try:
        info = yt.channel_info(**kwargs)
    except yt.QuotaExhausted:
        return "", "Quota de YouTube exhaurida; torna-ho a provar demà."
    except Exception:  # pragma: no cover - transport
        logger.exception("resolent el canal de YouTube %r", brut)
        return "", "No s'ha pogut consultar YouTube. Torna-ho a provar."
    if not info:
        return "", f"YouTube no coneix {brut}."

    # Refuse the auto-generated channel. It is the OTHER lane and the
    # discovery cron already finds it on its own; pasting it here would
    # make us count the same Art Track twice and lose the videoclip lane
    # entirely. Easy mistake: searching an artist surfaces both, and the
    # Topic one often ranks first.
    if yt.topic_suffix_name(info["title"]) is not None:
        return "", (
            f"«{info['title']}» és el canal automàtic de YouTube Music, i "
            "eixe ja el trobem sols. Ací va el canal propi de l'artista, "
            "el dels videoclips."
        )
    return info["id"], ""


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_crear(request: Request) -> Response:
    data = request.data or {}
    nom = (data.get("nom") or "").strip()
    if not nom:
        return Response({"error": "El nom és obligatori."}, status=400)
    lastfm_nom = (data.get("lastfm_nom") or "").strip() or nom
    deezer_raw = (data.get("deezer_id") or "").strip() if data.get("deezer_id") else ""
    deezer_id = None
    if deezer_raw:
        try:
            deezer_id = int(deezer_raw)
        except ValueError:
            return Response(
                {"error": "Deezer ID ha de ser un nombre enter."}, status=400
            )
    with transaction.atomic():
        artista = Artista.objects.create(
            nom=nom,
            lastfm_nom=lastfm_nom,
            aprovat=True,
            auto_descobert=False,
            font_descoberta="manual",
        )
        if deezer_id is not None:
            try:
                ArtistaDeezer.objects.create(
                    artista=artista, deezer_id=deezer_id, principal=True
                )
            except IntegrityError:
                return Response(
                    {"error": f"Deezer ID {deezer_id} ja pertany a un altre artista."},
                    status=409,
                )
        log_staff_action(request, "artista_crear", target=artista, deezer_id=deezer_id)
    return Response({"ok": True, "pk": artista.pk, "slug": artista.slug})


def _homonims_payload(artista: Artista) -> list[dict]:
    """Other artistes sharing this one's homonym key (same name modulo accents
    + punctuation). Drives the staff heads-up marker. Each entry carries enough
    to disambiguate by eye: estat, location, Deezer IDs, verified-song count."""
    out = []
    for h in (
        artista.homonims()
        .prefetch_related("localitats__municipi", "deezer_ids")
        .order_by("-aprovat", "nom")
    ):
        locs = []
        for loc in h.localitats.all():
            if loc.municipi_id:
                locs.append(loc.municipi.nom)
            elif loc.localitat_manual:
                locs.append(loc.localitat_manual)
        out.append(
            {
                "pk": h.pk,
                "nom": h.nom,
                "slug": h.slug,
                "aprovat": h.aprovat,
                "localitats": locs[:4],
                "deezer_ids": list(h.deezer_ids.values_list("deezer_id", flat=True)),
                "n_cancons_verificades": Canco.objects.filter(
                    artista=h, verificada=True, activa=True
                ).count(),
            }
        )
    return out


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def artista_detail(request: Request, pk: int) -> Response:
    artista = get_object_or_404(Artista, pk=pk)
    if request.method == "PATCH":
        data = request.data or {}
        # A YouTube handle is what a human can actually copy: the site
        # stopped showing the `UC…` id anywhere, so asking for it made the
        # staff queue unusable (caught 2026-08-12 filling in Malifeta).
        # `channels.list?forHandle=` resolves it for ONE quota unit.
        if data.get("youtube_canal_oficial"):
            resolt, err = _resol_canal_youtube(data["youtube_canal_oficial"])
            if err:
                return Response({"error": err}, status=400)
            data = {**data, "youtube_canal_oficial": resolt}
        simple_fields = [
            "nom",
            "lastfm_nom",
            "genere",
            "genere_canonical",
            "percentatge_femeni",
            "musicbrainz_id",
            "youtube_canal_oficial",
        ] + [f for f, _ in Artista.SOCIAL_LINK_FIELDS]
        # Whole PATCH is one transaction: a rejected approval (no Deezer)
        # or a Deezer collision must NOT leave half-written localitats /
        # deezer rows. `transaction.set_rollback(True)` before an early
        # return undoes the in-flight writes (a bare `return` inside an
        # atomic block would otherwise commit them).
        with transaction.atomic():
            # Sprint S Bloc D pt 3: when staff sets `genere_canonical`
            # manually, lock the field so the nightly inferer doesn't
            # overwrite it. Same for `percentatge_femeni`. Idempotent —
            # sending the same value re-locks (no-op).
            if "genere_canonical" in data:
                artista.genere_locked = bool(
                    (data.get("genere_canonical") or "").strip()
                )
            if "genere_locked" in data:
                artista.genere_locked = bool(data["genere_locked"])
            old_mbid = artista.musicbrainz_id
            for f in simple_fields:
                if f in data:
                    setattr(artista, f, (data.get(f) or "").strip())
            # Editing the handle is the fix for a Meta rejection, so the
            # flag clears itself: leaving it set would keep an already-
            # corrected artist in the "broken handle" list forever.
            if "instagram_url" in data:
                artista.instagram_rebutjat_at = None
                artista.instagram_rebutjat_url = ""
                # Filling the URL IS the review, so the operator doesn't
                # have to say so twice.
                if (data.get("instagram_url") or "").strip():
                    artista.instagram_revisat = True
            # Boolean, so it can't ride the `.strip()` loop above.
            if "youtube_canal_revisat" in data:
                artista.youtube_canal_revisat = bool(data["youtube_canal_revisat"])
            if "instagram_revisat" in data:
                artista.instagram_revisat = bool(data["instagram_revisat"])
            # Staff assigning a non-blank MBID manually overrides the
            # auto-match lockout: the decision is that this specific ID is
            # correct, so re-enable automatic sync for future cron runs.
            new_mbid = (
                (data.get("musicbrainz_id") or "").strip()
                if "musicbrainz_id" in data
                else None
            )
            if new_mbid and new_mbid != old_mbid and artista.mb_auto_match_disabled:
                artista.mb_auto_match_disabled = False
            # The `aprovat=True` flip is DEFERRED until after the
            # localitat + Deezer writes below, so approving + adding the
            # Deezer in one PATCH passes the gate. An unapprove applies now.
            approving = "aprovat" in data and bool(data["aprovat"])
            if "aprovat" in data and not bool(data["aprovat"]):
                artista.aprovat = False
            artista.save()

            # If staff just changed the MBID (or set one for the first
            # time), re-sync MB metadata. Without this, stale fields
            # (`mb_recording_id`, `mb_work_id`, `mbrainz_confirmed`) on
            # the artist's Cançons survive the change and corrupt
            # downstream MB-derived ML features. Caught 2026-04-29 on
            # the "Casual" case — the auto-resolver had matched the wrong
            # (US) MBID, staff PATCH'd to the correct (CAT) one, but the
            # cançons stayed tagged with the US recording IDs.
            new_mbid_value = (artista.musicbrainz_id or "").strip()
            if new_mbid_value and new_mbid_value != (old_mbid or ""):
                from music.mb_sync import sync_from_mbid

                try:
                    sync_from_mbid(artista)
                except Exception:
                    logger.exception(
                        "Auto-sync after MBID change failed for artista %s", artista.pk
                    )

            # Replace locations if sent (array of {municipi_id} or {manual}).
            if "localitats" in data:
                artista.localitats.all().delete()
                for loc in data["localitats"] or []:
                    mid = loc.get("municipi_id")
                    manual = (loc.get("manual") or "").strip()
                    if mid:
                        try:
                            m = Municipi.objects.get(pk=int(mid))
                            ArtistaLocalitat.objects.create(artista=artista, municipi=m)
                        except (ValueError, Municipi.DoesNotExist):
                            pass
                    elif manual:
                        ArtistaLocalitat.objects.create(
                            artista=artista, municipi=None, localitat_manual=manual
                        )

            # Replace Deezer IDs if sent (list of ints; first is principal).
            # A collision (the id already belongs to another artist) is no
            # longer swallowed: surface a 409 so staff know to merge,
            # instead of a silent 200 that didn't persist anything.
            if "deezer_ids" in data:
                want = []
                for raw in data["deezer_ids"] or []:
                    try:
                        want.append(int(raw))
                    except (TypeError, ValueError):
                        pass
                existing = set(artista.deezer_ids.values_list("deezer_id", flat=True))
                want_set = set(want)
                if existing - want_set:
                    artista.deezer_ids.filter(
                        deezer_id__in=existing - want_set
                    ).delete()
                for i, dz_id in enumerate(want):
                    if dz_id not in existing:
                        try:
                            with transaction.atomic():
                                ArtistaDeezer.objects.create(
                                    artista=artista,
                                    deezer_id=dz_id,
                                    principal=(i == 0),
                                )
                        except IntegrityError:
                            owner = (
                                ArtistaDeezer.objects.filter(deezer_id=dz_id)
                                .select_related("artista")
                                .first()
                            )
                            transaction.set_rollback(True)
                            return Response(
                                {
                                    "error": (
                                        f"El Deezer {dz_id} ja és de "
                                        f"«{owner.artista.nom if owner else '?'}» "
                                        f"(pk={owner.artista.pk if owner else '?'}); "
                                        "fusioneu-los o canvieu l'ID."
                                    ),
                                    "owner_pk": owner.artista.pk if owner else None,
                                },
                                status=409,
                            )

            # Approval gate (after the anchors are written): an artist may
            # only be approved with at least one Deezer and one localitat.
            if approving:
                if not artista.deezer_ids.exists():
                    transaction.set_rollback(True)
                    return Response(
                        {"error": "Cal almenys un Deezer ID per aprovar l'artista."},
                        status=400,
                    )
                if not artista.localitats.exists():
                    transaction.set_rollback(True)
                    return Response(
                        {"error": "Cal almenys una localitat per aprovar l'artista."},
                        status=400,
                    )
                artista.aprovat = True
                # Invariant `artista_no_aprovat_pendent_review`: clear the
                # queue flag so approving from the edit page doesn't 500.
                if artista.pendent_review:
                    artista.pendent_review = False
                artista.save(update_fields=["aprovat", "pendent_review"])

        log_staff_action(request, "artista_edit", target=artista)

    # Return full detail
    row = _artista_card(artista)
    row.update(
        {
            "homonims": _homonims_payload(artista),
            "lastfm_nom": artista.lastfm_nom or "",
            "percentatge_femeni": artista.percentatge_femeni or "",
            "genere_canonical": artista.genere_canonical or "",
            "genere_locked": artista.genere_locked,
            "genere_choices": list(Artista.GENERE_CANONICAL_CHOICES),
            "social": {
                f: getattr(artista, f) or "" for f, _ in Artista.SOCIAL_LINK_FIELDS
            },
            "localitats": [
                {
                    "municipi_id": loc.municipi.pk if loc.municipi else None,
                    "municipi_nom": loc.municipi.nom if loc.municipi else "",
                    "comarca": loc.municipi.comarca if loc.municipi else "",
                    "territori": (loc.municipi.territori_id if loc.municipi else "ALT"),
                    "manual": loc.localitat_manual or "",
                }
                for loc in artista.localitats.select_related(
                    "municipi", "municipi__territori"
                ).all()
            ],
            "percentatge_choices": list(Artista.PERCENTATGE_FEMENI_CHOICES),
            "social_fields": list(Artista.SOCIAL_LINK_FIELDS),
            "musicbrainz": {
                "id": artista.musicbrainz_id or "",
                "type": artista.mb_type or "",
                "gender": artista.mb_gender or "",
                "area": artista.mb_area or "",
                "area_hierarchy": artista.mb_area_hierarchy or [],
                "begin_date": (
                    artista.mb_begin_date.isoformat() if artista.mb_begin_date else None
                ),
                "end_date": (
                    artista.mb_end_date.isoformat() if artista.mb_end_date else None
                ),
                "disambiguation": artista.mb_disambiguation or "",
                "sort_name": artista.mb_sort_name or "",
                "aliases": artista.mb_aliases or [],
                "tags": artista.mb_tags or [],
                "rating": float(artista.mb_rating) if artista.mb_rating else None,
                "last_sync": (
                    artista.mb_last_sync.isoformat() if artista.mb_last_sync else None
                ),
                "n_isrcs_known": len(
                    (artista.mb_discography_cache or {}).get("isrcs", [])
                ),
                "blocked_mbids": list(artista.mb_blocked_mbids or []),
                "auto_match_disabled": artista.mb_auto_match_disabled,
            },
            "lastfm": {
                # Force +noredirect on the public link so a click
                # never bounces to a homonym (Fades → The Fades).
                # Defence in depth — the cron writes already include
                # this transform, but legacy rows haven't been
                # re-synced yet and we don't want them to point
                # wrong in the meantime.
                "url": to_noredirect_url(artista.lastfm_url or ""),
                "bio_summary": artista.lastfm_bio_summary or "",
                "bio_content": artista.lastfm_bio_content or "",
                "bio_published": (
                    artista.lastfm_bio_published.isoformat()
                    if artista.lastfm_bio_published
                    else None
                ),
                "listeners": artista.lastfm_listeners,
                "playcount_total": artista.lastfm_playcount_total,
                "ontour": artista.lastfm_ontour,
                "tags": artista.lastfm_tags or [],
                "image_small": artista.lastfm_image_small or "",
                "image_medium": artista.lastfm_image_medium or "",
                "image_large": artista.lastfm_image_large or "",
                "image_extralarge": artista.lastfm_image_extralarge or "",
                "last_sync": (
                    artista.lastfm_last_sync.isoformat()
                    if artista.lastfm_last_sync
                    else None
                ),
                "nb_similars": artista.nb_similars_lastfm or 0,
                "auto_match_disabled": artista.lastfm_auto_match_disabled,
                "aliases": [
                    {
                        "pk": a.pk,
                        "nom": a.nom,
                        "confirmat": a.confirmat,
                        "rebutjat": a.rebutjat,
                        "descobert_at": a.descobert_at.isoformat(),
                        "playcount_canonical": a.playcount_canonical,
                        "playcount_variant": a.playcount_variant,
                        "top_tracks_overlap": a.top_tracks_overlap,
                    }
                    for a in artista.lastfm_aliases.all().order_by(
                        "-confirmat", "rebutjat", "-descobert_at"
                    )
                ],
            },
        }
    )
    return Response(row)


def _absorb_lastfm_duplicate_pendents(artista: Artista, alias_nom: str) -> int:
    """When an alias is confirmed (or manually added), look for
    pendent Artistes that the Last.fm-similars cron previously
    created at the same literal name, and absorb them into the
    canonical row.

    Caught 2026-05-01 with Anna Roig and Sabor de Gràcia: the
    pre-alias-era cron auto-created pendents for typographic-
    apostrophe / case-only spellings, and they kept reappearing in
    the staff queue forever. Confirming an alias is the staff's
    explicit signal that the variant belongs to the canonical, so
    that's the moment to clean up.

    Safety rules — only delete if ALL of the following hold:
      * `aprovat=False` (never touch approved data).
      * `font_descoberta == 'lastfm_similar'` (created by the
        similars cron, not via a UserPropostaArtista or manual
        add — those carry user intent and need staff review).
      * 0 Cançons.
      * 0 Deezer IDs.
      * 0 territoris.
      * No verified Cançons referencing it via collab.

    Before deletion, redirect any `ArtistaLastfmSimilar` rows
    pointing at the duplicate to the canonical (skipping any that
    would violate the source/target unique constraint), then drop
    the duplicate. Recompute the canonical's `nb_similars_lastfm`
    cache.

    Returns the count of duplicates absorbed.
    """
    from music.models import ArtistaLastfmSimilar

    name = (alias_nom or "").strip()
    if not name:
        return 0
    candidates = (
        Artista.objects.filter(aprovat=False)
        .filter(font_descoberta="lastfm_similar")
        .filter(Q(lastfm_nom__iexact=name) | Q(nom__iexact=name))
        .exclude(pk=artista.pk)
    )
    absorbed = 0
    for dup in candidates:
        # Safety gates: anything with non-trivial data stays put
        # for human review.
        has_cancons = dup.cancons.exists()
        has_deezer = dup.deezer_ids.exists()
        has_terr = dup.territoris.exists()
        # Check collaborations — if anything still references this
        # pendent as a guest, don't delete or we'll lose the link.
        has_collab = dup.participacions.exists()
        if has_cancons or has_deezer or has_terr or has_collab:
            continue

        # Redirect similar rows. The unique(source, target) means
        # we can't blindly UPDATE if a pair (source, canonical)
        # already exists — drop those duplicates instead.
        existing_canon_sources = set(
            ArtistaLastfmSimilar.objects.filter(target=artista).values_list(
                "source_id", flat=True
            )
        )
        for row in ArtistaLastfmSimilar.objects.filter(target=dup):
            if row.source_id in existing_canon_sources:
                row.delete()
            else:
                row.target = artista
                row.save(update_fields=["target"])
                existing_canon_sources.add(row.source_id)
        # Same for outgoing rows from the duplicate (it shouldn't
        # have any — pendents aren't a similars source — but be
        # defensive).
        ArtistaLastfmSimilar.objects.filter(source=dup).delete()

        dup.delete()
        absorbed += 1

    if absorbed:
        # Recompute the cached count from the now-correct table.
        new_count = ArtistaLastfmSimilar.objects.filter(target=artista).count()
        Artista.objects.filter(pk=artista.pk).update(nb_similars_lastfm=new_count)
    return absorbed


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_lastfm_alias_action(request: Request, pk: int, alias_pk: int) -> Response:
    """Confirm or reject a Last.fm alias candidate.

    Body: {"action": "confirm" | "reject" | "delete"}.

    Confirmed aliases start contributing to the signal sum on the
    next `obtenir_senyal` run. Rejected aliases stay in the DB so
    `detectar_lastfm_aliases` doesn't re-propose the same homonym.
    Delete is for outright removal (e.g. the alias was confirmed by
    mistake and we want to start over).
    """
    from music.models import ArtistaLastfmAlias

    artista = get_object_or_404(Artista, pk=pk)
    alias = get_object_or_404(ArtistaLastfmAlias, pk=alias_pk, artista=artista)
    action = (request.data or {}).get("action", "")
    if action == "confirm":
        alias.confirmat = True
        alias.rebutjat = False
        alias.confirmat_at = timezone.now()
        alias.confirmat_per = request.user if request.user.is_authenticated else None
        alias.save()
        # Sweep pre-existing Last.fm-cron-created pendents at the
        # same literal name into the canonical artist. See
        # `_absorb_lastfm_duplicate_pendents` docstring for safety
        # rules. Audit-log if anything actually got absorbed.
        absorbed = _absorb_lastfm_duplicate_pendents(artista, alias.nom)
        log_staff_action(
            request,
            "lastfm_alias_confirm",
            target=artista,
            alias_pk=alias.pk,
            alias_nom=alias.nom,
            absorbed_pendents=absorbed,
        )
    elif action == "reject":
        alias.confirmat = False
        alias.rebutjat = True
        alias.save()
        log_staff_action(
            request,
            "lastfm_alias_reject",
            target=artista,
            alias_pk=alias.pk,
            alias_nom=alias.nom,
        )
    elif action == "delete":
        alias_nom = alias.nom
        alias.delete()
        log_staff_action(
            request,
            "lastfm_alias_delete",
            target=artista,
            alias_nom=alias_nom,
        )
    else:
        return Response({"error": "action must be confirm/reject/delete"}, status=400)
    return Response({"ok": True})


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_lastfm_alias_create(request: Request, pk: int) -> Response:
    """Manually add a Last.fm alias (already confirmed) for cases
    where staff knows about a variant the auto-detector missed."""
    from music.models import ArtistaLastfmAlias

    artista = get_object_or_404(Artista, pk=pk)
    nom = ((request.data or {}).get("nom") or "").strip()
    if not nom:
        return Response({"error": "nom required"}, status=400)
    alias, created = ArtistaLastfmAlias.objects.get_or_create(
        artista=artista,
        nom=nom,
        defaults={
            "confirmat": True,
            "confirmat_at": timezone.now(),
            "confirmat_per": (request.user if request.user.is_authenticated else None),
        },
    )
    if not created and not alias.confirmat:
        alias.confirmat = True
        alias.rebutjat = False
        alias.confirmat_at = timezone.now()
        alias.confirmat_per = request.user if request.user.is_authenticated else None
        alias.save()
    # Manual additions are confirmed by definition (staff knew the
    # variant), so absorb any pre-existing pendent at that name too.
    absorbed = _absorb_lastfm_duplicate_pendents(artista, nom)
    log_staff_action(
        request,
        "lastfm_alias_manual_add",
        target=artista,
        alias_nom=nom,
        absorbed_pendents=absorbed,
    )
    return Response(
        {"ok": True, "pk": alias.pk, "created": created, "absorbed": absorbed}
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def artistes_fusionar(request: Request) -> Response:
    """Merge multiple artists into one target.

    Body: {"target_pk": int, "source_pks": [int, ...]}
    The target keeps its PK and all data; sources are merged into it
    (cançons, àlbums, Deezer IDs, UserArtista links, HistorialRevisio
    rows, ArtistaLocalitat entries) and then deleted.
    """
    data = request.data or {}
    try:
        target_pk = int(data.get("target_pk"))
        source_pks = [int(x) for x in (data.get("source_pks") or [])]
    except (TypeError, ValueError):
        return Response({"error": "PKs invàlides."}, status=400)
    if not source_pks:
        return Response({"error": "Cap artista origen."}, status=400)
    if target_pk in source_pks:
        return Response(
            {"error": "L'artista destí no pot ser també origen."}, status=400
        )

    target = get_object_or_404(Artista, pk=target_pk)
    sources = list(Artista.objects.filter(pk__in=source_pks))
    if len(sources) != len(set(source_pks)):
        return Response({"error": "Algun artista origen no existeix."}, status=404)

    source_names = [a.nom for a in sources]

    with transaction.atomic():
        for source in sources:
            # Cançons: main artist.
            Canco.objects.filter(artista=source).update(artista=target)
            # Cançons: collaborator. D5 invariant — main artist and
            # collaborator can't coincide; skip the re-add in that case.
            for canco in Canco.objects.filter(artistes_col=source):
                canco.artistes_col.remove(source)
                if canco.artista_id != target.pk:
                    canco.artistes_col.add(target)
            # Clean up any pre-existing D5 overlap.
            for canco in Canco.objects.filter(
                artista=target, artistes_col=target
            ).distinct():
                canco.artistes_col.remove(target)

            Album.objects.filter(artista=source).update(artista=target)
            ArtistaDeezer.objects.filter(artista=source).update(
                artista=target, principal=False
            )
            UserArtista.objects.filter(artista=source).update(artista=target)
            # ML feature `ratio_rebuig_artista` keys on artista_nom —
            # rehome the historic rejections so the target doesn't look
            # like a fresh artist to the classifier.
            HistorialRevisio.objects.filter(artista_nom=source.nom).update(
                artista_nom=target.nom
            )

            target_municipis = set(
                target.localitats.filter(municipi__isnull=False).values_list(
                    "municipi_id", flat=True
                )
            )
            for al in source.localitats.all():
                if al.municipi_id and al.municipi_id in target_municipis:
                    al.delete()
                else:
                    al.artista = target
                    al.save()
                    if al.municipi_id:
                        target_municipis.add(al.municipi_id)

            if not target.genere and source.genere:
                target.genere = source.genere

            source.delete()

        # Principal invariant on Deezer IDs.
        target_ads = list(target.deezer_ids.order_by("created_at"))
        if target_ads and not any(ad.principal for ad in target_ads):
            first = target_ads[0]
            first.principal = True
            first.save(update_fields=["principal"])

        target.save()

    log_staff_action(
        request,
        "artista_fusionar",
        target=target,
        sources_merged=[{"pk": a.pk, "nom": n} for a, n in zip(sources, source_names)],
        target_artista_pk=target.pk,
    )
    return Response(
        {
            "ok": True,
            "target_pk": target.pk,
            "target_nom": target.nom,
            "fusionats": len(sources),
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_sync_mb(request: Request, pk: int) -> Response:
    """Run MusicBrainz sync synchronously for a single artist."""
    from music.mb_sync import resolve_mbid, sync_from_mbid

    artista = get_object_or_404(Artista, pk=pk)
    if not artista.musicbrainz_id:
        mbid = resolve_mbid(artista)
        if mbid:
            artista.musicbrainz_id = mbid
            artista.save(update_fields=["musicbrainz_id"])
        else:
            return Response(
                {
                    "ok": False,
                    "msg": "No s'ha pogut resoldre un MBID únic per aquest nom. "
                    "Omple'l manualment a partir de musicbrainz.org.",
                }
            )
    counters = sync_from_mbid(artista)
    log_staff_action(request, "artista_sync_mb", target=artista, **counters)
    return Response({"ok": True, "counters": counters})


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_mb_clear(request: Request, pk: int) -> Response:
    """Unlink an artist from MusicBrainz, optionally blocking the MBID.

    Body (JSON): {"block": true|false, "disable_auto": true|false}

    * `block` (default true) — append the current MBID to the artist's
      `mb_blocked_mbids` list so the auto-resolver won't reassign it
      on the next cron run.
    * `disable_auto` (default false) — set `mb_auto_match_disabled=True`,
      stopping *any* automatic match. Use when MB has no entry for the
      artist at all (not even homonyms worth blocking).

    Clears every mb_* field on Artista, on the linked Albums (release
    group), and on the Cançons (recording, work, language). Does not
    delete Albums or Cançons themselves. Refuses to proceed if doing so
    would leave an approved artist with no external anchor (no Deezer
    ID and now no MBID): mirrors the invariant enforced by the
    ArtistaDeezer post_delete signal.
    """
    artista = get_object_or_404(Artista, pk=pk)
    data = request.data or {}
    block = data.get("block", True)
    disable_auto = bool(data.get("disable_auto", False))

    old_mbid = artista.musicbrainz_id or ""

    # Invariant guard: an approved artist needs at least one anchor.
    has_deezer = ArtistaDeezer.objects.filter(artista=artista).exists()
    if artista.aprovat and not has_deezer and not disable_auto is False:
        # disable_auto doesn't affect the anchor count; this is really
        # about whether we're removing the last anchor at all.
        pass
    if artista.aprovat and not has_deezer and old_mbid:
        return Response(
            {
                "error": (
                    "No es pot desvincular: l'artista està aprovat i només "
                    "té MusicBrainz com a àncora externa (no té cap ID de "
                    "Deezer). Assigna'l un Deezer ID abans de desvincular "
                    "el MBID o desaprova'l manualment."
                )
            },
            status=400,
        )

    with transaction.atomic():
        if block and old_mbid:
            blocked = list(artista.mb_blocked_mbids or [])
            if old_mbid not in blocked:
                blocked.append(old_mbid)
            artista.mb_blocked_mbids = blocked
        if disable_auto:
            artista.mb_auto_match_disabled = True
        # Wipe artist-level MB fields.
        artista.musicbrainz_id = None
        artista.mb_type = ""
        artista.mb_gender = ""
        artista.mb_area = ""
        artista.mb_area_hierarchy = []
        artista.mb_begin_date = None
        artista.mb_end_date = None
        artista.mb_disambiguation = ""
        artista.mb_sort_name = ""
        artista.mb_aliases = []
        artista.mb_tags = []
        artista.mb_rating = None
        artista.mb_discography_cache = {}
        artista.mb_last_sync = None
        artista.save()

        # Detach any Album/Canco rows linked to this artist from MB so
        # the next cron doesn't re-assert stale confirmations.
        Album.objects.filter(artista=artista).exclude(mb_release_group_id="").update(
            mb_release_group_id="",
            mb_type_secondary="",
            mb_status="",
            mbrainz_confirmed=None,
        )
        Canco.objects.filter(artista=artista).exclude(mb_recording_id="").update(
            mb_recording_id="",
            mb_work_id="",
            mb_lyrics_language="",
            mbrainz_confirmed=None,
        )

    log_staff_action(
        request,
        "artista_edit",
        target=artista,
        source="mb_clear",
        old_mbid=old_mbid,
        blocked=block and bool(old_mbid),
        disable_auto=disable_auto,
    )
    return Response(
        {
            "ok": True,
            "old_mbid": old_mbid,
            "blocked": block and bool(old_mbid),
            "auto_match_disabled": artista.mb_auto_match_disabled,
            "blocked_mbids": artista.mb_blocked_mbids,
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_lastfm_clear(request: Request, pk: int) -> Response:
    """Disconnect an artiste from Last.fm to stop ingesting wrong
    data when Last.fm has the canonical name colliding with another
    artist (e.g. our Mallorcan LGBT band "Fades" silently
    redirected to the English punk band "The Fades").

    Body (JSON): {"disable_auto": true|false} — default true.

    Side effects:
      * Clears all `lastfm_*` fields on the Artista (tags, listeners,
        playcount, image, bio, similars). Subsequent passes of
        `obtenir_metadata_lastfm` would normally repopulate them; the
        `lastfm_auto_match_disabled` flag stops that.
      * `disable_auto=True` (default): sets
        `lastfm_auto_match_disabled=True`. The cron skips the artiste
        forever until staff manually re-enables (no UI for that yet —
        edit via Django shell if needed).
      * Re-runs `inferir_genere` immediately on this artiste so the
        canonical genre falls back to MB-tags-only (or empties if MB
        is also empty).
    """
    artista = get_object_or_404(Artista, pk=pk)
    disable_auto = bool((request.data or {}).get("disable_auto", True))

    with transaction.atomic():
        if disable_auto:
            artista.lastfm_auto_match_disabled = True
        # Clear Last.fm-derived fields. lastfm_url + lastfm_nom stay
        # so staff can paste a corrected URL later if MB or another
        # source eventually identifies the right artist.
        artista.lastfm_tags = []
        artista.lastfm_listeners = None
        artista.lastfm_playcount_total = None
        artista.lastfm_te_scrobbles = None
        artista.lastfm_image_small = ""
        artista.lastfm_image_medium = ""
        artista.lastfm_image_large = ""
        artista.lastfm_image_extralarge = ""
        artista.lastfm_bio_summary = ""
        artista.lastfm_bio_content = ""
        artista.lastfm_bio_published = None
        artista.lastfm_ontour = None
        artista.lastfm_last_sync = None
        artista.save()

        # Re-infer genre now that the bad tags are gone (only takes
        # effect when genere_locked=False, which is the common case).
        if not artista.genere_locked:
            from music.genere import infer_canonical

            artista.genere_canonical = infer_canonical([], artista.mb_tags)
            artista.save(update_fields=["genere_canonical"])

    log_staff_action(
        request,
        "artista_edit",
        target=artista,
        source="lastfm_clear",
        disable_auto=disable_auto,
    )
    return Response(
        {
            "ok": True,
            "auto_match_disabled": artista.lastfm_auto_match_disabled,
            "genere_canonical": artista.genere_canonical or "",
        }
    )
