"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate
from web.api.staff.estat import _homonym_suspects_qs
from web.api.staff.pendents import _artista_card

# ═════════════════════════════════════════════════════════════════════════
# Artistes — approved artists management
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def artistes_list(request: Request) -> Response:
    qs = Artista.objects.prefetch_related(
        "territoris", "localitats__municipi", "deezer_ids"
    )
    aprovat = request.GET.get("aprovat", "1")
    if aprovat == "1":
        qs = qs.filter(aprovat=True)
    elif aprovat == "0":
        qs = qs.filter(aprovat=False)
    deezer = request.GET.get("deezer", "")
    if deezer == "si":
        qs = qs.filter(deezer_ids__isnull=False)
    elif deezer == "no":
        qs = qs.filter(deezer_ids__isnull=True)
    territori = request.GET.get("territori", "")
    if territori:
        qs = qs.filter(territoris__codi=territori)
    # MusicBrainz filters — surface artists that still need manual MBID
    # resolution, or those flagged as dissolved. The two new filters
    # `provat_sense_mbid` / `mai_provat` split the legacy `sense_mbid`
    # bucket so staff can act on the right subset.
    mb = request.GET.get("mb", "")
    if mb == "sense_mbid":
        qs = qs.filter(Q(musicbrainz_id__isnull=True) | Q(musicbrainz_id=""))
    elif mb == "amb_mbid":
        qs = qs.exclude(musicbrainz_id__isnull=True).exclude(musicbrainz_id="")
    elif mb == "dissolt":
        qs = qs.filter(mb_end_date__isnull=False)
    elif mb == "no_sincronitzat" or mb == "mai_provat":
        qs = qs.filter(mb_last_sync__isnull=True)
    elif mb == "provat_sense_mbid":
        qs = qs.filter(Q(musicbrainz_id__isnull=True) | Q(musicbrainz_id="")).filter(
            mb_last_sync__isnull=False
        )
    elif mb == "bloquejat":
        qs = qs.filter(mb_auto_match_disabled=True)

    # Homonym-collision suspects: at least one Cançó rejected as
    # `artista_incorrecte` AND at least one still active. See
    # `_homonym_suspects_qs` for the rationale.
    if request.GET.get("homonim_sospitos") == "1":
        qs = qs.filter(pk__in=_homonym_suspects_qs().values("pk"))

    # Per-social filter: handy when staff needs to chase down missing
    # social handles for outreach (Instagram is the most relevant for
    # publication, hence first-class; the rest can be added the same way).
    instagram = request.GET.get("instagram", "")
    if instagram == "no":
        qs = qs.filter(Q(instagram_url="") | Q(instagram_url__isnull=True))
    elif instagram == "si":
        qs = qs.exclude(instagram_url="").exclude(instagram_url__isnull=True)

    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(_nom_norm=_unaccent_field("nom")).filter(
            _nom_norm__contains=_normalize_search_term(cerca)
        )

    # Sort: default is alphabetical, but the publication workflow
    # benefits from "artistes amb més presència històrica al top" so
    # we annotate distinct charted Cançons (main artist) and sort by
    # that. TopSetmanal stores one row per (canço, territori,
    # setmana) — distinct on the canço so a track appearing 10 weeks
    # in the CAT top doesn't outweigh a track in 9 distinct top tracks.
    sort_raw = (request.GET.get("sort") or "").strip()
    if sort_raw == "cancons_tops_desc":
        qs = (
            qs.annotate(
                n_cancons_tops=Count(
                    "cancons__rankings",
                    filter=Q(cancons__rankings__posicio__lte=40),
                    distinct=True,
                )
            )
            .distinct()
            .order_by("-n_cancons_tops", Lower("nom"))
        )
    else:
        qs = qs.distinct().order_by(Lower("nom"))

    page, meta = _paginate(qs, request)
    return Response({"results": [_artista_card(a) for a in page.object_list], **meta})


@api_view(["GET"])
@permission_classes([IsStaff])
def artistes_search(request: Request) -> Response:
    """Light-weight lookup for the reassignment typeaheads.

    Returns up to 10 candidate artists (aprovats=True by default, but
    we surface pending/descartats too when the search is explicit, so
    staff can pick a pending artist to land a mis-assigned track on).
    """
    q = (request.GET.get("q") or "").strip()
    if len(q) < 2:
        return Response({"results": []})
    qs = (
        Artista.objects.annotate(_nom_norm=_unaccent_field("nom"))
        .filter(_nom_norm__contains=_normalize_search_term(q))
        .order_by("-aprovat", "nom")[:10]
    )
    return Response(
        {
            "results": [
                {
                    "pk": a.pk,
                    "nom": a.nom,
                    "slug": a.slug,
                    "aprovat": a.aprovat,
                    "pendent_review": a.pendent_review,
                }
                for a in qs
            ]
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_crear(request: Request) -> Response:
    data = request.data or {}
    nom = (data.get("nom") or "").strip()
    if not nom:
        return Response({"error": "El nom és obligatori."}, status=400)
    lastfm_nom = (data.get("lastfm_nom") or "").strip() or nom
    deezer_raw = (data.get("deezer_id") or "").strip() if data.get("deezer_id") else ""
    deezer_id = None
    if deezer_raw:
        try:
            deezer_id = int(deezer_raw)
        except ValueError:
            return Response(
                {"error": "Deezer ID ha de ser un nombre enter."}, status=400
            )
    with transaction.atomic():
        artista = Artista.objects.create(
            nom=nom,
            lastfm_nom=lastfm_nom,
            aprovat=True,
            auto_descobert=False,
            font_descoberta="manual",
        )
        if deezer_id is not None:
            try:
                ArtistaDeezer.objects.create(
                    artista=artista, deezer_id=deezer_id, principal=True
                )
            except IntegrityError:
                return Response(
                    {"error": f"Deezer ID {deezer_id} ja pertany a un altre artista."},
                    status=409,
                )
        log_staff_action(request, "artista_crear", target=artista, deezer_id=deezer_id)
    return Response({"ok": True, "pk": artista.pk, "slug": artista.slug})


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def artista_detail(request: Request, pk: int) -> Response:
    artista = get_object_or_404(Artista, pk=pk)
    if request.method == "PATCH":
        data = request.data or {}
        simple_fields = [
            "nom",
            "lastfm_nom",
            "genere",
            "percentatge_femeni",
            "musicbrainz_id",
        ] + [f for f, _ in Artista.SOCIAL_LINK_FIELDS]
        old_mbid = artista.musicbrainz_id
        for f in simple_fields:
            if f in data:
                setattr(artista, f, (data.get(f) or "").strip())
        # Staff assigning a non-blank MBID manually overrides the
        # auto-match lockout: the decision is that this specific ID is
        # correct, so re-enable automatic sync for future cron runs.
        new_mbid = (
            (data.get("musicbrainz_id") or "").strip()
            if "musicbrainz_id" in data
            else None
        )
        if new_mbid and new_mbid != old_mbid and artista.mb_auto_match_disabled:
            artista.mb_auto_match_disabled = False
        if "aprovat" in data:
            artista.aprovat = bool(data["aprovat"])
            # Invariant enforced by `artista_no_aprovat_pendent_review`:
            # aprovat=True + pendent_review=True is not allowed. Clear
            # the queue flag so a PATCH that approves straight from the
            # edit page doesn't 500 on the CheckConstraint.
            if artista.aprovat and artista.pendent_review:
                artista.pendent_review = False
        artista.save()

        # Replace locations if sent (array of {municipi_id} or {manual}).
        if "localitats" in data:
            artista.localitats.all().delete()
            for loc in data["localitats"] or []:
                mid = loc.get("municipi_id")
                manual = (loc.get("manual") or "").strip()
                if mid:
                    try:
                        m = Municipi.objects.get(pk=int(mid))
                        ArtistaLocalitat.objects.create(artista=artista, municipi=m)
                    except (ValueError, Municipi.DoesNotExist):
                        pass
                elif manual:
                    ArtistaLocalitat.objects.create(
                        artista=artista, municipi=None, localitat_manual=manual
                    )

        # Replace Deezer IDs if sent (list of ints; first is principal).
        if "deezer_ids" in data:
            want = []
            for raw in data["deezer_ids"] or []:
                try:
                    want.append(int(raw))
                except (TypeError, ValueError):
                    pass
            existing = set(artista.deezer_ids.values_list("deezer_id", flat=True))
            want_set = set(want)
            if existing - want_set:
                artista.deezer_ids.filter(deezer_id__in=existing - want_set).delete()
            for i, dz_id in enumerate(want):
                if dz_id not in existing:
                    try:
                        ArtistaDeezer.objects.create(
                            artista=artista, deezer_id=dz_id, principal=(i == 0)
                        )
                    except IntegrityError:
                        pass
        log_staff_action(request, "artista_edit", target=artista)

    # Return full detail
    row = _artista_card(artista)
    row.update(
        {
            "lastfm_nom": artista.lastfm_nom or "",
            "percentatge_femeni": artista.percentatge_femeni or "",
            "social": {
                f: getattr(artista, f) or "" for f, _ in Artista.SOCIAL_LINK_FIELDS
            },
            "localitats": [
                {
                    "municipi_id": loc.municipi.pk if loc.municipi else None,
                    "municipi_nom": loc.municipi.nom if loc.municipi else "",
                    "comarca": loc.municipi.comarca if loc.municipi else "",
                    "territori": (loc.municipi.territori_id if loc.municipi else "ALT"),
                    "manual": loc.localitat_manual or "",
                }
                for loc in artista.localitats.select_related(
                    "municipi", "municipi__territori"
                ).all()
            ],
            "percentatge_choices": list(Artista.PERCENTATGE_FEMENI_CHOICES),
            "social_fields": list(Artista.SOCIAL_LINK_FIELDS),
            "musicbrainz": {
                "id": artista.musicbrainz_id or "",
                "type": artista.mb_type or "",
                "gender": artista.mb_gender or "",
                "area": artista.mb_area or "",
                "area_hierarchy": artista.mb_area_hierarchy or [],
                "begin_date": (
                    artista.mb_begin_date.isoformat() if artista.mb_begin_date else None
                ),
                "end_date": (
                    artista.mb_end_date.isoformat() if artista.mb_end_date else None
                ),
                "disambiguation": artista.mb_disambiguation or "",
                "sort_name": artista.mb_sort_name or "",
                "aliases": artista.mb_aliases or [],
                "tags": artista.mb_tags or [],
                "rating": float(artista.mb_rating) if artista.mb_rating else None,
                "last_sync": (
                    artista.mb_last_sync.isoformat() if artista.mb_last_sync else None
                ),
                "n_isrcs_known": len(
                    (artista.mb_discography_cache or {}).get("isrcs", [])
                ),
                "blocked_mbids": list(artista.mb_blocked_mbids or []),
                "auto_match_disabled": artista.mb_auto_match_disabled,
            },
            "lastfm": {
                "url": artista.lastfm_url or "",
                "bio_summary": artista.lastfm_bio_summary or "",
                "bio_content": artista.lastfm_bio_content or "",
                "bio_published": (
                    artista.lastfm_bio_published.isoformat()
                    if artista.lastfm_bio_published
                    else None
                ),
                "listeners": artista.lastfm_listeners,
                "playcount_total": artista.lastfm_playcount_total,
                "ontour": artista.lastfm_ontour,
                "tags": artista.lastfm_tags or [],
                "image_small": artista.lastfm_image_small or "",
                "image_medium": artista.lastfm_image_medium or "",
                "image_large": artista.lastfm_image_large or "",
                "image_extralarge": artista.lastfm_image_extralarge or "",
                "last_sync": (
                    artista.lastfm_last_sync.isoformat()
                    if artista.lastfm_last_sync
                    else None
                ),
                "nb_similars": artista.nb_similars_lastfm or 0,
                "auto_match_disabled": artista.lastfm_auto_match_disabled,
            },
        }
    )
    return Response(row)


@api_view(["POST"])
@permission_classes([IsStaff])
def artistes_fusionar(request: Request) -> Response:
    """Merge multiple artists into one target.

    Body: {"target_pk": int, "source_pks": [int, ...]}
    The target keeps its PK and all data; sources are merged into it
    (cançons, àlbums, Deezer IDs, UserArtista links, HistorialRevisio
    rows, ArtistaLocalitat entries) and then deleted.
    """
    data = request.data or {}
    try:
        target_pk = int(data.get("target_pk"))
        source_pks = [int(x) for x in (data.get("source_pks") or [])]
    except (TypeError, ValueError):
        return Response({"error": "PKs invàlides."}, status=400)
    if not source_pks:
        return Response({"error": "Cap artista origen."}, status=400)
    if target_pk in source_pks:
        return Response(
            {"error": "L'artista destí no pot ser també origen."}, status=400
        )

    target = get_object_or_404(Artista, pk=target_pk)
    sources = list(Artista.objects.filter(pk__in=source_pks))
    if len(sources) != len(set(source_pks)):
        return Response({"error": "Algun artista origen no existeix."}, status=404)

    source_names = [a.nom for a in sources]

    with transaction.atomic():
        for source in sources:
            # Cançons: main artist.
            Canco.objects.filter(artista=source).update(artista=target)
            # Cançons: collaborator. D5 invariant — main artist and
            # collaborator can't coincide; skip the re-add in that case.
            for canco in Canco.objects.filter(artistes_col=source):
                canco.artistes_col.remove(source)
                if canco.artista_id != target.pk:
                    canco.artistes_col.add(target)
            # Clean up any pre-existing D5 overlap.
            for canco in Canco.objects.filter(
                artista=target, artistes_col=target
            ).distinct():
                canco.artistes_col.remove(target)

            Album.objects.filter(artista=source).update(artista=target)
            ArtistaDeezer.objects.filter(artista=source).update(
                artista=target, principal=False
            )
            UserArtista.objects.filter(artista=source).update(artista=target)
            # ML feature `ratio_rebuig_artista` keys on artista_nom —
            # rehome the historic rejections so the target doesn't look
            # like a fresh artist to the classifier.
            HistorialRevisio.objects.filter(artista_nom=source.nom).update(
                artista_nom=target.nom
            )

            target_municipis = set(
                target.localitats.filter(municipi__isnull=False).values_list(
                    "municipi_id", flat=True
                )
            )
            for al in source.localitats.all():
                if al.municipi_id and al.municipi_id in target_municipis:
                    al.delete()
                else:
                    al.artista = target
                    al.save()
                    if al.municipi_id:
                        target_municipis.add(al.municipi_id)

            if not target.genere and source.genere:
                target.genere = source.genere

            source.delete()

        # Principal invariant on Deezer IDs.
        target_ads = list(target.deezer_ids.order_by("created_at"))
        if target_ads and not any(ad.principal for ad in target_ads):
            first = target_ads[0]
            first.principal = True
            first.save(update_fields=["principal"])

        target.save()

    log_staff_action(
        request,
        "artista_fusionar",
        target=target,
        sources_merged=[{"pk": a.pk, "nom": n} for a, n in zip(sources, source_names)],
        target_artista_pk=target.pk,
    )
    return Response(
        {
            "ok": True,
            "target_pk": target.pk,
            "target_nom": target.nom,
            "fusionats": len(sources),
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_sync_mb(request: Request, pk: int) -> Response:
    """Run MusicBrainz sync synchronously for a single artist."""
    from music.mb_sync import resolve_mbid, sync_from_mbid

    artista = get_object_or_404(Artista, pk=pk)
    if not artista.musicbrainz_id:
        mbid = resolve_mbid(artista)
        if mbid:
            artista.musicbrainz_id = mbid
            artista.save(update_fields=["musicbrainz_id"])
        else:
            return Response(
                {
                    "ok": False,
                    "msg": "No s'ha pogut resoldre un MBID únic per aquest nom. "
                    "Omple'l manualment a partir de musicbrainz.org.",
                }
            )
    counters = sync_from_mbid(artista)
    log_staff_action(request, "artista_sync_mb", target=artista, **counters)
    return Response({"ok": True, "counters": counters})


@api_view(["POST"])
@permission_classes([IsStaff])
def artista_mb_clear(request: Request, pk: int) -> Response:
    """Unlink an artist from MusicBrainz, optionally blocking the MBID.

    Body (JSON): {"block": true|false, "disable_auto": true|false}

    * `block` (default true) — append the current MBID to the artist's
      `mb_blocked_mbids` list so the auto-resolver won't reassign it
      on the next cron run.
    * `disable_auto` (default false) — set `mb_auto_match_disabled=True`,
      stopping *any* automatic match. Use when MB has no entry for the
      artist at all (not even homonyms worth blocking).

    Clears every mb_* field on Artista, on the linked Albums (release
    group), and on the Cançons (recording, work, language). Does not
    delete Albums or Cançons themselves. Refuses to proceed if doing so
    would leave an approved artist with no external anchor (no Deezer
    ID and now no MBID): mirrors the invariant enforced by the
    ArtistaDeezer post_delete signal.
    """
    artista = get_object_or_404(Artista, pk=pk)
    data = request.data or {}
    block = data.get("block", True)
    disable_auto = bool(data.get("disable_auto", False))

    old_mbid = artista.musicbrainz_id or ""

    # Invariant guard: an approved artist needs at least one anchor.
    has_deezer = ArtistaDeezer.objects.filter(artista=artista).exists()
    if artista.aprovat and not has_deezer and not disable_auto is False:
        # disable_auto doesn't affect the anchor count; this is really
        # about whether we're removing the last anchor at all.
        pass
    if artista.aprovat and not has_deezer and old_mbid:
        return Response(
            {
                "error": (
                    "No es pot desvincular: l'artista està aprovat i només "
                    "té MusicBrainz com a àncora externa (no té cap ID de "
                    "Deezer). Assigna'l un Deezer ID abans de desvincular "
                    "el MBID o desaprova'l manualment."
                )
            },
            status=400,
        )

    with transaction.atomic():
        if block and old_mbid:
            blocked = list(artista.mb_blocked_mbids or [])
            if old_mbid not in blocked:
                blocked.append(old_mbid)
            artista.mb_blocked_mbids = blocked
        if disable_auto:
            artista.mb_auto_match_disabled = True
        # Wipe artist-level MB fields.
        artista.musicbrainz_id = None
        artista.mb_type = ""
        artista.mb_gender = ""
        artista.mb_area = ""
        artista.mb_area_hierarchy = []
        artista.mb_begin_date = None
        artista.mb_end_date = None
        artista.mb_disambiguation = ""
        artista.mb_sort_name = ""
        artista.mb_aliases = []
        artista.mb_tags = []
        artista.mb_rating = None
        artista.mb_discography_cache = {}
        artista.mb_last_sync = None
        artista.save()

        # Detach any Album/Canco rows linked to this artist from MB so
        # the next cron doesn't re-assert stale confirmations.
        Album.objects.filter(artista=artista).exclude(mb_release_group_id="").update(
            mb_release_group_id="",
            mb_type_secondary="",
            mb_status="",
            mbrainz_confirmed=None,
        )
        Canco.objects.filter(artista=artista).exclude(mb_recording_id="").update(
            mb_recording_id="",
            mb_work_id="",
            mb_lyrics_language="",
            mbrainz_confirmed=None,
        )

    log_staff_action(
        request,
        "artista_edit",
        target=artista,
        source="mb_clear",
        old_mbid=old_mbid,
        blocked=block and bool(old_mbid),
        disable_auto=disable_auto,
    )
    return Response(
        {
            "ok": True,
            "old_mbid": old_mbid,
            "blocked": block and bool(old_mbid),
            "auto_match_disabled": artista.mb_auto_match_disabled,
            "blocked_mbids": artista.mb_blocked_mbids,
        }
    )
