"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Auditoria (StaffAuditLog)
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def auditlog(request: Request) -> Response:
    qs = StaffAuditLog.objects.select_related("actor").order_by("-created_at")
    action = request.GET.get("action", "")
    if action:
        qs = qs.filter(action=action)
    actor_email = (request.GET.get("actor") or "").strip()
    if actor_email:
        qs = qs.filter(actor__email__icontains=actor_email)
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.filter(target_label__icontains=cerca)
    page, meta = _paginate(qs, request)
    return Response(
        {
            "action_choices": [
                {"value": v, "label": lbl} for v, lbl in StaffAuditLog.ACTION_CHOICES
            ],
            "results": [
                {
                    "pk": r.pk,
                    "action": r.action,
                    "created_at": r.created_at.isoformat() if r.created_at else None,
                    "actor_email": r.actor.email if r.actor else "",
                    "target_type": r.target_type or "",
                    "target_id": r.target_id,
                    "target_label": r.target_label or "",
                    "metadata": r.metadata or {},
                }
                for r in page.object_list
            ],
            **meta,
        }
    )
