"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from music.models import (
    StaffAuditLog,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Auditoria (StaffAuditLog)
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def auditlog(request: Request) -> Response:
    qs = StaffAuditLog.objects.select_related("actor").order_by("-created_at")
    action = request.GET.get("action", "")
    if action:
        qs = qs.filter(action=action)
    actor_email = (request.GET.get("actor") or "").strip()
    if actor_email:
        qs = qs.filter(actor__email__icontains=actor_email)
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.filter(target_label__icontains=cerca)
    page, meta = _paginate(qs, request)
    return Response(
        {
            "action_choices": [
                {"value": v, "label": lbl} for v, lbl in StaffAuditLog.ACTION_CHOICES
            ],
            "results": [
                {
                    "pk": r.pk,
                    "action": r.action,
                    "created_at": r.created_at.isoformat() if r.created_at else None,
                    "actor_email": r.actor.email if r.actor else "",
                    "target_type": r.target_type or "",
                    "target_id": r.target_id,
                    "target_label": r.target_label or "",
                    "metadata": r.metadata or {},
                }
                for r in page.object_list
            ],
            **meta,
        }
    )
