"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db import IntegrityError, transaction
from django.db.models import (
    Q,
)
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.dateparse import parse_date
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from music.audit import log_staff_action
from music.constants import MOTIUS_VALIDS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    Canco,
    CancoYouTubeVideo,
    SpotifyMetadata,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field
from web.api.staff._spotify_url import SpotifyUrlError, parse_track_id
from web.api.staff._youtube_url import YoutubeUrlError, parse_video_id

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate, noms_amb_homonims

# ═════════════════════════════════════════════════════════════════════════
# Cançons — track management
# ═════════════════════════════════════════════════════════════════════════


def _canco_row(c, homset=None) -> dict:
    # Spotify enrichment payload (Process B, see ADR-0012). The
    # OneToOne reverse accessor raises DoesNotExist when there's no
    # SpotifyMetadata row, which is the legitimate state for Cançons
    # created before migration 0080 or never processed; getattr with
    # default keeps the response shape stable.
    sm = getattr(c, "spotify", None)
    spotify_payload = None
    if (
        sm is not None
        and sm.enrichment_status in SpotifyMetadata.LOCKED_STATUSES
        and sm.spotify_id
    ):
        # Hydration state (manual links are id-first, hydrated later by
        # Process B from the id — see playlists.md). Three states so the
        # editor can distinguish a still-queued link from a bad id:
        #   ok      — spotify_artist_id resolved (fully hydrated)
        #   pending — manual id saved, not yet hydrated (enriched_at NULL)
        #   failed  — hydration ran but couldn't resolve the id (bad URL):
        #             enriched_at stamped, spotify_artist_id still empty
        if sm.spotify_artist_id:
            hydration = "ok"
        elif sm.enriched_at is None:
            hydration = "pending"
        else:
            hydration = "failed"
        spotify_payload = {
            "spotify_id": sm.spotify_id,
            "artist_name": sm.spotify_artist_name or "",
            "artist_id": sm.spotify_artist_id or "",
            # True when a staff member pasted the id by hand (Process A
            # puts it in playlists like `found`; Process B hydrates it
            # from the id without re-resolving via /search).
            "is_manual": sm.enrichment_status == SpotifyMetadata.STATUS_MANUAL,
            "hydration": hydration,
        }
    return {
        "pk": c.pk,
        "nom": c.nom,
        "slug": c.slug,
        "verificada": c.verificada,
        "activa": c.activa,
        "ml_classe": c.ml_classe or "",
        "ml_confianca": c.ml_confianca,
        "isrc": c.isrc or "",
        "deezer_id": c.deezer_id,
        "data_llancament": (
            c.data_llancament.isoformat() if c.data_llancament else None
        ),
        "lastfm_nom": c.lastfm_nom or "",
        "whisper_lang": c.whisper_lang or "",
        "mb_recording_id": c.mb_recording_id or "",
        "mb_work_id": c.mb_work_id or "",
        "mb_lyrics_language": c.mb_lyrics_language or "",
        "mbrainz_confirmed": c.mbrainz_confirmed,
        "spotify": spotify_payload,
        # YouTube lanes. `youtube_video_id` is the Art Track pointer (one
        # per song); `youtube_videos` are the official-channel lanes
        # (videoclip, live, lyric). Both are read-only here except the
        # pointer — see `canco_detail`. `revisat` is the third state that
        # lets a song leave the daily action list without a video.
        "youtube": {
            "video_id": c.youtube_video_id or "",
            "match": c.youtube_match or "",
            "revisat": c.youtube_revisat,
            "carrils": [
                {"video_id": v.video_id, "titol": v.titol}
                for v in c.youtube_videos.all()
            ],
        },
        "artista": (
            {
                "pk": c.artista_id,
                "nom": c.artista.nom,
                "aprovat": c.artista.aprovat,
                "pendent_review": c.artista.pendent_review,
                "musicbrainz_id": c.artista.musicbrainz_id or "",
                "mb_end_date": (
                    c.artista.mb_end_date.isoformat() if c.artista.mb_end_date else None
                ),
                # Spotify dispersion: count of distinct principal
                # spotify_artist_ids across this artista's enriched
                # cançons. >1 is the "possible Deezer barreja" badge
                # the SPA surfaces on the row.
                "spotify_dispersio": c.artista.spotify_artist_dispersio,
                # Homonym marker: another artista shares this name (modulo
                # accents + punctuation). Heads-up for the Crim case.
                "te_homonims": (
                    bool(c.artista.nom_normalitzat)
                    and c.artista.nom_normalitzat in homset
                    if homset is not None
                    else c.artista.homonims().exists()
                ),
            }
            if c.artista
            else None
        ),
        "album": (
            {"pk": c.album_id, "nom": c.album.nom, "slug": c.album.slug}
            if c.album
            else None
        ),
        # artistes_col is a ManyToMany on Canco. Expose the list on every
        # row so staff can see collabs at a glance in the edit page.
        "artistes_col": [
            {"pk": a.pk, "nom": a.nom, "slug": a.slug, "aprovat": a.aprovat}
            for a in c.artistes_col.all()
        ],
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def cancons_list(request: Request) -> Response:
    # Pick the base queryset via the manager method so the
    # no_verificades Spotify playlists (which also call `pendents()`)
    # cannot drift from this workbench view. `pendents()` = verificada=
    # False AND activa=True. The verificada=="1" branch keeps its old
    # `verificada=True only` semantics on purpose so staff can still
    # inspect already-verified caducades.
    verificada = request.GET.get("verificada", "0")
    if verificada == "0":
        qs = Canco.objects.pendents()
    elif verificada == "1":
        qs = Canco.objects.filter(verificada=True)
    else:
        qs = Canco.objects.all()
    # select_related: artista + album (FK) and spotify (reverse OneToOne,
    # read per row in _canco_row). prefetch_related: artistes_col (M2M
    # iterated per row). Without these the row builder fired one query per
    # row for the collab list and the Spotify payload — N+1 ×up-to-200
    # (auditoria 2026-06-07).
    qs = qs.select_related("artista", "album", "spotify").prefetch_related(
        "artistes_col", "youtube_videos"
    )
    ml_classe = request.GET.get("ml_classe", "")
    if ml_classe in ("A", "B", "C"):
        qs = qs.filter(ml_classe=ml_classe)
    whisper = request.GET.get("whisper", "")
    if whisper == "ca":
        qs = qs.filter(whisper_lang="ca")
    elif whisper == "no_ca":
        qs = qs.filter(whisper_processat_at__isnull=False).exclude(whisper_lang="ca")
    elif whisper == "pendent":
        qs = qs.filter(whisper_processat_at__isnull=True)
    # "Sense Deezer" — a verified track without a deezer_id is the
    # legacy/mis-ingest case worth auditing. `no` surfaces only those,
    # `si` only the tracks that do have an ID (rarely needed, handy
    # for QA).
    deezer = request.GET.get("deezer", "")
    if deezer == "no":
        qs = qs.filter(deezer_id__isnull=True)
    elif deezer == "si":
        qs = qs.filter(deezer_id__isnull=False)
    # MusicBrainz filters: confirmat (MB attests ownership), no_confirmat
    # (synced but didn't match), desconegut (not yet reconciled), cat
    # (Work.language == 'cat'), artista_dissolt (main artist has mb_end_date).
    mb = request.GET.get("mb", "")
    if mb == "confirmat":
        qs = qs.filter(mbrainz_confirmed=True)
    elif mb == "no_confirmat":
        qs = qs.filter(mbrainz_confirmed=False)
    elif mb == "desconegut":
        qs = qs.filter(mbrainz_confirmed__isnull=True)
    elif mb == "cat":
        qs = qs.filter(mb_lyrics_language="cat")
    elif mb == "artista_dissolt":
        qs = qs.filter(artista__mb_end_date__isnull=False)
    # Track not (yet) MB-confirmed but its main artist already has an
    # MBID — candidates for a targeted MB sync.
    elif mb == "artista_amb_mbid":
        qs = (
            qs.filter(mbrainz_confirmed__isnull=True)
            .exclude(artista__musicbrainz_id__isnull=True)
            .exclude(artista__musicbrainz_id="")
        )
    # Fully uncovered: neither track nor artist mapped to MB.
    elif mb == "sense_cobertura":
        qs = qs.filter(mbrainz_confirmed__isnull=True).filter(
            Q(artista__musicbrainz_id__isnull=True) | Q(artista__musicbrainz_id="")
        )

    # Whisper preview filter: lets the dashboard link to the
    # forever-pending ("sense preview") slice without conflating it
    # with the actually-processable queue.
    preview = request.GET.get("preview", "")
    if preview == "no":
        qs = qs.filter(Q(preview_url="") | Q(preview_url__isnull=True))
    elif preview == "si":
        qs = qs.exclude(preview_url="").exclude(preview_url__isnull=True)

    # Refinement on the whisper bucket: separate "pendent amb preview"
    # (analitzable) from "pendent sense preview" (perpetual).
    if whisper == "pendent_amb_preview":
        qs = (
            qs.filter(whisper_processat_at__isnull=True)
            .exclude(preview_url="")
            .exclude(preview_url__isnull=True)
        )
    elif whisper == "pendent_sense_preview":
        qs = qs.filter(whisper_processat_at__isnull=True).filter(
            Q(preview_url="") | Q(preview_url__isnull=True)
        )
    # Recent-release shortcut: "últims 7 dies" + "últims 30 dies".
    # Driven by the staff cançons page so the operator can spot
    # newly released tracks without typing dates manually.
    recent = (request.GET.get("recent") or "").strip()
    if recent in ("7", "30", "90"):
        import datetime

        cutoff = datetime.date.today() - datetime.timedelta(days=int(recent))
        qs = qs.filter(data_llancament__gte=cutoff)

    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(
            _canco_norm=_unaccent_field("nom"),
            _artista_norm=_unaccent_field("artista__nom"),
        ).filter(
            Q(_canco_norm__contains=_normalize_search_term(cerca))
            | Q(_artista_norm__contains=_normalize_search_term(cerca))
        )
    # Scope to a single artist — includes main artist AND collaborator
    # participations so the "X cançons verificades" drill-down from the
    # pendents page matches the nb_verif count exactly.
    artista_pk = request.GET.get("artista_pk", "")
    if artista_pk:
        try:
            pk = int(artista_pk)
            qs = qs.filter(Q(artista_id=pk) | Q(artistes_col__pk=pk)).distinct()
        except ValueError:
            pass
    # Sorting: `sort` accepts the same allow-list as the Django staff
    # view used to, prefixed with `-` for descending. Default keeps the
    # ML triage order so new users land on the highest-confidence work.
    sort_map = {
        "ml_confianca": "ml_confianca",
        "nom": "nom",
        "data_llancament": "data_llancament",
        "artista": "artista__nom",
        "album": "album__nom",
        "isrc": "isrc",
    }
    sort_raw = (request.GET.get("sort") or "-ml_confianca").strip()
    direction = ""
    key = sort_raw
    if sort_raw.startswith("-"):
        direction = "-"
        key = sort_raw[1:]
    if key not in sort_map:
        direction, key = "-", "ml_confianca"
    qs = qs.order_by(f"{direction}{sort_map[key]}", "nom")
    page, meta = _paginate(qs, request)
    homset = noms_amb_homonims()
    return Response(
        {"results": [_canco_row(c, homset) for c in page.object_list], **meta}
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def cancons_accio(request: Request) -> Response:
    """Bulk aprovar / rebutjar. Body: {action, ids, motiu}."""
    data = request.data or {}
    action = data.get("action", "")
    ids = data.get("ids") or []
    if not ids:
        return Response({"error": "No has seleccionat cap cançó."}, status=400)
    qs = Canco.objects.filter(pk__in=ids).select_related("artista", "album")

    if action == "aprovar":
        with transaction.atomic():
            for c in qs:
                aprovar_canco(c)
                log_staff_action(request, "canco_aprovar", target=c)
        recalcular_ml_si_cal()
        return Response({"ok": True, "n": qs.count()})

    motiu = data.get("motiu", "")
    if motiu not in MOTIUS_VALIDS:
        return Response({"error": "Motiu invàlid."}, status=400)

    msgs: list[str] = []
    if action == "rebutjar":
        with transaction.atomic():
            if motiu == "desvincular_artista":
                artista_ids = set(qs.values_list("artista_id", flat=True))
                for a in Artista.objects.filter(pk__in=artista_ids):
                    n = rebutjar_artista(a, motiu)
                    log_staff_action(
                        request,
                        "artista_rebutjar",
                        target=a,
                        motiu=motiu,
                        cancons_afectades=n,
                    )
                    msgs.append(f"{n} cançons de {a.nom}")
            elif motiu == "desvincular_album":
                album_ids = set(qs.values_list("album_id", flat=True))
                for al in Album.objects.filter(pk__in=album_ids):
                    n = rebutjar_album(al, motiu)
                    log_staff_action(
                        request,
                        "canco_rebutjar_album",
                        target=al,
                        motiu=motiu,
                        cancons_afectades=n,
                    )
                    msgs.append(f"{n} cançons de l'àlbum {al.nom}")
            else:
                for c in qs:
                    rebutjar_canco(c, motiu)
                    log_staff_action(request, "canco_rebutjar", target=c, motiu=motiu)
                msgs.append(f"{qs.count()} cançons rebutjades")
        recalcular_ml_si_cal()
        return Response({"ok": True, "msg": "; ".join(msgs)})

    return Response({"error": "Acció desconeguda."}, status=400)


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def canco_detail(request: Request, pk: int) -> Response:
    canco = get_object_or_404(Canco.objects.select_related("artista", "album"), pk=pk)
    if request.method == "PATCH":
        data = request.data or {}
        if "nom" in data:
            canco.nom = (data.get("nom") or "").strip()
        if "isrc" in data:
            canco.isrc = (data.get("isrc") or "").strip()
        if "lastfm_nom" in data:
            canco.lastfm_nom = (data.get("lastfm_nom") or "").strip()
        if "verificada" in data:
            canco.verificada = bool(data["verificada"])
        if "activa" in data:
            canco.activa = bool(data["activa"])
        if "data_llancament" in data:
            raw = (data.get("data_llancament") or "").strip()
            # parse_date → date | None; avoids the "str has no isoformat"
            # 500 when the response serializer re-reads the field after save.
            canco.data_llancament = parse_date(raw) if raw else None
        if "deezer_id" in data:
            raw = str(data.get("deezer_id") or "").strip()
            if raw:
                try:
                    canco.deezer_id = int(raw)
                except ValueError:
                    return Response({"error": "Deezer ID invàlid."}, status=400)
            else:
                canco.deezer_id = None
        # Manual Spotify track id (store-and-trust: format validated, no
        # API call — see `_spotify_url.parse_track_id`). Empty value →
        # clear back to `not_attempted` so auto-enrichment can retry. A
        # non-empty value is accepted ONLY when the Canço has no Spotify
        # id yet (auto or manual); to replace one, clear it first. The
        # validated action is applied after the main save so a parse
        # error short-circuits before any write.
        spotify_action: tuple[str, str] | None = None
        if "spotify_url" in data:
            raw = (data.get("spotify_url") or "").strip()
            if not raw:
                spotify_action = ("clear", "")
            else:
                try:
                    track_id = parse_track_id(raw)
                except SpotifyUrlError as exc:
                    return Response({"error": str(exc)}, status=400)
                sm_existing = getattr(canco, "spotify", None)
                if sm_existing is not None and sm_existing.spotify_id:
                    return Response(
                        {
                            "error": (
                                "Aquesta cançó ja té un id de Spotify. "
                                "Buida'l primer per substituir-lo."
                            )
                        },
                        status=400,
                    )
                # Collision: a Spotify track id must not point at two
                # cançons. Clear 400 (the legacy-unique IntegrityError is
                # kept below as a race-condition fallback). Check the
                # canonical SpotifyMetadata table and the legacy column.
                clash = (
                    SpotifyMetadata.objects.filter(spotify_id=track_id)
                    .exclude(canco_id=canco.pk)
                    .values_list("canco_id", "canco__nom")
                    .first()
                ) or (
                    Canco.objects.filter(spotify_id=track_id)
                    .exclude(pk=canco.pk)
                    .values_list("pk", "nom")
                    .first()
                )
                if clash:
                    return Response(
                        {
                            "error": (
                                f"Aquest id de Spotify ja està assignat "
                                f"a la cançó #{clash[0]} ({clash[1]})."
                            )
                        },
                        status=400,
                    )
                spotify_action = ("set", track_id)
        # Manual YouTube video (store-and-trust: format only, no quota
        # spent — see `_youtube_url`). Two destinations, decided by what
        # the song already has, mirroring how staff pasting a Topic
        # channel is adopted on the artist side:
        #   · no Art Track yet → it becomes the Art Track pointer, and
        #     the song starts being measured tonight;
        #   · already has one  → it is added as an extra lane, which is
        #     what a videoclip on the band's own channel is.
        # Empty value clears the pointer only. Lanes are not removable
        # on purpose: discovery re-creates them from the title match, so
        # a delete button would undo itself overnight — a wrong lane is
        # a `_conte_titol` bug, not a data-entry one.
        youtube_action: tuple[str, str] | None = None
        if "youtube_url" in data:
            raw = (data.get("youtube_url") or "").strip()
            if not raw:
                youtube_action = ("clear", "")
            else:
                try:
                    video_id = parse_video_id(raw)
                except YoutubeUrlError as exc:
                    return Response({"error": str(exc)}, status=400)
                youtube_action = (
                    "carril" if canco.youtube_video_id else "principal",
                    video_id,
                )
        # Third state: "s'ha buscat i no en té". Final answer, and the
        # only thing that takes a song out of the daily action list
        # without a video.
        if "youtube_revisat" in data:
            canco.youtube_revisat = bool(data["youtube_revisat"])
        # Reassign to a different artist (when staff spots a mis-attribution).
        if "artista_pk" in data:
            raw = data.get("artista_pk")
            if raw in (None, ""):
                return Response({"error": "L'artista és obligatori."}, status=400)
            try:
                new_artista = Artista.objects.get(pk=int(raw))
            except (ValueError, Artista.DoesNotExist):
                return Response({"error": "Artista no trobat."}, status=404)
            if canco.artista_id != new_artista.pk:
                old_nom = canco.artista.nom if canco.artista else ""
                canco.artista = new_artista
                log_staff_action(
                    request,
                    "canco_edit",
                    target=canco,
                    field="artista",
                    old_artista=old_nom,
                    new_artista=new_artista.nom,
                )
        canco.save()
        # Apply the validated manual Spotify action. Writes the canonical
        # `SpotifyMetadata.spotify_id` (what Process A reads) and mirrors
        # the legacy `Canco.spotify_id` best-effort.
        if spotify_action is not None:
            verb, track_id = spotify_action
            sm, _ = SpotifyMetadata.objects.get_or_create(canco=canco)
            if verb == "set":
                # id-first: store the id + mark manual, leave
                # `enriched_at = NULL` so Process B's hydration phase
                # picks it up next run and fills spotify_artist_id + the
                # rest from the id (no /search). Reset spotify_artist_id
                # so a previously-hydrated row re-hydrates cleanly. The
                # canonical write and the legacy-unique mirror share one
                # savepoint: the pre-check above rejects collisions, and
                # this catches the rare race where another canço grabbed
                # the id in between — the IntegrityError rolls back BOTH
                # writes and we return the same clear 400, never a 500.
                try:
                    with transaction.atomic():
                        sm.spotify_id = track_id
                        sm.spotify_artist_id = ""
                        sm.enrichment_status = SpotifyMetadata.STATUS_MANUAL
                        sm.enriched_at = None
                        sm.save(
                            update_fields=[
                                "spotify_id",
                                "spotify_artist_id",
                                "enrichment_status",
                                "enriched_at",
                                "updated_at",
                            ]
                        )
                        Canco.objects.filter(pk=canco.pk).update(spotify_id=track_id)
                except IntegrityError:
                    return Response(
                        {
                            "error": (
                                "Aquest id de Spotify acaba de ser assignat "
                                "a una altra cançó. Torna-ho a provar."
                            )
                        },
                        status=400,
                    )
                log_staff_action(
                    request,
                    "canco_edit",
                    target=canco,
                    field="spotify_manual",
                    spotify_id=track_id,
                )
            else:  # clear → re-enrichable
                sm.spotify_id = ""
                sm.enrichment_status = SpotifyMetadata.STATUS_NOT_ATTEMPTED
                sm.enriched_at = None
                sm.save(
                    update_fields=[
                        "spotify_id",
                        "enrichment_status",
                        "enriched_at",
                        "updated_at",
                    ]
                )
                Canco.objects.filter(pk=canco.pk).update(spotify_id=None)
                log_staff_action(
                    request,
                    "canco_edit",
                    target=canco,
                    field="spotify_manual",
                    spotify_id="",
                )
            # Refresh the cached reverse relation so the response
            # serializer reflects the row we just wrote (the earlier
            # `getattr(canco, "spotify", …)` may have cached its absence).
            canco.spotify = sm
        # Apply the validated manual YouTube action.
        if youtube_action is not None:
            verb, video_id = youtube_action
            if verb == "principal":
                canco.youtube_video_id = video_id
                canco.youtube_match = Canco.MATCH_MANUAL
                canco.youtube_matched_at = timezone.now()
                # Answered: a song with a video is no longer a task.
                canco.youtube_revisat = True
                canco.save(
                    update_fields=[
                        "youtube_video_id",
                        "youtube_match",
                        "youtube_matched_at",
                        "youtube_revisat",
                    ]
                )
            elif verb == "carril":
                CancoYouTubeVideo.objects.get_or_create(
                    canco=canco, video_id=video_id, defaults={"titol": ""}
                )
                if not canco.youtube_revisat:
                    canco.youtube_revisat = True
                    canco.save(update_fields=["youtube_revisat"])
            else:  # clear → discovery may fill it again
                canco.youtube_video_id = ""
                canco.youtube_match = ""
                canco.youtube_matched_at = None
                canco.save(
                    update_fields=[
                        "youtube_video_id",
                        "youtube_match",
                        "youtube_matched_at",
                    ]
                )
            log_staff_action(
                request,
                "canco_edit",
                target=canco,
                field="youtube_manual",
                video_id=video_id,
                carril=verb,
            )
        # Replace the collaborator list (artistes_col ManyToMany). Expects
        # an array of Artista PKs. A check in Canco.clean() rejects the
        # D5 case where the main artist also appears as a collaborator;
        # we mirror it here so the PATCH surfaces a 400 instead of an
        # opaque IntegrityError.
        if "artistes_col_pks" in data:
            raw_list = data.get("artistes_col_pks") or []
            try:
                want_pks = [int(x) for x in raw_list if str(x).strip()]
            except (TypeError, ValueError):
                return Response(
                    {"error": "artistes_col_pks ha de ser una llista d'enters."},
                    status=400,
                )
            if canco.artista_id in want_pks:
                return Response(
                    {
                        "error": (
                            "L'artista principal no pot ser també "
                            "col·laborador de la mateixa cançó."
                        )
                    },
                    status=400,
                )
            found = list(Artista.objects.filter(pk__in=want_pks))
            if len(found) != len(set(want_pks)):
                return Response(
                    {"error": "Algun dels artistes col·laboradors no existeix."},
                    status=404,
                )
            canco.artistes_col.set(found)
        log_staff_action(request, "canco_edit", target=canco)
    return Response(_canco_row(canco))
