"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Cançons — track management
# ═════════════════════════════════════════════════════════════════════════


def _canco_row(c) -> dict:
    return {
        "pk": c.pk,
        "nom": c.nom,
        "slug": c.slug,
        "verificada": c.verificada,
        "activa": c.activa,
        "ml_classe": c.ml_classe or "",
        "ml_confianca": c.ml_confianca,
        "isrc": c.isrc or "",
        "deezer_id": c.deezer_id,
        "data_llancament": (
            c.data_llancament.isoformat() if c.data_llancament else None
        ),
        "lastfm_nom": c.lastfm_nom or "",
        "whisper_lang": c.whisper_lang or "",
        "mb_recording_id": c.mb_recording_id or "",
        "mb_work_id": c.mb_work_id or "",
        "mb_lyrics_language": c.mb_lyrics_language or "",
        "mbrainz_confirmed": c.mbrainz_confirmed,
        "artista": (
            {
                "pk": c.artista_id,
                "nom": c.artista.nom,
                "aprovat": c.artista.aprovat,
                "pendent_review": c.artista.pendent_review,
                "musicbrainz_id": c.artista.musicbrainz_id or "",
                "mb_end_date": (
                    c.artista.mb_end_date.isoformat() if c.artista.mb_end_date else None
                ),
            }
            if c.artista
            else None
        ),
        "album": (
            {"pk": c.album_id, "nom": c.album.nom, "slug": c.album.slug}
            if c.album
            else None
        ),
        # artistes_col is a ManyToMany on Canco. Expose the list on every
        # row so staff can see collabs at a glance in the edit page.
        "artistes_col": [
            {"pk": a.pk, "nom": a.nom, "slug": a.slug, "aprovat": a.aprovat}
            for a in c.artistes_col.all()
        ],
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def cancons_list(request: Request) -> Response:
    qs = Canco.objects.select_related("artista", "album")
    verificada = request.GET.get("verificada", "0")
    if verificada == "0":
        qs = qs.filter(verificada=False, activa=True)
    elif verificada == "1":
        qs = qs.filter(verificada=True)
    ml_classe = request.GET.get("ml_classe", "")
    if ml_classe in ("A", "B", "C"):
        qs = qs.filter(ml_classe=ml_classe)
    whisper = request.GET.get("whisper", "")
    if whisper == "ca":
        qs = qs.filter(whisper_lang="ca")
    elif whisper == "no_ca":
        qs = qs.filter(whisper_processat_at__isnull=False).exclude(whisper_lang="ca")
    elif whisper == "pendent":
        qs = qs.filter(whisper_processat_at__isnull=True)
    # "Sense Deezer" — a verified track without a deezer_id is the
    # legacy/mis-ingest case worth auditing. `no` surfaces only those,
    # `si` only the tracks that do have an ID (rarely needed, handy
    # for QA).
    deezer = request.GET.get("deezer", "")
    if deezer == "no":
        qs = qs.filter(deezer_id__isnull=True)
    elif deezer == "si":
        qs = qs.filter(deezer_id__isnull=False)
    # MusicBrainz filters: confirmat (MB attests ownership), no_confirmat
    # (synced but didn't match), desconegut (not yet reconciled), cat
    # (Work.language == 'cat'), artista_dissolt (main artist has mb_end_date).
    mb = request.GET.get("mb", "")
    if mb == "confirmat":
        qs = qs.filter(mbrainz_confirmed=True)
    elif mb == "no_confirmat":
        qs = qs.filter(mbrainz_confirmed=False)
    elif mb == "desconegut":
        qs = qs.filter(mbrainz_confirmed__isnull=True)
    elif mb == "cat":
        qs = qs.filter(mb_lyrics_language="cat")
    elif mb == "artista_dissolt":
        qs = qs.filter(artista__mb_end_date__isnull=False)
    # Track not (yet) MB-confirmed but its main artist already has an
    # MBID — candidates for a targeted MB sync.
    elif mb == "artista_amb_mbid":
        qs = (
            qs.filter(mbrainz_confirmed__isnull=True)
            .exclude(artista__musicbrainz_id__isnull=True)
            .exclude(artista__musicbrainz_id="")
        )
    # Fully uncovered: neither track nor artist mapped to MB.
    elif mb == "sense_cobertura":
        qs = qs.filter(mbrainz_confirmed__isnull=True).filter(
            Q(artista__musicbrainz_id__isnull=True) | Q(artista__musicbrainz_id="")
        )

    # Whisper preview filter: lets the dashboard link to the
    # forever-pending ("sense preview") slice without conflating it
    # with the actually-processable queue.
    preview = request.GET.get("preview", "")
    if preview == "no":
        qs = qs.filter(Q(preview_url="") | Q(preview_url__isnull=True))
    elif preview == "si":
        qs = qs.exclude(preview_url="").exclude(preview_url__isnull=True)

    # Refinement on the whisper bucket: separate "pendent amb preview"
    # (analitzable) from "pendent sense preview" (perpetual).
    if whisper == "pendent_amb_preview":
        qs = (
            qs.filter(whisper_processat_at__isnull=True)
            .exclude(preview_url="")
            .exclude(preview_url__isnull=True)
        )
    elif whisper == "pendent_sense_preview":
        qs = qs.filter(whisper_processat_at__isnull=True).filter(
            Q(preview_url="") | Q(preview_url__isnull=True)
        )
    # Recent-release shortcut: "últims 7 dies" + "últims 30 dies".
    # Driven by the staff cançons page so the operator can spot
    # newly released tracks without typing dates manually.
    recent = (request.GET.get("recent") or "").strip()
    if recent in ("7", "30", "90"):
        import datetime

        cutoff = datetime.date.today() - datetime.timedelta(days=int(recent))
        qs = qs.filter(data_llancament__gte=cutoff)

    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(
            _canco_norm=_unaccent_field("nom"),
            _artista_norm=_unaccent_field("artista__nom"),
        ).filter(
            Q(_canco_norm__contains=_normalize_search_term(cerca))
            | Q(_artista_norm__contains=_normalize_search_term(cerca))
        )
    # Scope to a single artist — includes main artist AND collaborator
    # participations so the "X cançons verificades" drill-down from the
    # pendents page matches the nb_verif count exactly.
    artista_pk = request.GET.get("artista_pk", "")
    if artista_pk:
        try:
            pk = int(artista_pk)
            qs = qs.filter(Q(artista_id=pk) | Q(artistes_col__pk=pk)).distinct()
        except ValueError:
            pass
    # Sorting: `sort` accepts the same allow-list as the Django staff
    # view used to, prefixed with `-` for descending. Default keeps the
    # ML triage order so new users land on the highest-confidence work.
    sort_map = {
        "ml_confianca": "ml_confianca",
        "nom": "nom",
        "data_llancament": "data_llancament",
        "artista": "artista__nom",
        "album": "album__nom",
        "isrc": "isrc",
    }
    sort_raw = (request.GET.get("sort") or "-ml_confianca").strip()
    direction = ""
    key = sort_raw
    if sort_raw.startswith("-"):
        direction = "-"
        key = sort_raw[1:]
    if key not in sort_map:
        direction, key = "-", "ml_confianca"
    qs = qs.order_by(f"{direction}{sort_map[key]}", "nom")
    page, meta = _paginate(qs, request)
    return Response({"results": [_canco_row(c) for c in page.object_list], **meta})


@api_view(["POST"])
@permission_classes([IsStaff])
def cancons_accio(request: Request) -> Response:
    """Bulk aprovar / rebutjar. Body: {action, ids, motiu}."""
    data = request.data or {}
    action = data.get("action", "")
    ids = data.get("ids") or []
    if not ids:
        return Response({"error": "No has seleccionat cap cançó."}, status=400)
    qs = Canco.objects.filter(pk__in=ids).select_related("artista", "album")

    if action == "aprovar":
        with transaction.atomic():
            for c in qs:
                aprovar_canco(c)
                log_staff_action(request, "canco_aprovar", target=c)
        recalcular_ml_si_cal()
        return Response({"ok": True, "n": qs.count()})

    motiu = data.get("motiu", "")
    if motiu not in MOTIUS_VALIDS:
        return Response({"error": "Motiu invàlid."}, status=400)

    msgs: list[str] = []
    if action == "rebutjar":
        with transaction.atomic():
            if motiu == "artista_incorrecte":
                artista_ids = set(qs.values_list("artista_id", flat=True))
                for a in Artista.objects.filter(pk__in=artista_ids):
                    n = rebutjar_artista(a, motiu)
                    log_staff_action(
                        request,
                        "artista_rebutjar",
                        target=a,
                        motiu=motiu,
                        cancons_afectades=n,
                    )
                    msgs.append(f"{n} cançons de {a.nom}")
            elif motiu == "album_incorrecte":
                album_ids = set(qs.values_list("album_id", flat=True))
                for al in Album.objects.filter(pk__in=album_ids):
                    n = rebutjar_album(al, motiu)
                    log_staff_action(
                        request,
                        "canco_rebutjar_album",
                        target=al,
                        motiu=motiu,
                        cancons_afectades=n,
                    )
                    msgs.append(f"{n} cançons de l'àlbum {al.nom}")
            else:
                for c in qs:
                    rebutjar_canco(c, motiu)
                    log_staff_action(request, "canco_rebutjar", target=c, motiu=motiu)
                msgs.append(f"{qs.count()} cançons rebutjades")
        recalcular_ml_si_cal()
        return Response({"ok": True, "msg": "; ".join(msgs)})

    return Response({"error": "Acció desconeguda."}, status=400)


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def canco_detail(request: Request, pk: int) -> Response:
    canco = get_object_or_404(Canco.objects.select_related("artista", "album"), pk=pk)
    if request.method == "PATCH":
        data = request.data or {}
        if "nom" in data:
            canco.nom = (data.get("nom") or "").strip()
        if "isrc" in data:
            canco.isrc = (data.get("isrc") or "").strip()
        if "lastfm_nom" in data:
            canco.lastfm_nom = (data.get("lastfm_nom") or "").strip()
        if "verificada" in data:
            canco.verificada = bool(data["verificada"])
        if "activa" in data:
            canco.activa = bool(data["activa"])
        if "data_llancament" in data:
            raw = (data.get("data_llancament") or "").strip()
            # parse_date → date | None; avoids the "str has no isoformat"
            # 500 when the response serializer re-reads the field after save.
            canco.data_llancament = parse_date(raw) if raw else None
        if "deezer_id" in data:
            raw = str(data.get("deezer_id") or "").strip()
            if raw:
                try:
                    canco.deezer_id = int(raw)
                except ValueError:
                    return Response({"error": "Deezer ID invàlid."}, status=400)
            else:
                canco.deezer_id = None
        # Reassign to a different artist (when staff spots a mis-attribution).
        if "artista_pk" in data:
            raw = data.get("artista_pk")
            if raw in (None, ""):
                return Response({"error": "L'artista és obligatori."}, status=400)
            try:
                new_artista = Artista.objects.get(pk=int(raw))
            except (ValueError, Artista.DoesNotExist):
                return Response({"error": "Artista no trobat."}, status=404)
            if canco.artista_id != new_artista.pk:
                old_nom = canco.artista.nom if canco.artista else ""
                canco.artista = new_artista
                log_staff_action(
                    request,
                    "canco_edit",
                    target=canco,
                    field="artista",
                    old_artista=old_nom,
                    new_artista=new_artista.nom,
                )
        canco.save()
        # Replace the collaborator list (artistes_col ManyToMany). Expects
        # an array of Artista PKs. A check in Canco.clean() rejects the
        # D5 case where the main artist also appears as a collaborator;
        # we mirror it here so the PATCH surfaces a 400 instead of an
        # opaque IntegrityError.
        if "artistes_col_pks" in data:
            raw_list = data.get("artistes_col_pks") or []
            try:
                want_pks = [int(x) for x in raw_list if str(x).strip()]
            except (TypeError, ValueError):
                return Response(
                    {"error": "artistes_col_pks ha de ser una llista d'enters."},
                    status=400,
                )
            if canco.artista_id in want_pks:
                return Response(
                    {
                        "error": (
                            "L'artista principal no pot ser també "
                            "col·laborador de la mateixa cançó."
                        )
                    },
                    status=400,
                )
            found = list(Artista.objects.filter(pk__in=want_pks))
            if len(found) != len(set(want_pks)):
                return Response(
                    {"error": "Algun dels artistes col·laboradors no existeix."},
                    status=404,
                )
            canco.artistes_col.set(found)
        log_staff_action(request, "canco_edit", target=canco)
    return Response(_canco_row(canco))
