"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from music.audit import log_staff_action
from ranking.models import (
    ConfiguracioGlobal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff

# ═════════════════════════════════════════════════════════════════════════
# Configuració global
# ═════════════════════════════════════════════════════════════════════════


# Field-name patterns we treat as secret. Anything matching is masked
# in the read response and recorded as `***` in the audit diff so a
# future config field added with a sensitive name doesn't leak by
# accident (the model is reflection-iterated). May-2026 audit fix.
_SECRET_PATTERNS = ("_token", "_secret", "_password", "_key", "_apikey")


def _is_secret_field(name: str) -> bool:
    n = name.lower()
    return any(p in n for p in _SECRET_PATTERNS)


def _mask_secret(value):
    s = str(value or "")
    if not s:
        return ""
    if len(s) <= 8:
        return "•" * len(s)
    return f"{s[:4]}…{s[-4:]}"


# Sectioning of the (auto-reflected) ConfiguracioGlobal fields so the SPA can
# group them. Same view, just labelled. Order here is the display order. Fields
# not listed fall through to "Altres" (e.g. a future field, or secrets).
SECTION_RANKINGS = "Rànquing i fórmules"
SECTION_SOFTCAP = "Soft cap (outliers)"
SECTION_EDITORIAL = "Editorial"
SECTION_DISTRIBUCIO = "Distribució i canals"
SECTION_COLABORADORS = "Col·laboradors IG"
SECTION_FIABILITAT = "Fiabilitat i certificats"
SECTION_ALTRES = "Altres"

_SECTION_MAP = {
    # F — reliability watches (tq-health)
    "tls_endpoints_vigilats": SECTION_FIABILITAT,
    "tls_avis_dies": SECTION_FIABILITAT,
    # A — ranking / formula
    "exponent_penalitzacio_antiguitat": SECTION_RANKINGS,
    "penalitzacio_album_per_canco": SECTION_RANKINGS,
    "penalitzacio_artista_per_canco": SECTION_RANKINGS,
    "coeficient_penalitzacio_top": SECTION_RANKINGS,
    "min_cancons_ranking_propi": SECTION_RANKINGS,
    "min_escoltes_top": SECTION_RANKINGS,
    "ppcc_penalitzacio_per_posicio": SECTION_RANKINGS,
    # soft-cap scoring (all tunables together)
    "soft_cap_actiu": SECTION_SOFTCAP,
    "soft_cap_multiplicador": SECTION_SOFTCAP,
    "soft_cap_floor_escoltes": SECTION_SOFTCAP,
    "soft_cap_base_top_n": SECTION_SOFTCAP,
    # D — editorial
    "editorial_veu": SECTION_EDITORIAL,
    "landing_editorial_veu": SECTION_EDITORIAL,
    "novetats_stories_per_pagina": SECTION_EDITORIAL,
    "feed_artwork_actiu": SECTION_EDITORIAL,
    "feed_artwork_mosaic_max": SECTION_EDITORIAL,
    "moviment_actiu": SECTION_EDITORIAL,
    "moviment_pujada_minima": SECTION_EDITORIAL,
    # B — distribution / channels (managed primarily in the distribution
    # cockpit; surfaced here read/write because the model is reflected).
    "newsletter_publicacio_pont_actiu": SECTION_DISTRIBUCIO,
    "distribucio_activa": SECTION_DISTRIBUCIO,
    "instagram_actiu": SECTION_DISTRIBUCIO,
    "mastodon_actiu": SECTION_DISTRIBUCIO,
    "bluesky_actiu": SECTION_DISTRIBUCIO,
    "telegram_actiu": SECTION_DISTRIBUCIO,
    "newsletter_actiu": SECTION_DISTRIBUCIO,
    "rss_actiu": SECTION_DISTRIBUCIO,
    "delay_instagram_min": SECTION_DISTRIBUCIO,
    "delay_mastodon_min": SECTION_DISTRIBUCIO,
    "delay_bluesky_min": SECTION_DISTRIBUCIO,
    "delay_telegram_min": SECTION_DISTRIBUCIO,
    "delay_newsletter_min": SECTION_DISTRIBUCIO,
    # IG collaborator invitations (ADR-0015). Own visible section (the
    # distribution section is hidden here, so these live separately so
    # staff can flip the master flag + tune slots/cooldowns).
    "ig_collaboradors_actiu": SECTION_COLABORADORS,
    "ig_collab_slots_total": SECTION_COLABORADORS,
    "ig_collab_slots_acceptats": SECTION_COLABORADORS,
    "ig_collab_cooldown_a_dies": SECTION_COLABORADORS,
    "ig_collab_cooldown_c_dies": SECTION_COLABORADORS,
}

# Stable display order of the sections in the SPA.
SECTION_ORDER = [
    SECTION_RANKINGS,
    SECTION_SOFTCAP,
    SECTION_EDITORIAL,
    SECTION_COLABORADORS,
    SECTION_FIABILITAT,
    SECTION_DISTRIBUCIO,
    SECTION_ALTRES,
]


# Sections the Config view does NOT surface. Distribution lives in the
# distribution cockpit / matrix (`/staff/social/*`), so it's hidden here —
# Configuració is rankings + soft cap + editorial. The fields stay on the
# model and `pot_publicar` / the cockpit are unchanged; they just don't appear
# (or accept writes) via `/staff/configuracio/`.
_HIDDEN_SECTIONS = {SECTION_DISTRIBUCIO}


def _section_for(name: str) -> str:
    return _SECTION_MAP.get(name, SECTION_ALTRES)


def _is_config_visible(name: str) -> bool:
    """False for fields whose section is hidden from the Config view."""
    return _section_for(name) not in _HIDDEN_SECTIONS


def _config_fields(config):
    out = []
    for field in ConfiguracioGlobal._meta.get_fields():
        if (
            hasattr(field, "attname")
            and field.attname != "id"
            and _is_config_visible(field.attname)
        ):
            raw_value = getattr(config, field.attname)
            display_value = (
                _mask_secret(raw_value)
                if _is_secret_field(field.attname)
                else raw_value
            )
            out.append(
                {
                    "name": field.attname,
                    "label": field.attname.replace("_", " ").title(),
                    "value": display_value,
                    "is_secret": _is_secret_field(field.attname),
                    "help": getattr(field, "help_text", "") or "",
                    "type": field.get_internal_type(),
                    "section": _section_for(field.attname),
                }
            )
    return out


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def configuracio(request: Request) -> Response:
    config = ConfiguracioGlobal.load()
    if request.method == "PATCH":
        data = request.data or {}
        # Only the visible (non-distribution) fields are writable here; the
        # distribution switches are owned by the cockpit/matrix endpoints.
        fields = [
            f
            for f in ConfiguracioGlobal._meta.get_fields()
            if hasattr(f, "attname")
            and f.attname != "id"
            and _is_config_visible(f.attname)
        ]
        before = {f.attname: getattr(config, f.attname) for f in fields}
        for f in fields:
            if f.attname not in data:
                continue
            raw = str(data.get(f.attname) or "").strip()
            if raw == "":
                continue
            try:
                setattr(config, f.attname, type(getattr(config, f.attname))(raw))
            except (TypeError, ValueError):
                return Response(
                    {"error": f"Valor invàlid per {f.attname}."}, status=400
                )
        try:
            config.save()
        except ValidationError as exc:
            return Response(
                {"error": "Validació fallada.", "details": exc.message_dict},
                status=400,
            )
        after = {f.attname: getattr(config, f.attname) for f in fields}
        # Mask secret fields in the audit log diff so the value never
        # lands in StaffAuditLog plaintext (would survive log
        # retention + backups). The fact that the field changed is
        # still recorded — only the values are obscured.
        diff = {
            n: {
                "before": ("***" if _is_secret_field(n) else str(before[n])),
                "after": ("***" if _is_secret_field(n) else str(after[n])),
            }
            for n in before
            if str(before[n]) != str(after[n])
        }
        if diff:
            log_staff_action(
                request,
                "config_update",
                target=config,
                changed_fields=list(diff.keys()),
                diff=diff,
            )
    fields = _config_fields(config)
    present = {f["section"] for f in fields}
    sections = [s for s in SECTION_ORDER if s in present]
    return Response({"fields": fields, "sections": sections})
