"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Configuració global
# ═════════════════════════════════════════════════════════════════════════


# Field-name patterns we treat as secret. Anything matching is masked
# in the read response and recorded as `***` in the audit diff so a
# future config field added with a sensitive name doesn't leak by
# accident (the model is reflection-iterated). May-2026 audit fix.
_SECRET_PATTERNS = ("_token", "_secret", "_password", "_key", "_apikey")


def _is_secret_field(name: str) -> bool:
    n = name.lower()
    return any(p in n for p in _SECRET_PATTERNS)


def _mask_secret(value):
    s = str(value or "")
    if not s:
        return ""
    if len(s) <= 8:
        return "•" * len(s)
    return f"{s[:4]}…{s[-4:]}"


def _config_fields(config):
    out = []
    for field in ConfiguracioGlobal._meta.get_fields():
        if hasattr(field, "attname") and field.attname != "id":
            raw_value = getattr(config, field.attname)
            display_value = (
                _mask_secret(raw_value)
                if _is_secret_field(field.attname)
                else raw_value
            )
            out.append(
                {
                    "name": field.attname,
                    "label": field.attname.replace("_", " ").title(),
                    "value": display_value,
                    "is_secret": _is_secret_field(field.attname),
                    "help": getattr(field, "help_text", "") or "",
                    "type": field.get_internal_type(),
                }
            )
    return out


@api_view(["GET", "PATCH"])
@permission_classes([IsStaff])
def configuracio(request: Request) -> Response:
    config = ConfiguracioGlobal.load()
    if request.method == "PATCH":
        data = request.data or {}
        fields = [
            f
            for f in ConfiguracioGlobal._meta.get_fields()
            if hasattr(f, "attname") and f.attname != "id"
        ]
        before = {f.attname: getattr(config, f.attname) for f in fields}
        for f in fields:
            if f.attname not in data:
                continue
            raw = str(data.get(f.attname) or "").strip()
            if raw == "":
                continue
            try:
                setattr(config, f.attname, type(getattr(config, f.attname))(raw))
            except (TypeError, ValueError):
                return Response(
                    {"error": f"Valor invàlid per {f.attname}."}, status=400
                )
        try:
            config.save()
        except ValidationError as exc:
            return Response(
                {"error": "Validació fallada.", "details": exc.message_dict},
                status=400,
            )
        after = {f.attname: getattr(config, f.attname) for f in fields}
        # Mask secret fields in the audit log diff so the value never
        # lands in StaffAuditLog plaintext (would survive log
        # retention + backups). The fact that the field changed is
        # still recorded — only the values are obscured.
        diff = {
            n: {
                "before": ("***" if _is_secret_field(n) else str(before[n])),
                "after": ("***" if _is_secret_field(n) else str(after[n])),
            }
            for n in before
            if str(before[n]) != str(after[n])
        }
        if diff:
            log_staff_action(
                request,
                "config_update",
                target=config,
                changed_fields=list(diff.keys()),
                diff=diff,
            )
    return Response({"fields": _config_fields(config)})
