"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Estat del sistema — visual dashboard at /staff/estat
# ═════════════════════════════════════════════════════════════════════════


# Cron metadata per command — single source of truth lives in
# `deploy/cron-meta.json` so a new cron is added in ONE place and
# both the staff dashboard (this module) and `bin/tq-health` pick it
# up automatically. Caught 2026-05-08: `detectar_anomalies_senyal`
# was added to `cron.topquaranta` + this module but missing from the
# tq-health hardcoded list, so the watchdog ignored it. JSON-source
# closes that drift.
#
# Fields per entry:
#   frequency_label   — Catalan, human-readable cron schedule
#   max_age_hours     — when last_run > this, surface as STALE/STUCK
#   skip_concern      — `consecutive_skips` value at which a still-
#                       running instance becomes suspicious. Hourly
#                       crons tolerate 1–2 long-runs; daily ones
#                       shouldn't skip ever (the next tick is 24 h
#                       away).
#   silenced (opt)    — True swallows watchdog email; still red on
#                       dashboard.
#   silenced_reason   — string shown next to the silenced row.
def _load_cron_meta() -> dict[str, dict]:
    import json
    from pathlib import Path

    meta_path = Path(settings.BASE_DIR) / "deploy" / "cron-meta.json"
    with meta_path.open() as fh:
        raw = json.load(fh)
    # Strip the `_doc` annotation entry (JSON has no comments; we
    # park documentation under a leading-underscore key by convention).
    return {k: v for k, v in raw.items() if not k.startswith("_")}


CRON_META: dict[str, dict] = _load_cron_meta()


def _read_status_file(path):
    """Parse one of /var/log/topquaranta/status/<name>.status.

    Format is a flat `key=value` file emitted by `tq-run` after every
    cron run. The `last_output<<EOF` block is multi-line; we only
    keep the `status` / `last_run` / `exit_code` / `attempts` keys.
    """
    from pathlib import Path

    p = Path(path)
    if not p.exists():
        return None
    data = {}
    try:
        with p.open() as fh:
            in_heredoc = False
            for line in fh:
                line = line.rstrip("\n")
                if in_heredoc:
                    if line == "EOF":
                        in_heredoc = False
                    continue
                if "<<EOF" in line:
                    in_heredoc = True
                    continue
                if "=" in line:
                    k, _, v = line.partition("=")
                    data[k] = v
    except OSError:
        return None
    return data


def _top_artistes_backlog(limit: int = 15) -> list[dict]:
    """Artists with the most unverified tracks in the active backlog.

    Approved artists first — those are the ones whose backlog staff
    can actually clear. Includes a sample of 3 track titles for
    context and an MBID hint so staff can spot homonym-collision
    candidates at a glance.

    Count semantics MUST match the destination link
    `/staff/cancons?artista_pk=<pk>&verificada=0`, which filters
    `Q(artista=pk) | Q(artistes_col__pk=pk)` — i.e. every track where
    the artiste is the main act OR a collaborator. Counting only the
    main FK (the previous behaviour) systematically under-reported,
    sometimes drastically when an artiste mainly appears on others'
    tracks (caught 2026-05-05 — staff reported the dashboard number
    being lower than the linked page count).
    """
    # SQL-level approach: collect (artiste_pk, canco_pk) pairs from
    # both relations and dedupe in Python. At our current scale
    # (~3 k unverified active tracks total) this is well under 10 k
    # tuples — trivially fast and avoids the buggy multi-M2M
    # `annotate(Count, distinct=True)` SQL Django generates when two
    # related-name JOINs are combined in a single QuerySet.
    main_pairs = Canco.objects.filter(
        verificada=False, activa=True, artista__aprovat=True
    ).values_list("artista_id", "pk")
    col_pairs = Canco.objects.filter(
        verificada=False,
        activa=True,
        artistes_col__aprovat=True,
    ).values_list("artistes_col", "pk")

    pairs: set[tuple[int, int]] = set()
    pairs.update(main_pairs)
    pairs.update(t for t in col_pairs if t[0] is not None)

    counts: dict[int, int] = {}
    for artiste_pk, _ in pairs:
        counts[artiste_pk] = counts.get(artiste_pk, 0) + 1

    top_pks = sorted(counts.items(), key=lambda x: -x[1])[:limit]
    if not top_pks:
        return []

    artistes_by_pk = {
        a.pk: a for a in Artista.objects.filter(pk__in=[pk for pk, _ in top_pks])
    }

    rows = []
    for pk, n_backlog in top_pks:
        a = artistes_by_pk.get(pk)
        if a is None:
            continue
        # Samples include collab tracks too so the preview matches
        # what staff sees on the destination page.
        samples = list(
            Canco.objects.filter(
                Q(artista=a) | Q(artistes_col=a),
                verificada=False,
                activa=True,
            )
            .distinct()
            .order_by("-data_llancament")
            .values_list("nom", flat=True)[:3]
        )
        rows.append(
            {
                "pk": a.pk,
                "nom": a.nom,
                "slug": a.slug,
                "n_backlog": n_backlog,
                "musicbrainz_id": a.musicbrainz_id or "",
                "mb_end_date": a.mb_end_date.isoformat() if a.mb_end_date else None,
                "samples": samples,
            }
        )
    return rows


def _homonym_suspects_details() -> list[dict]:
    """Pairs (artist, deezer_id) that look like an unresolved homonym
    collision: a Cançó was rejected as `artista_incorrecte` while
    pointing at this specific Deezer artist ID, AND that same Deezer
    ID is *still* linked to an artist of the same name with verified
    tracks.

    If the offending Deezer ID has already been unlinked the case is
    considered resolved — even if the historial entry still exists —
    so it doesn't surface here. That's the Cactus case: the rejection
    referenced Deezer artist 5338 (American blues-rock), which was
    later removed from our `Cactus`; today's Deezer ID (303474781) is
    correct, so no human action is needed.

    The function returns one row per (artist, deezer_id) suspect with
    counts and the most recent rejection timestamp.
    """
    rejected = (
        HistorialRevisio.objects.filter(
            decisio="rebutjada",
            motiu="artista_incorrecte",
            artista_deezer_id__isnull=False,
        )
        .values("artista_nom", "artista_deezer_id")
        .annotate(n_rebutjades=Count("pk"), last_at=Max("created_at"))
    )
    cases: list[dict] = []
    for r in rejected:
        nom = r["artista_nom"]
        dz_id = r["artista_deezer_id"]
        # Live artist of this name still owning the offending Deezer ID
        # AND still holding ≥1 verified Cançó.
        art = (
            Artista.objects.filter(nom=nom, deezer_ids__deezer_id=dz_id)
            .annotate(
                n_verificades=Count(
                    "cancons", filter=Q(cancons__verificada=True), distinct=True
                ),
                n_actives=Count(
                    "cancons", filter=Q(cancons__activa=True), distinct=True
                ),
            )
            .filter(n_verificades__gt=0)
            .first()
        )
        if not art:
            continue
        cases.append(
            {
                "artista_pk": art.pk,
                "artista_nom": art.nom,
                "artista_slug": art.slug,
                "deezer_id": dz_id,
                "n_verificades": art.n_verificades,
                "n_actives_total": art.n_actives,
                "n_rebutjades": r["n_rebutjades"],
                "last_rejected_at": (
                    r["last_at"].isoformat() if r["last_at"] else None
                ),
            }
        )
    cases.sort(key=lambda c: c["artista_nom"].lower())
    return cases


def _homonym_suspects_qs():
    """QuerySet of suspect artists, used as a list filter (`?homonim_sospitos=1`)."""
    pks = {c["artista_pk"] for c in _homonym_suspects_details()}
    return Artista.objects.filter(pk__in=pks)


def _ml_subtier_stats() -> dict:
    """Per-sub-tier accuracy + auto-decision status.

    The 12 sub-tiers (`music.constants.ML_SUBTIERS`) cover the full
    [0.0, 1.0] confidence axis with no gaps and no overlaps, ordered
    HIGH-to-LOW (A++ first, C-- last). Accuracy comes from
    `HistorialRevisio` — the snapshot of every staff decision, with
    `ml_classe_decisio` / `ml_confianca_decisio` captured at the
    moment the decision was made. This is the only honest source:
    live `Canco.ml_classe` / `ml_confianca` get re-scored on every
    retrain, which would leak the answer back into the metric (a
    model retrained on its own approvals will look perfect on those
    same approvals).

    Each row's `status`:
      * `auto_aprovacio_activa` — pinned at `ML_AUTO_APPROVE_SUBTIERS`;
        tracks here are auto-approved.
      * `auto_rebuig_activa`    — same for rejection.
      * `candidat_aprovacio`    — passes ≥99.5 % approve accuracy on
        n ≥ 200 decisions, but not graduated yet.
      * `candidat_rebuig`       — same for rejection.
      * `mostra_insuficient`    — n < min samples, can't decide.
      * `no_qualifica`          — accuracy below threshold.

    Auto-decisions (motiu="auto_ml") are excluded so a graduated
    sub-tier can't self-reinforce its own accuracy.
    """
    from music.constants import (
        ML_AUTO_APPROVE_SUBTIERS,
        ML_AUTO_APPROVE_THRESHOLD,
        ML_AUTO_MIN_SAMPLES,
        ML_AUTO_REJECT_SUBTIERS,
        ML_AUTO_REJECT_THRESHOLD,
        ML_SUBTIERS,
        MOTIU_AUTO_ML,
    )

    rows: list[dict] = []
    for label, lo, hi in ML_SUBTIERS:
        tier = label[0]
        qs = HistorialRevisio.objects.filter(
            ml_classe_decisio=tier,
            ml_confianca_decisio__gte=lo,
            ml_confianca_decisio__lt=hi,
        ).exclude(motiu=MOTIU_AUTO_ML)
        n = qs.count()
        verif = qs.filter(decisio="aprovada").count()
        rej = qs.filter(decisio="rebutjada").count()
        approve_acc = (verif / n) if n else None
        reject_acc = (rej / n) if n else None

        if label in ML_AUTO_APPROVE_SUBTIERS:
            status = "auto_aprovacio_activa"
        elif label in ML_AUTO_REJECT_SUBTIERS:
            status = "auto_rebuig_activa"
        elif n < ML_AUTO_MIN_SAMPLES:
            status = "mostra_insuficient"
        elif approve_acc is not None and approve_acc >= ML_AUTO_APPROVE_THRESHOLD:
            status = "candidat_aprovacio"
        elif reject_acc is not None and reject_acc >= ML_AUTO_REJECT_THRESHOLD:
            status = "candidat_rebuig"
        else:
            status = "no_qualifica"

        rows.append(
            {
                "label": label,
                "tier": tier,
                "conf_lo": round(lo, 3),
                "conf_hi": round(min(hi, 1.0), 3),
                "n": n,
                "verif": verif,
                "rej": rej,
                "approve_accuracy": (
                    round(approve_acc, 4) if approve_acc is not None else None
                ),
                "reject_accuracy": (
                    round(reject_acc, 4) if reject_acc is not None else None
                ),
                "status": status,
            }
        )
    return {
        "rows": rows,
        "auto_approve_threshold": ML_AUTO_APPROVE_THRESHOLD,
        "auto_reject_threshold": ML_AUTO_REJECT_THRESHOLD,
        "auto_min_samples": ML_AUTO_MIN_SAMPLES,
        "auto_approved": list(ML_AUTO_APPROVE_SUBTIERS),
        "auto_rejected": list(ML_AUTO_REJECT_SUBTIERS),
    }


def _musicbrainz_stats() -> dict:
    """Summary of MusicBrainz coverage across our catalog.

    Splits the "no MBID" bucket into the cases that actually need a
    different action from staff:
      * `provat_sense_mbid` — synced at least once but MB had no
        unambiguous match (likely needs a manual MBID paste)
      * `mai_provat`        — never synced (cron just hasn't reached
        them yet)
      * `bloquejat`         — explicit staff lockout (mb_auto_match_
        disabled OR populated mb_blocked_mbids)

    Cançons no verificades es desglossen per estat MB de la pista i del
    seu artista: la idea és veure quantes podríem promoure a verificada
    si aprofitàssim el senyal MB.
    """
    aprovats_qs = Artista.objects.public()
    aprovat_total = aprovats_qs.count()
    # `with_mbid()` is the public-facing twin of the inline
    # `exclude(NULL).exclude("")` we used to repeat — same semantics.
    aprovats_amb_mbid = aprovats_qs.with_mbid().count()
    aprovats_sense_mbid_qs = aprovats_qs.filter(
        Q(musicbrainz_id__isnull=True) | Q(musicbrainz_id="")
    )
    aprovats_provat_sense_mbid = aprovats_sense_mbid_qs.filter(
        mb_last_sync__isnull=False
    ).count()
    aprovats_mai_provat = aprovats_sense_mbid_qs.filter(
        mb_last_sync__isnull=True
    ).count()
    aprovats_bloquejats = aprovats_qs.filter(Q(mb_auto_match_disabled=True)).count()

    synced = Artista.objects.filter(mb_last_sync__isnull=False).count()
    cancons_confirmed = Canco.objects.filter(mbrainz_confirmed=True).count()
    cancons_total_verified = Canco.objects.filter(verificada=True).count()
    albums_total = Album.objects.count()
    albums_confirmed = Album.objects.filter(mbrainz_confirmed=True).count()
    dissolved = aprovats_qs.filter(mb_end_date__isnull=False).count()
    with_cat_lyrics = Canco.objects.filter(mb_lyrics_language="cat").count()
    oldest_sync = (
        Artista.objects.filter(mb_last_sync__isnull=False)
        .order_by("mb_last_sync")
        .values_list("mb_last_sync", flat=True)
        .first()
    )

    # ── Cançons no verificades, segmentades per cobertura MB ─────────
    no_verif_qs = Canco.objects.filter(verificada=False, activa=True)
    no_verif_total = no_verif_qs.count()
    no_verif_mb_confirmat = no_verif_qs.filter(mbrainz_confirmed=True).count()
    # Tracks not MB-confirmed themselves but whose main artist *does*
    # have an MBID — we know who they belong to in MB space, just
    # haven't matched the recording. Useful for sync-targeting.
    no_verif_artista_amb_mbid = (
        no_verif_qs.filter(mbrainz_confirmed__isnull=True)
        .exclude(artista__musicbrainz_id__isnull=True)
        .exclude(artista__musicbrainz_id="")
        .count()
    )
    # The fully-uncovered slice: track has no MB match AND artist has no MBID.
    no_verif_sense_cobertura = (
        no_verif_qs.filter(mbrainz_confirmed__isnull=True)
        .filter(Q(artista__musicbrainz_id__isnull=True) | Q(artista__musicbrainz_id=""))
        .count()
    )

    return {
        "aprovats_total": aprovat_total,
        "aprovats_amb_mbid": aprovats_amb_mbid,
        "aprovats_provat_sense_mbid": aprovats_provat_sense_mbid,
        "aprovats_mai_provat": aprovats_mai_provat,
        "aprovats_bloquejats": aprovats_bloquejats,
        "artistes_sincronitzats": synced,
        "cancons_confirmades": cancons_confirmed,
        "cancons_verificades_total": cancons_total_verified,
        "albums_total": albums_total,
        "albums_confirmats": albums_confirmed,
        "artistes_dissolts_detectats": dissolved,
        "cancons_lletra_cat": with_cat_lyrics,
        "sync_mes_antic": oldest_sync.isoformat() if oldest_sync else None,
        "no_verif_total": no_verif_total,
        "no_verif_mb_confirmat": no_verif_mb_confirmat,
        "no_verif_artista_amb_mbid": no_verif_artista_amb_mbid,
        "no_verif_sense_cobertura": no_verif_sense_cobertura,
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def estat(request: Request) -> Response:
    """Aggregate everything the visual dashboard needs in one call.

    Shape:
      {
        bd:        counts (artistes/albums/cançons by state),
        whisper:   LID coverage + daily rate,
        ranking:   setmanal + provisional,
        senyal:    daily feed stats,
        comunitat: feedback/propostes/sol·licituds,
        crons:     per-cron last-run status,
        ml: {
          model_mtime, features_total, training_size, class_balance,
          classe_distribution, confianca_avg, importances [{name,value}],
          noise_count,
        },
      }
    """
    import os
    from pathlib import Path

    import joblib

    from music.ml import DIRECTIONS_PATH, FEATURE_NAMES, MODEL_PATH, TFIDF_PATH

    # ── BD inventory ────────────────────────────────────────────────────
    a_total = Artista.objects.count()
    a_aprovat = Artista.objects.public().count()
    a_pendent = Artista.objects.pendents().count()
    a_descartat = a_total - a_aprovat - a_pendent

    alb_total = Album.objects.count()
    alb_descartat = Album.objects.filter(descartat=True).count()

    c_total = Canco.objects.count()
    c_verif = Canco.objects.filter(verificada=True).count()
    c_no_verif = Canco.objects.filter(verificada=False, activa=True).count()
    c_inactiva = Canco.objects.filter(activa=False).count()
    c_deezer = Canco.objects.filter(deezer_id__isnull=False).count()
    c_isrc = Canco.objects.exclude(isrc__in=["", None]).count()
    c_preview = Canco.objects.exclude(preview_url__in=["", None]).count()

    # ── Flux setmanal: entrades + caducitats + target de verificació ──
    #
    # Intake: `data_llancament` — la data de publicació real de la
    # cançó. És el que importa pel ranking (el pipeline pot veure una
    # cançó antiga en fer un backfill, però això no és "flux nou"). Les
    # cançons sense data_llancament s'exclouen de la mètrica.
    #
    #   * intake_setmanal_robust — dies amb volum anòmal (>500) exclosos
    #     del càlcul de mitjana.
    #   * intake_setmanal_bruta — lectura directa.
    #   * intake_7d — últims 7 dies.
    #
    # Caducaran: cançons `verificada=False` amb `data_llancament` que
    # cau fora dels 365 dies la setmana que ve. `netejar_caducades`
    # les esborra cada dia a les 04:30, així que efectivament marxen.
    from datetime import timedelta as _td

    from music.constants import DIES_CADUCITAT

    today = datetime.date.today()
    four_weeks_ago = today - _td(days=28)

    # Per-day histogram of last 28 days by release date.
    daily_rows = list(
        Canco.objects.filter(data_llancament__gte=four_weeks_ago)
        .values("data_llancament")
        .annotate(n=Count("pk"))
    )
    daily_by_day = {r["data_llancament"]: r["n"] for r in daily_rows}
    intake_28d_total = sum(daily_by_day.values())
    intake_setmanal_bruta = round(intake_28d_total / 4.0, 1)

    ANOMALY_DAY_THRESHOLD = 500
    normal_days_counts = [
        n for n in daily_by_day.values() if 0 < n <= ANOMALY_DAY_THRESHOLD
    ]
    if normal_days_counts:
        avg_per_day = sum(normal_days_counts) / len(normal_days_counts)
        intake_setmanal_robust = round(avg_per_day * 7, 1)
    else:
        intake_setmanal_robust = intake_setmanal_bruta

    seven_days_ago = today - _td(days=6)
    intake_7d = Canco.objects.filter(data_llancament__gte=seven_days_ago).count()

    # Per-week breakdown (oldest → newest), for the trend sparkline.
    intake_setmanes: list[dict] = []
    for w in range(4):
        wk_start = today - _td(days=(w + 1) * 7 - 1)
        wk_end = today + _td(days=1) if w == 0 else today - _td(days=w * 7 - 1)
        n = Canco.objects.filter(
            data_llancament__gte=wk_start, data_llancament__lt=wk_end
        ).count()
        label = f"-{(w + 1) * 7}d → -{w * 7}d"
        intake_setmanes.append({"label": label, "n": n})
    intake_setmanes = list(reversed(intake_setmanes))

    cutoff_today = today - _td(days=DIES_CADUCITAT)
    cutoff_next_week = today - _td(days=DIES_CADUCITAT - 7)
    caducaran_7d = Canco.objects.filter(
        verificada=False,
        data_llancament__gte=cutoff_today,
        data_llancament__lt=cutoff_next_week,
    ).count()
    cutoff_next_month = today - _td(days=DIES_CADUCITAT - 30)
    caducaran_30d = Canco.objects.filter(
        verificada=False,
        data_llancament__gte=cutoff_today,
        data_llancament__lt=cutoff_next_month,
    ).count()

    # Target: per no acumular backlog la ràtio setmanal de verificació
    # ha de cobrir les entrades netes (robustes) menys el que caducarà
    # naturalment. Si el signe és negatiu el backlog baixa sol.
    target_verificacio_setmanal = max(0, round(intake_setmanal_robust - caducaran_7d))

    # ── Whisper LID coverage ────────────────────────────────────────────
    # `whisper_processat_at IS NULL` covers two very different states:
    #   - tracks with a Deezer preview waiting to be analysed (the cron
    #     will pick them up at 05:00 UTC, --limit 100/night)
    #   - tracks WITHOUT preview that can never be analysed (Deezer
    #     doesn't expose 30 s clips for every catalogue entry)
    # Surface them separately so staff doesn't see "1.500 pending,
    # 15 days at 700/night" and panic.
    w_ca = Canco.objects.filter(whisper_lang="ca").count()
    w_no = (
        Canco.objects.filter(whisper_processat_at__isnull=False)
        .exclude(whisper_lang="ca")
        .count()
    )
    w_pend_qs = Canco.objects.filter(whisper_processat_at__isnull=True)
    w_pend_amb_preview = (
        w_pend_qs.exclude(preview_url="").exclude(preview_url__isnull=True).count()
    )
    w_pend_sense_preview = w_pend_qs.filter(
        Q(preview_url="") | Q(preview_url__isnull=True)
    ).count()
    # Daily Whisper budget — kept in sync with the cron line in
    # deploy/cron.topquaranta. Used to surface a realistic ETA on the
    # processable backlog.
    WHISPER_DAILY_LIMIT = 100

    # ── Ranking ─────────────────────────────────────────────────────────
    setmanes = TopSetmanal.objects.values("setmana").distinct().count()
    r_prov = TopProvisional.objects.count()
    last_oficial = (
        TopSetmanal.objects.order_by("-setmana")
        .values_list("setmana", flat=True)
        .first()
    )

    # ── Senyal ──────────────────────────────────────────────────────────
    s_total = SenyalDiari.objects.count()
    s_recent = (
        SenyalDiari.objects.order_by("-data").values_list("data", flat=True).first()
    )

    # ── Comunitat ───────────────────────────────────────────────────────
    fb_obert = Feedback.objects.filter(resolt=False).count()
    fb_total = Feedback.objects.count()
    prop_pend = PropostaArtista.objects.filter(
        estat=PropostaArtista.ESTAT_PENDENT
    ).count()
    sol_pend = UserArtista.objects.filter(estat=UserArtista.ESTAT_PENDENT).count()

    # ── Cron status ─────────────────────────────────────────────────────
    status_dir = Path("/var/log/topquaranta/status")
    crons = []
    if status_dir.exists():
        for f in sorted(status_dir.glob("*.status")):
            parsed = _read_status_file(f)
            if not parsed:
                continue
            meta = CRON_META.get(f.stem, {})
            # `_sort_key` is a temporary field popped before serialising;
            # we sort by max_age (frequency proxy) then name so the
            # dashboard reads top-down: hourly → daily → weekly →
            # monthly → quarterly. Unknown commands sink to the end.
            _sort_key = (meta.get("max_age_hours") or 10**9, f.stem)
            crons.append(
                {
                    "name": f.stem,
                    "command": parsed.get("command", ""),
                    "args": parsed.get("args", ""),
                    "last_run": parsed.get("last_run", ""),
                    "last_skip": parsed.get("last_skip", ""),
                    "status": parsed.get("status", ""),
                    "exit_code": parsed.get("exit_code", ""),
                    "attempts": parsed.get("attempts", ""),
                    # `consecutive_skips` is the number of cron ticks
                    # that have been blocked by an in-flight (and
                    # potentially hung) instance — written by tq-run
                    # whenever the wrapped command exits 75. A value
                    # >0 paired with stale `last_run` is the signal
                    # of a stuck process (caught 2026-05-01 with
                    # `obtenir_novetats` hung ~12 days).
                    "consecutive_skips": int(parsed.get("consecutive_skips") or 0),
                    # WORK_DONE protocol (2026-05-07): commands that
                    # opt in emit a final `WORK_DONE=N` line; tq-run
                    # surfaces N here + `consecutive_zero_work`. Both
                    # may be missing/None when the command doesn't
                    # opt in, in which case the dashboard treats them
                    # as "no signal".
                    "work_done": (
                        int(parsed["work_done"]) if parsed.get("work_done") else None
                    ),
                    "consecutive_zero_work": int(
                        parsed.get("consecutive_zero_work") or 0
                    ),
                    "frequency_label": meta.get("frequency_label", ""),
                    "max_age_hours": meta.get("max_age_hours"),
                    "skip_concern": meta.get("skip_concern"),
                    "silenced": meta.get("silenced", False),
                    "silenced_reason": meta.get("silenced_reason", ""),
                    "_sort_key": _sort_key,
                }
            )

        crons.sort(key=lambda c: c.pop("_sort_key"))

    # ── ML ──────────────────────────────────────────────────────────────
    ml = {
        "trained": False,
        "features_total": None,
        "training_size": None,
        "class_balance": None,
        "model_mtime": None,
        "tfidf_mtime": None,
        "importances": [],
        "noise_count": None,
        "classe_distribution": {},
        "confianca_avg": None,
        "confianca_min": None,
        "confianca_max": None,
    }
    if MODEL_PATH.exists():
        try:
            clf = joblib.load(MODEL_PATH)
            ml["trained"] = True
            ml["features_total"] = getattr(clf, "n_features_in_", None)
            ml["model_mtime"] = datetime.datetime.fromtimestamp(
                os.path.getmtime(MODEL_PATH)
            ).isoformat()
            if TFIDF_PATH.exists():
                ml["tfidf_mtime"] = datetime.datetime.fromtimestamp(
                    os.path.getmtime(TFIDF_PATH)
                ).isoformat()
            if hasattr(clf, "feature_importances_"):
                importances = list(clf.feature_importances_)
                names = FEATURE_NAMES
                if len(names) != len(importances):
                    # Names out of sync (ex. mid-deploy). Fall back to indices.
                    names = [f"f{i}" for i in range(len(importances))]
                directions: dict[str, float] = {}
                if DIRECTIONS_PATH.exists():
                    try:
                        directions = joblib.load(DIRECTIONS_PATH) or {}
                    except Exception:  # noqa: BLE001
                        directions = {}
                pairs = sorted(zip(names, importances), key=lambda x: -x[1])
                ml["importances"] = [
                    {
                        "name": n,
                        "value": round(float(v), 5),
                        # 'direction': +1 = higher feature → approval,
                        # -1 = higher feature → rejection, 0 = flat /
                        # unknown (TF-IDF features and absent data).
                        "direction": (
                            1
                            if directions.get(n, 0) > 1e-9
                            else -1 if directions.get(n, 0) < -1e-9 else 0
                        ),
                    }
                    for n, v in pairs
                ]
                ml["noise_count"] = sum(1 for _, v in pairs if v < 0.0005)
        except Exception as exc:  # noqa: BLE001
            ml["error"] = str(exc)

    ml["training_size"] = HistorialRevisio.objects.count()
    apv = HistorialRevisio.objects.filter(decisio="aprovada").count()
    rej = HistorialRevisio.objects.filter(decisio="rebutjada").count()
    ml["class_balance"] = {"aprovades": apv, "rebutjades": rej}

    for row in (
        Canco.objects.values("ml_classe").annotate(n=Count("pk")).order_by("ml_classe")
    ):
        key = row["ml_classe"] or "none"
        ml["classe_distribution"][key] = row["n"]

    conf_agg = Canco.objects.exclude(ml_confianca__isnull=True).aggregate(
        avg=Avg("ml_confianca"),
        mn=Min("ml_confianca"),
        mx=Max("ml_confianca"),
    )
    if conf_agg["avg"] is not None:
        ml["confianca_avg"] = round(float(conf_agg["avg"]), 3)
        ml["confianca_min"] = round(float(conf_agg["mn"]), 3)
        ml["confianca_max"] = round(float(conf_agg["mx"]), 3)

    # Sub-tier accuracy + auto-decision status (the table below the
    # main ML panel on the staff dashboard).
    ml["subtiers"] = _ml_subtier_stats()

    return Response(
        {
            "bd": {
                "artistes": {
                    "total": a_total,
                    "aprovats": a_aprovat,
                    "pendents": a_pendent,
                    "descartats": a_descartat,
                },
                "albums": {
                    "total": alb_total,
                    "actius": alb_total - alb_descartat,
                    "descartats": alb_descartat,
                },
                "cancons": {
                    "total": c_total,
                    "verificades": c_verif,
                    "no_verificades_actives": c_no_verif,
                    "inactives": c_inactiva,
                    "amb_deezer": c_deezer,
                    "amb_isrc": c_isrc,
                    "amb_preview": c_preview,
                },
            },
            "flux": {
                "intake_ultim_mes": intake_28d_total,
                "intake_setmanal_bruta": intake_setmanal_bruta,
                "intake_setmanal_robust": intake_setmanal_robust,
                "intake_7d": intake_7d,
                "intake_per_setmana": intake_setmanes,
                "anomaly_day_threshold": ANOMALY_DAY_THRESHOLD,
                "anomaly_days_excluded": sum(
                    1 for n in daily_by_day.values() if n > ANOMALY_DAY_THRESHOLD
                ),
                "caducaran_7d": caducaran_7d,
                "caducaran_30d": caducaran_30d,
                "target_verificacio_setmanal": target_verificacio_setmanal,
                "backlog_no_verificades": c_no_verif,
                "top_artistes_backlog": _top_artistes_backlog(limit=15),
            },
            "whisper": {
                "ca": w_ca,
                "no_ca": w_no,
                # `pendent_amb_preview` = realistic queue (cron pickup).
                # `pendent_sense_preview` = forever-pending: Deezer has
                # no preview, Whisper can't run on them.
                "pendent_amb_preview": w_pend_amb_preview,
                "pendent_sense_preview": w_pend_sense_preview,
                "daily_limit": WHISPER_DAILY_LIMIT,
                "total": c_total,
            },
            "musicbrainz": _musicbrainz_stats(),
            "homonimia": (
                lambda c: {
                    "casos_sospitosos": len(c),
                    "casos": c,
                }
            )(_homonym_suspects_details()),
            "ranking": {
                "setmanes_historiques": setmanes,
                "provisional_ara": r_prov,
                "ultim_oficial": last_oficial.isoformat() if last_oficial else None,
            },
            "senyal": {
                "total": s_total,
                "data_recent": s_recent.isoformat() if s_recent else None,
            },
            "comunitat": {
                "feedback_obert": fb_obert,
                "feedback_total": fb_total,
                "propostes_pendents": prop_pend,
                "solicituds_pendents": sol_pend,
            },
            "crons": crons,
            "ml": ml,
        }
    )
