"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db.models import (
    Q,
)
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from music.constants import MOTIUS_REBUIG
from music.models import (
    HistorialRevisio,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Historial (read-only)
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def historial_list(request: Request) -> Response:
    qs = HistorialRevisio.objects.all()
    decisio = request.GET.get("decisio", "")
    if decisio in ("aprovada", "rebutjada"):
        qs = qs.filter(decisio=decisio)
    motiu = request.GET.get("motiu", "")
    if motiu:
        qs = qs.filter(motiu=motiu)
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.filter(Q(canco_nom__icontains=cerca) | Q(artista_nom__icontains=cerca))
    qs = qs.order_by("-created_at")
    page, meta = _paginate(qs, request)
    return Response(
        {
            "motius": list(MOTIUS_REBUIG),
            "results": [
                {
                    "pk": h.pk,
                    "canco_nom": h.canco_nom or "",
                    "artista_nom": h.artista_nom or "",
                    "decisio": h.decisio,
                    "motiu": h.motiu or "",
                    "created_at": h.created_at.isoformat() if h.created_at else None,
                }
                for h in page.object_list
            ],
            **meta,
        }
    )
