"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db import IntegrityError, transaction
from django.db.models import (
    Case,
    Count,
    F,
    IntegerField,
    Q,
    Value,
    When,
)
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import PropostaArtista
from music.audit import log_staff_action
from music.ml import recalcular_ml_si_cal
from music.models import (
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Municipi,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate, noms_amb_homonims

# ═════════════════════════════════════════════════════════════════════════
# Pendents — auto-discovered artists awaiting review
# ═════════════════════════════════════════════════════════════════════════


def _compute_propostes_per_artista_map() -> dict[int, int]:
    """Return {artista_pk: #pending_propostes_referencing_its_deezer_ids}.

    A single proposal that references two Deezer IDs of the same
    artist counts as 1 hit on that artist (the set() below dedups).
    A proposal that references IDs of multiple artists increments
    every affected artist by 1.

    Scoped to `estat=pendent` — approved/rejected proposals don't
    add noise to the triage queue.
    """
    from collections import defaultdict

    pending = PropostaArtista.objects.filter(
        estat=PropostaArtista.ESTAT_PENDENT
    ).values_list("deezer_ids", flat=True)
    # Map Deezer ID → Artista.pk once so the inner loop is O(1).
    dz_to_artista = dict(ArtistaDeezer.objects.values_list("deezer_id", "artista_id"))
    counter: dict[int, int] = defaultdict(int)
    for raw_list in pending:
        hit_artistes: set[int] = set()
        for raw in raw_list or []:
            try:
                dz = int(raw)
            except (TypeError, ValueError):
                continue
            aid = dz_to_artista.get(dz)
            if aid is not None:
                hit_artistes.add(aid)
        for aid in hit_artistes:
            counter[aid] += 1
    return dict(counter)


def _artista_card(a, homset=None) -> dict:
    """Compact artist shape for staff tables (pendents + artistes).

    Callers MUST `prefetch_related("localitats__municipi", "deezer_ids",
    "territoris", "lastfm_aliases")` — the card reads all four from the
    prefetch cache (no per-row query). Before 2026-06-07 the localitat
    line called `.select_related().first()`, which re-queried per row and
    defeated the prefetch (N+1 ×up-to-200 on the list endpoints)."""
    # Pick the first localitat from the prefetched cache rather than
    # re-querying. `municipi.territori_id` is a column, so reading it
    # needs no extra join beyond `localitats__municipi`.
    loc = next(iter(a.localitats.all()), None)
    loc_out = None
    if loc:
        if loc.municipi:
            loc_out = {
                "municipi_id": loc.municipi.pk,
                "municipi_nom": loc.municipi.nom,
                "comarca": loc.municipi.comarca,
                "territori": loc.municipi.territori_id,
                "manual": "",
            }
        elif loc.localitat_manual:
            loc_out = {
                "municipi_id": None,
                "municipi_nom": "",
                "comarca": "",
                "territori": "ALT",
                "manual": loc.localitat_manual,
            }
    return {
        "pk": a.pk,
        "nom": a.nom,
        "slug": a.slug,
        "genere": a.genere or "",
        "aprovat": a.aprovat,
        "pendent_review": a.pendent_review,
        # Homonym marker: another artista shares this name (modulo accents +
        # punctuation). Flags the Crim-style traps in the pendents queue.
        "te_homonims": (
            bool(a.nom_normalitzat) and a.nom_normalitzat in homset
            if homset is not None
            else a.homonims().exists()
        ),
        "auto_descobert": a.auto_descobert,
        "font_descoberta": a.font_descoberta or "",
        # Read from the prefetch cache (`.values_list()` would bypass it
        # and re-query per row — the N+1 caught 2026-06-07).
        "deezer_ids": [d.deezer_id for d in a.deezer_ids.all()],
        "territoris": sorted(t.codi for t in a.territoris.all()),
        "localitat": loc_out,
        "musicbrainz_id": a.musicbrainz_id or "",
        "mb_end_date": a.mb_end_date.isoformat() if a.mb_end_date else None,
        "mb_last_sync": a.mb_last_sync.isoformat() if a.mb_last_sync else None,
        "mb_blocked_mbids": list(a.mb_blocked_mbids or []),
        "mb_auto_match_disabled": a.mb_auto_match_disabled,
        # Surfaced when the caller sorted by `cancons_tops_desc` so
        # the UI can show the count next to each row. Otherwise None.
        "n_cancons_tops": getattr(a, "n_cancons_tops", None),
        # Surfaced when the caller passed `?include_n_top=1`. Same
        # metric as `n_cancons_tops` without the `posicio<=40` filter;
        # in practice TopSetmanal only stores posicio<=40 rows so the
        # two numbers match, but they're kept named per use case for
        # clarity at the call site.
        "n_top": getattr(a, "n_top", None),
        "instagram_url": a.instagram_url or "",
        # Last.fm artist metadata — surfaced everywhere the card is used
        # (artistes list, pendents, edit page) so staff can spot
        # high-affinity discoveries without an extra fetch.
        "nb_similars_lastfm": a.nb_similars_lastfm or 0,
        "lastfm_last_sync": (
            a.lastfm_last_sync.isoformat() if a.lastfm_last_sync else None
        ),
        # Alias counts surface in the artistes list so staff can see
        # which artists have outstanding alias review work without
        # opening each one. The numbers come from the related
        # manager — cheap thanks to prefetch_related, but never N+1
        # in the worst case (small per-artist sets).
        "lastfm_aliases_pendents": sum(
            1 for x in a.lastfm_aliases.all() if not x.confirmat and not x.rebutjat
        ),
        "lastfm_aliases_confirmats": sum(
            1 for x in a.lastfm_aliases.all() if x.confirmat
        ),
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def pendents_list(request: Request) -> Response:
    # distinct=True on both Count() calls to avoid the cartesian
    # multiplication that happens when two LEFT JOINs stack up (Django
    # ticket #10060). Without it, an artist with 3 main tracks and 4
    # collab tracks reported 12 verified, not 7.
    qs = (
        Artista.objects.filter(aprovat=False, pendent_review=True)
        .prefetch_related(
            "territoris", "deezer_ids", "localitats__municipi", "lastfm_aliases"
        )
        .annotate(
            nb_verif_main=Count(
                "cancons", filter=Q(cancons__verificada=True), distinct=True
            ),
            nb_verif_col=Count(
                "participacions",
                filter=Q(participacions__verificada=True),
                distinct=True,
            ),
        )
        .annotate(nb_verif=F("nb_verif_main") + F("nb_verif_col"))
    )
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.annotate(_nom_norm=_unaccent_field("nom")).filter(
            _nom_norm__contains=_normalize_search_term(cerca)
        )

    # Restrict to a single discovery source. Most useful right now:
    # `font_descoberta=lastfm_similar` to triage the network of
    # similar-artists Last.fm flagged as related to our aprovats.
    font = (request.GET.get("font_descoberta") or "").strip()
    if font:
        qs = qs.filter(font_descoberta=font)

    # Annotate with n_propostes: count of pending PropostaArtista rows
    # whose deezer_ids JSON array references any of this artist's
    # Deezer IDs. Computed in Python because JSON-list overlap is a
    # Postgres-specific query and the set of pending proposals is
    # small (<100 in practice).
    propostes_per_artista = _compute_propostes_per_artista_map()
    if propostes_per_artista:
        # Build a Case/When that maps Artista.pk → count. With <100
        # pending proposals this is ~dozens of branches at most.
        when_clauses = [
            When(pk=aid, then=Value(n)) for aid, n in propostes_per_artista.items()
        ]
        qs = qs.annotate(
            n_propostes=Case(
                *when_clauses, default=Value(0), output_field=IntegerField()
            )
        )
    else:
        qs = qs.annotate(n_propostes=Value(0, output_field=IntegerField()))

    # Default sort: propostes first, then verified-tracks count, then
    # alphabetical. `?sort=similars_lastfm` switches to "Last.fm
    # affinity descending" for the similar-artists triage workflow.
    sort = (request.GET.get("sort") or "").strip()
    if sort == "similars_lastfm":
        qs = qs.order_by("-nb_similars_lastfm", "-n_propostes", "-nb_verif", "nom")
    else:
        qs = qs.order_by("-n_propostes", "-nb_verif", "nom")
    page, meta = _paginate(qs, request)
    homset = noms_amb_homonims()
    rows = []
    for a in page.object_list:
        row = _artista_card(a, homset)
        row["nb_verif"] = a.nb_verif
        row["n_propostes"] = getattr(a, "n_propostes", 0) or 0
        rows.append(row)
    return Response({"results": rows, **meta})


@api_view(["POST"])
@permission_classes([IsStaff])
def pendent_aprovar(request: Request, pk: int) -> Response:
    """Approve a pending artist. Accepts deezer_id + municipi_id/comarca+localitat."""
    artista = get_object_or_404(Artista, pk=pk)
    data = request.data or {}

    deezer_id_raw = str(data.get("deezer_id", "")).strip()
    municipi_id = data.get("municipi_id")
    comarca = (data.get("comarca") or "").strip()
    localitat = (data.get("localitat") or "").strip()
    # Explicit shortcut used by the React cascade when territori=ALT:
    # there's no comarca/municipi then, just a free-text place name.
    manual_loc = (data.get("manual") or "").strip()

    cascade_selected = (
        bool(municipi_id) or (bool(comarca) and bool(localitat)) or bool(manual_loc)
    )
    has_existing_loc = artista.localitats.exists()
    if not cascade_selected and not has_existing_loc:
        return Response({"error": "Cal seleccionar un municipi"}, status=400)

    # Deezer gate (2026-06): an artist may only be approved with at least
    # one Deezer anchor — either an existing ArtistaDeezer row or a
    # deezer_id supplied here. Checked BEFORE the transaction so a reject
    # never leaves a half-written localitat. NOT "Deezer or MBID": Deezer,
    # full stop (the catalogue + previews + scale all key off it).
    will_have_deezer = artista.deezer_ids.exists() or bool(deezer_id_raw)
    if not will_have_deezer:
        return Response(
            {"error": "Cal almenys un Deezer ID per aprovar l'artista."},
            status=400,
        )

    deezer_id: int | None = None
    if deezer_id_raw:
        try:
            deezer_id = int(deezer_id_raw)
        except ValueError:
            return Response({"error": "Deezer ID invàlid"}, status=400)

    audit_loc = None
    territori = None

    with transaction.atomic():
        if (
            deezer_id is not None
            and not artista.deezer_ids.filter(deezer_id=deezer_id).exists()
        ):
            try:
                with transaction.atomic():
                    ArtistaDeezer.objects.create(
                        artista=artista,
                        deezer_id=deezer_id,
                        principal=not artista.deezer_ids.exists(),
                    )
            except IntegrityError:
                owner = (
                    ArtistaDeezer.objects.filter(deezer_id=deezer_id)
                    .select_related("artista")
                    .first()
                )
                return Response(
                    {
                        "error": (
                            f"Deezer ID {deezer_id} ja pertany a "
                            f"«{owner.artista.nom if owner else '?'}». "
                            "Fusiona els dos artistes o canvia l'ID."
                        ),
                        "owner_pk": owner.artista.pk if owner else None,
                    },
                    status=409,
                )

        if cascade_selected:
            if municipi_id:
                try:
                    municipi = Municipi.objects.get(pk=int(municipi_id))
                except Municipi.DoesNotExist:
                    return Response({"error": "Municipi no trobat"}, status=404)
                ArtistaLocalitat.objects.create(artista=artista, municipi=municipi)
                audit_loc = f"{municipi.nom}, {municipi.comarca}"
                territori = municipi.territori_id
            elif manual_loc:
                ArtistaLocalitat.objects.create(
                    artista=artista,
                    municipi=None,
                    localitat_manual=manual_loc,
                )
                audit_loc = f"{manual_loc} (manual)"
                territori = "ALT"
            else:
                try:
                    municipi = Municipi.objects.get(nom=localitat, comarca=comarca)
                    ArtistaLocalitat.objects.create(artista=artista, municipi=municipi)
                    audit_loc = f"{municipi.nom}, {municipi.comarca}"
                    territori = municipi.territori_id
                except Municipi.DoesNotExist:
                    ArtistaLocalitat.objects.create(
                        artista=artista,
                        municipi=None,
                        localitat_manual=f"{localitat}, {comarca}",
                    )
                    audit_loc = f"{localitat}, {comarca} (manual)"
                    territori = "ALT"
        else:
            loc = artista.localitats.select_related("municipi__territori").first()
            if loc and loc.municipi:
                audit_loc = f"{loc.municipi.nom}, {loc.municipi.comarca} (existent)"
                territori = loc.municipi.territori_id
            elif loc:
                audit_loc = f"{loc.localitat_manual} (existent, manual)"
                territori = "ALT"

        artista.aprovat = True
        artista.pendent_review = False
        artista.save(update_fields=["aprovat", "pendent_review"])

        # Push the new public URLs to IndexNow so Bing/Yandex pick
        # them up within hours. Fail-open per the helper.
        from web.seo.indexnow import notify_artista

        notify_artista(artista)

        # Auto-approve any user propostes that reference this artist
        # via Deezer ID overlap. Saves staff from a second click on a
        # proposta that's already resolved by the pendent approval.
        artista_dz = list(artista.deezer_ids.values_list("deezer_id", flat=True))
        propostes_auto = []
        if artista_dz:
            q = Q()
            for dz in artista_dz:
                q |= Q(deezer_ids__contains=dz)
            propostes_auto = list(
                PropostaArtista.objects.filter(
                    estat=PropostaArtista.ESTAT_PENDENT
                ).filter(q)
            )
            for p in propostes_auto:
                p.estat = PropostaArtista.ESTAT_APROVAT
                p.artista_creat = artista
                p.save(update_fields=["estat", "artista_creat"])

    log_staff_action(
        request,
        "pendent_aprovar",
        target=artista,
        territori=territori,
        localitat=audit_loc,
        deezer_id_afegit=deezer_id,
        propostes_auto_aprovades=[p.pk for p in propostes_auto],
    )
    return Response(
        {
            "ok": True,
            "territori": territori,
            "propostes_auto_aprovades": len(propostes_auto),
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def pendent_descartar(request: Request, pk: int) -> Response:
    """Discard a pendent artist by TOMBSTONING it — never deleting.

    A hard delete leaves no `Artista` row for the Last.fm similar
    resolver (`obtenir_metadata_lastfm._resolve_similar_target`) to
    match, so an approved artist that still recommends the name
    re-creates the pendent on its next sync — the
    Tremenda Jauría / The Fades resurrection loop (audit 2026-06-02).
    `aprovat=False, pendent_review=False` keeps the row out of the
    pendents queue (`pendents_list` filters `pendent_review=True`) AND
    lets the resolver's step 3 (`aprovat=False` by name) find it without
    re-queuing it (`_process` never flips `pendent_review` on a matched
    row). Both branches (with/without verified tracks) now land on the
    same tombstone state; the StaffAuditLog row is preserved.
    """
    artista = get_object_or_404(Artista, pk=pk)
    had_verified = artista.cancons.filter(verificada=True).exists()
    artista.aprovat = False
    artista.pendent_review = False
    artista.save(update_fields=["aprovat", "pendent_review"])
    recalcular_ml_si_cal()
    log_staff_action(
        request,
        "pendent_descartar",
        target=artista,
        action_taken="kept_pendent_review_false",
        reason="had verified tracks" if had_verified else "tombstoned (no verified)",
    )
    return Response({"ok": True, "action": "tombstoned"})
