"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db import transaction
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import PropostaArtista
from music.audit import log_staff_action
from music.models import (
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Municipi,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Propostes d'artistes
# ═════════════════════════════════════════════════════════════════════════


def _proposta_row(p) -> dict:
    return {
        "pk": p.pk,
        "nom": p.nom,
        "estat": p.estat,
        "usuari": {
            "pk": p.usuari_id,
            "email": p.usuari.email if p.usuari_id else "",
            "username": p.usuari.username if p.usuari_id else "",
        },
        "created_at": p.created_at.isoformat() if p.created_at else None,
        "artista_creat": (
            {"pk": p.artista_creat.pk, "slug": p.artista_creat.slug}
            if p.artista_creat_id
            else None
        ),
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def propostes_list(request: Request) -> Response:
    qs = PropostaArtista.objects.select_related("usuari", "artista_creat")
    estat = request.GET.get("estat", "")
    if estat in ("pendent", "aprovat", "rebutjat"):
        qs = qs.filter(estat=estat)
    qs = qs.order_by("-created_at")
    page, meta = _paginate(qs, request, default_per_page=25)
    return Response({"results": [_proposta_row(p) for p in page.object_list], **meta})


@api_view(["GET"])
@permission_classes([IsStaff])
def proposta_detail(request: Request, pk: int) -> Response:
    p = get_object_or_404(
        PropostaArtista.objects.select_related("usuari", "artista_creat"), pk=pk
    )
    localitzacions: list[str] = []
    for loc in p.localitzacions or []:
        if "municipi_id" in loc:
            try:
                m = Municipi.objects.get(pk=loc["municipi_id"])
                localitzacions.append(f"{m.nom}, {m.comarca} ({m.territori_id})")
            except Municipi.DoesNotExist:
                localitzacions.append(f"Municipi ID {loc['municipi_id']} (no trobat)")
        elif "manual" in loc:
            localitzacions.append(f"{loc['manual']} (manual)")
    row = _proposta_row(p)
    row.update(
        {
            "justificacio": p.justificacio or "",
            "localitzacions": localitzacions,
            "deezer_ids": p.get_deezer_id_list(),
            "social": {
                f: getattr(p, f, "") or ""
                for f, _ in Artista.SOCIAL_LINK_FIELDS
                if getattr(p, f, "")
            },
        }
    )
    return Response(row)


@api_view(["POST"])
@permission_classes([IsStaff])
def proposta_aprovar(request: Request, pk: int) -> Response:
    p = get_object_or_404(PropostaArtista.objects.select_related("usuari"), pk=pk)
    if p.estat != PropostaArtista.ESTAT_PENDENT:
        return Response({"error": "Ja processada."}, status=400)

    # Validate Deezer IDs *before* opening the transaction. An
    # IntegrityError inside `atomic()` poisons the surrounding block
    # (Postgres refuses further statements), so the silent try/except
    # that used to live in the loop actually crashed the whole approval
    # with a TransactionManagementError. Check up-front and surface a
    # 409 with the conflict info so staff can decide how to resolve it
    # (merge, change the ID on the proposal, etc.).
    wanted_deezer = p.get_deezer_id_list()
    if wanted_deezer:
        clashing = ArtistaDeezer.objects.filter(
            deezer_id__in=wanted_deezer
        ).select_related("artista")
        conflicts = [
            {
                "deezer_id": ad.deezer_id,
                "owner_pk": ad.artista_id,
                "owner_nom": ad.artista.nom if ad.artista else "?",
                "owner_aprovat": bool(ad.artista.aprovat) if ad.artista else False,
                "owner_pendent_review": (
                    bool(ad.artista.pendent_review) if ad.artista else False
                ),
                "owner_slug": ad.artista.slug if ad.artista else "",
            }
            for ad in clashing
        ]
        if conflicts:
            # The UI uses this to offer interactive options: go to the
            # existing artist, merge the proposal into it, or reject
            # the proposal. No silent pass.
            return Response(
                {
                    "error": (
                        "Algun dels Deezer IDs de la proposta ja pertany a "
                        "un altre artista."
                    ),
                    "conflicts": conflicts,
                },
                status=409,
            )

    with transaction.atomic():
        artista = Artista.objects.create(
            nom=p.nom,
            lastfm_nom=p.nom,
            aprovat=True,
            auto_descobert=False,
            font_descoberta="proposta_usuari",
        )
        for f, _ in Artista.SOCIAL_LINK_FIELDS:
            val = getattr(p, f, "")
            if val:
                setattr(artista, f, val)
        artista.save()
        for i, dz in enumerate(wanted_deezer):
            ArtistaDeezer.objects.create(
                artista=artista, deezer_id=dz, principal=(i == 0)
            )
        for loc in p.localitzacions or []:
            if "municipi_id" in loc:
                try:
                    m = Municipi.objects.get(pk=loc["municipi_id"])
                    ArtistaLocalitat.objects.create(artista=artista, municipi=m)
                except Municipi.DoesNotExist:
                    pass
            elif "manual" in loc:
                ArtistaLocalitat.objects.create(
                    artista=artista, municipi=None, localitat_manual=loc["manual"]
                )
        p.estat = PropostaArtista.ESTAT_APROVAT
        p.artista_creat = artista
        p.save(update_fields=["estat", "artista_creat"])
    log_staff_action(
        request,
        "proposta_aprovar",
        target=p,
        artista_creat_id=artista.pk,
        artista_nom=artista.nom,
        usuari_proposant=p.usuari.email,
    )
    from comptes.notifications import notify_user_proposta_resolta

    notify_user_proposta_resolta(p, "aprovada")
    return Response({"ok": True, "artista_pk": artista.pk, "slug": artista.slug})


@api_view(["POST"])
@permission_classes([IsStaff])
def proposta_rebutjar(request: Request, pk: int) -> Response:
    p = get_object_or_404(PropostaArtista.objects.select_related("usuari"), pk=pk)
    p.estat = PropostaArtista.ESTAT_REBUTJAT
    p.save(update_fields=["estat"])
    log_staff_action(
        request,
        "proposta_rebutjar",
        target=p,
        artista_nom=p.nom,
        usuari_proposant=p.usuari.email if p.usuari_id else "",
    )
    if p.usuari_id:
        from comptes.notifications import notify_user_proposta_resolta

        notify_user_proposta_resolta(p, "rebutjada")
    return Response({"ok": True})


@api_view(["POST"])
@permission_classes([IsStaff])
def proposta_fusionar(request: Request, pk: int) -> Response:
    """Merge a pending proposta into an existing Artista.

    Body: `{"artista_pk": <int>}`. The target artist receives:
      * any Deezer IDs from the proposal that aren't already attached
        somewhere (conflicts on *other* artists abort the operation
        with 409 so staff can sort the triple-collision case out by
        hand);
      * any localitzacions (municipi_id preserved, manual entries
        kept as-is) that the target doesn't already have;
      * any social URLs the target doesn't already fill (never
        overwrite an existing value — staff curates, proposals propose).

    The proposta is marked `aprovat` with `artista_creat=<target>`
    so the user sees their submission acknowledged.
    """
    p = get_object_or_404(PropostaArtista.objects.select_related("usuari"), pk=pk)
    if p.estat != PropostaArtista.ESTAT_PENDENT:
        return Response({"error": "Ja processada."}, status=400)

    target_pk_raw = (request.data or {}).get("artista_pk")
    try:
        target = Artista.objects.get(pk=int(target_pk_raw))
    except (TypeError, ValueError, Artista.DoesNotExist):
        return Response({"error": "Artista de destí no trobat."}, status=404)

    # Any Deezer IDs the proposal brings that are already owned by a
    # DIFFERENT artist: abort. Merging those would require a second
    # merge (artist↔artist) which is a separate operation.
    wanted_deezer = p.get_deezer_id_list()
    foreign = (
        ArtistaDeezer.objects.filter(deezer_id__in=wanted_deezer)
        .exclude(artista=target)
        .select_related("artista")
    )
    if foreign.exists():
        ad = foreign.first()
        return Response(
            {
                "error": (
                    f"El Deezer ID {ad.deezer_id} pertany a «{ad.artista.nom}» "
                    f"(pk={ad.artista_id}), no a l'objectiu de fusió. "
                    "Resol això primer fusionant els dos artistes."
                )
            },
            status=409,
        )

    with transaction.atomic():
        # Attach every missing Deezer ID.
        existing_dz = set(target.deezer_ids.values_list("deezer_id", flat=True))
        for dz in wanted_deezer:
            if dz in existing_dz:
                continue
            ArtistaDeezer.objects.create(
                artista=target,
                deezer_id=dz,
                principal=not existing_dz,
            )
            existing_dz.add(dz)

        # Merge localitzacions (skip duplicates by municipi_id).
        existing_municipi_ids = set(
            target.localitats.filter(municipi__isnull=False).values_list(
                "municipi_id", flat=True
            )
        )
        for loc in p.localitzacions or []:
            mid = loc.get("municipi_id")
            manual = (loc.get("manual") or "").strip()
            if mid and mid not in existing_municipi_ids:
                try:
                    m = Municipi.objects.get(pk=int(mid))
                    ArtistaLocalitat.objects.create(artista=target, municipi=m)
                    existing_municipi_ids.add(m.pk)
                except (ValueError, Municipi.DoesNotExist):
                    pass
            elif manual:
                ArtistaLocalitat.objects.create(
                    artista=target, municipi=None, localitat_manual=manual
                )

        # Social URLs: only fill fields that are currently empty.
        for field, _ in Artista.SOCIAL_LINK_FIELDS:
            if getattr(target, field, ""):
                continue
            val = getattr(p, field, "")
            if val:
                setattr(target, field, val)

        # If the target was a pendent auto-discovery, a merge with a
        # human-curated proposal is a strong approval signal — flip
        # aprovat on but only when the target now satisfies the
        # aprovat-needs-Deezer invariant (which it does, we just
        # attached IDs).
        if target.pendent_review and target.deezer_ids.exists():
            target.aprovat = True
            target.pendent_review = False
        target.save()

        p.estat = PropostaArtista.ESTAT_APROVAT
        p.artista_creat = target
        p.save(update_fields=["estat", "artista_creat"])

    log_staff_action(
        request,
        "proposta_aprovar",
        target=p,
        action_taken="fusionat",
        artista_creat_id=target.pk,
        artista_nom=target.nom,
        usuari_proposant=p.usuari.email if p.usuari_id else "",
    )
    return Response({"ok": True, "artista_pk": target.pk, "slug": target.slug})
