"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Senyal diari (Last.fm raw feed)
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def senyal_list(request: Request) -> Response:
    qs = SenyalDiari.objects.select_related("canco", "canco__artista")
    data_filtre = request.GET.get("data", "")
    if data_filtre:
        qs = qs.filter(data=data_filtre)
    mena = request.GET.get("mena", "")
    if mena == "errors":
        qs = qs.filter(error=True)
    elif mena == "correccions":
        qs = qs.filter(corregit=True)
    elif mena == "confirmats":
        qs = qs.filter(canco__lastfm_confirmed=True)
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.filter(
            Q(canco__nom__icontains=cerca) | Q(canco__artista__nom__icontains=cerca)
        )
    qs = qs.order_by("-data")
    page, meta = _paginate(qs, request)
    rows = []
    for s in page.object_list:
        rows.append(
            {
                "pk": s.pk,
                "data": s.data.isoformat() if s.data else None,
                "canco_pk": s.canco_id,
                "canco_nom": s.canco.nom if s.canco else "",
                "canco_slug": s.canco.slug if s.canco else None,
                "artista_pk": (
                    s.canco.artista_id if s.canco and s.canco.artista_id else None
                ),
                "artista_nom": (
                    s.canco.artista.nom if s.canco and s.canco.artista else ""
                ),
                "lastfm_playcount": s.lastfm_playcount,
                "lastfm_listeners": s.lastfm_listeners,
                "error": s.error,
                "corregit": s.corregit,
                "lastfm_confirmed": (s.canco.lastfm_confirmed if s.canco else False),
            }
        )
    return Response({"results": rows, **meta})


@api_view(["POST"])
@permission_classes([IsStaff])
def senyal_acceptar_correccio(request: Request, canco_pk: int) -> Response:
    canco = get_object_or_404(Canco, pk=canco_pk)
    canco.lastfm_confirmed = True
    canco.save(update_fields=["lastfm_confirmed"])
    SenyalDiari.objects.filter(canco=canco, corregit=True).update(corregit=False)
    log_staff_action(
        request,
        "canco_edit",
        target=canco,
        field="lastfm_confirmed",
        new_value=True,
        source="senyal_accept_correction",
    )
    return Response({"ok": True})


@api_view(["POST"])
@permission_classes([IsStaff])
def canco_refetch_senyal(request: Request, pk: int) -> Response:
    """Retry the Last.fm signal lookup for a single Canco, on demand.

    After staff fixes `artista.lastfm_nom` or `canco.lastfm_nom`, the
    scheduled cron won't revisit today's failure until tomorrow — and
    a permanent error row stays flagged indefinitely. This endpoint
    replays the same lookup immediately with current values and writes
    a fresh SenyalDiari for today (overwriting any error/drift row).
    """
    from ingesta.clients.lastfm import get_track_info

    canco = get_object_or_404(Canco.objects.select_related("artista"), pk=pk)
    artist_name = canco.artista.lastfm_nom or canco.artista.nom
    track_name = canco.lastfm_lookup_nom
    result = get_track_info(artist_name, track_name)
    today = datetime.date.today()

    # Replace any existing row for today — we want the freshest truth.
    SenyalDiari.objects.filter(canco=canco, data=today).delete()

    if result is None:
        SenyalDiari.objects.create(
            canco=canco,
            data=today,
            lastfm_playcount=None,
            lastfm_listeners=None,
            lastfm_returned_track="",
            lastfm_returned_artista="",
            corregit=False,
            error=True,
            error_msg=(f"Last.fm lookup failed for '{artist_name}' / '{track_name}'"),
        )
        log_staff_action(
            request, "canco_edit", target=canco, source="refetch_senyal", ok=False
        )
        return Response(
            {
                "ok": False,
                "error": (
                    "Last.fm no ha tornat cap resultat. Revisa el Nom a "
                    "Last.fm de la cançó i de l'artista."
                ),
                "lookup": {"artist": artist_name, "track": track_name},
            },
            status=200,
        )

    from ingesta.management.commands.obtenir_senyal import _detect_drift

    returned_artist = result.get("returned_artist", "") or ""
    returned_track = result.get("returned_track", "") or ""
    is_drift = not canco.lastfm_confirmed and _detect_drift(
        artist_name, track_name, returned_artist, returned_track
    )
    SenyalDiari.objects.create(
        canco=canco,
        data=today,
        lastfm_playcount=result["playcount"],
        lastfm_listeners=result["listeners"],
        lastfm_returned_track=returned_track[:500],
        lastfm_returned_artista=returned_artist[:255],
        corregit=is_drift,
        error=False,
        error_msg="",
    )
    log_staff_action(
        request,
        "canco_edit",
        target=canco,
        source="refetch_senyal",
        ok=True,
        drift=is_drift,
    )
    return Response(
        {
            "ok": True,
            "playcount": result["playcount"],
            "listeners": result["listeners"],
            "drift": is_drift,
            "returned_artist": returned_artist,
            "returned_track": returned_track,
        }
    )
