"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Sol·licituds de gestió (UserArtista)
# ═════════════════════════════════════════════════════════════════════════


def _solicitud_row(ua) -> dict:
    return {
        "pk": ua.pk,
        "estat": ua.estat,
        "verificat": ua.verificat,
        "sollicitud_text": ua.sollicitud_text or "",
        "created_at": ua.created_at.isoformat() if ua.created_at else None,
        "usuari": {
            "pk": ua.usuari_id,
            "email": ua.usuari.email if ua.usuari_id else "",
            "username": ua.usuari.username if ua.usuari_id else "",
        },
        "artista": {
            "pk": ua.artista_id,
            "nom": ua.artista.nom if ua.artista_id else "",
            "slug": ua.artista.slug if ua.artista_id else "",
        },
    }


@api_view(["GET"])
@permission_classes([IsStaff])
def solicituds_list(request: Request) -> Response:
    qs = UserArtista.objects.select_related("usuari", "artista")
    verificat = request.GET.get("verificat", "")
    if verificat == "0":
        qs = qs.filter(verificat=False)
    elif verificat == "1":
        qs = qs.filter(verificat=True)
    qs = qs.order_by("-created_at")
    page, meta = _paginate(qs, request, default_per_page=25)
    return Response(
        {"results": [_solicitud_row(ua) for ua in page.object_list], **meta}
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def solicitud_toggle(request: Request, pk: int) -> Response:
    from django.utils import timezone

    from comptes.notifications import notify_user_solicitud_resolta

    ua = get_object_or_404(
        UserArtista.objects.select_related("usuari", "artista"), pk=pk
    )
    ua.verificat = not ua.verificat
    ua.estat = UserArtista.ESTAT_APROVAT if ua.verificat else UserArtista.ESTAT_PENDENT
    update_fields = ["verificat", "estat"]
    if ua.verificat:
        ua.aprovat_at = timezone.now()
        ua.aprovat_per = request.user
        ua.motiu_rebuig = ""
        update_fields += ["aprovat_at", "aprovat_per", "motiu_rebuig"]
    ua.save(update_fields=update_fields)
    log_staff_action(
        request,
        "sollicitud_aprovar" if ua.verificat else "sollicitud_rebutjar",
        target=ua,
        nou_estat=ua.estat,
        artista=ua.artista.nom,
        usuari=ua.usuari.email,
    )
    if ua.verificat:
        notify_user_solicitud_resolta(ua, "aprovada")
    return Response({"ok": True, "estat": ua.estat, "verificat": ua.verificat})


@api_view(["POST"])
@permission_classes([IsStaff])
def solicitud_rebutjar(request: Request, pk: int) -> Response:
    from comptes.notifications import notify_user_solicitud_resolta

    ua = get_object_or_404(
        UserArtista.objects.select_related("usuari", "artista"), pk=pk
    )
    motiu = (request.data.get("motiu") or "").strip() if request.data else ""
    # Fase 1.5.A bug fix: also flip verificat=False so a previously
    # approved-then-rejected user actually loses edit rights. The old
    # path only set estat='rebutjat' but left verificat untouched,
    # leaking auth (the `_gestor_check` predicate keyed on verificat).
    ua.verificat = False
    ua.estat = UserArtista.ESTAT_REBUTJAT
    ua.motiu_rebuig = motiu
    ua.save(update_fields=["verificat", "estat", "motiu_rebuig"])
    log_staff_action(
        request,
        "sollicitud_rebutjar",
        target=ua,
        artista=ua.artista.nom,
        usuari=ua.usuari.email,
        motiu=motiu,
    )
    notify_user_solicitud_resolta(ua, "rebutjada")
    return Response({"ok": True})
