"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.db import transaction
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes
from rest_framework.request import Request
from rest_framework.response import Response

from music.audit import log_staff_action
from music.constants import (
    MOTIUS_REBUIG,
    MOTIUS_VALIDS,
    TERRITORI_NOMS,
    TERRITORIS_AGREGATS,
    TERRITORIS_FIXOS,
    TERRITORIS_OPCIONALS,
)
from music.ml import recalcular_ml_si_cal
from music.models import (
    Artista,
    Canco,
)
from music.services import (
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    TopProvisional,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.

Usuari = get_user_model()
# Effective (post soft-cap) plays are derived from the persisted score the
# SAME way the per-cançó transparency panel does. Reuse that exact function
# so the staff list reconciles to the byte with `TopBreakdownPanel`
# (web/api/canco_views.py::canco_top_breakdown). No re-implementation of the
# adaptive knee, no gate touch, no write.
from web.api.canco_views import _derive_plays_eff

# Shared helpers from the staff package.
from web.api.staff._common import IsStaff

# ═════════════════════════════════════════════════════════════════════════
# Ranking provisional
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def canco_top_breakdown(request: Request, pk: int) -> Response:
    """Per-territori algorithm breakdown for a single cançó.

    Returns every TopProvisional row for this cançó (one per
    territori), with the weekly plays, age / past-top / monopoli
    factors and the resulting score. Useful to explain to staff (and
    to artist managers) why a track lands where it does.
    """
    canco = get_object_or_404(Canco, pk=pk)
    qs = TopProvisional.objects.filter(canco_id=canco.pk).order_by("territori")
    return Response(
        {
            "canco_pk": canco.pk,
            "canco_nom": canco.nom,
            "entries": [
                {
                    "territori": rp.territori,
                    "territori_nom": TERRITORI_NOMS.get(rp.territori, rp.territori),
                    "posicio": rp.posicio,
                    "escoltes_setmanals": rp.escoltes_setmanals,
                    "age_factor": rp.age_factor,
                    "past_top_factor": rp.past_top_factor,
                    "monopoli_factor": rp.monopoli_factor,
                    "score_final": rp.score_setmanal,
                    "data_calcul": rp.data_calcul,
                }
                for rp in qs
            ],
        }
    )


# Staff top picker: fixed PPCC origins first, then optionals (incl.
# CAR), then aggregated buckets (ALT, PPCC). Built from the canonical
# subsets so a new territori only needs adding to music/constants.
TOP_TERRITORIS = [
    (c, TERRITORI_NOMS[c])
    for c in (*TERRITORIS_FIXOS, *TERRITORIS_OPCIONALS, *TERRITORIS_AGREGATS)
]


@api_view(["GET"])
@permission_classes([IsStaff])
def top_list(request: Request) -> Response:
    territori = request.GET.get("territori", "CAT")
    if territori not in {c for c, _ in TOP_TERRITORIS}:
        territori = "CAT"
    qs = (
        TopProvisional.objects.filter(territori=territori)
        .select_related("canco", "canco__artista")
        .order_by("posicio")
    )
    entries = []
    for rp in qs:
        # Derived from the persisted score (score / age·past_top·monopoli),
        # NOT recomputed — so it matches the breakdown panel exactly and is
        # read-only. Equals `escoltes_setmanals` when the soft-cap left the
        # row uncompressed.
        plays_eff, soft_cap_aplicat = _derive_plays_eff(rp)
        entries.append(
            {
                "pk": rp.pk,
                "posicio": rp.posicio,
                "canco_pk": rp.canco_id,
                "canco_nom": rp.canco.nom if rp.canco else "",
                "canco_slug": rp.canco.slug if rp.canco else None,
                "artista_nom": (
                    rp.canco.artista.nom if rp.canco and rp.canco.artista else ""
                ),
                "artista_pk": (
                    rp.canco.artista_id if rp.canco and rp.canco.artista else None
                ),
                "escoltes_setmanals": rp.escoltes_setmanals,
                "escoltes_efectives": int(round(plays_eff)),
                "soft_cap_aplicat": soft_cap_aplicat,
                "age_factor": rp.age_factor,
                "past_top_factor": rp.past_top_factor,
                "monopoli_factor": rp.monopoli_factor,
                "score_final": rp.score_setmanal,
            }
        )
    return Response(
        {
            "territori": territori,
            "territoris": [{"codi": c, "nom": n} for c, n in TOP_TERRITORIS],
            "motius": list(MOTIUS_REBUIG),
            "entries": entries,
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def top_accio(request: Request) -> Response:
    data = request.data or {}
    action = data.get("action", "")
    ids = data.get("ids") or []
    motiu = data.get("motiu", "")
    if not ids:
        return Response({"error": "No has seleccionat cap entrada."}, status=400)
    if motiu not in MOTIUS_VALIDS:
        return Response({"error": "Motiu invàlid."}, status=400)
    entries = TopProvisional.objects.filter(pk__in=ids).select_related(
        "canco__artista", "canco__album"
    )
    if action == "rebutjar_canco":
        total = 0
        with transaction.atomic():
            for rp in entries:
                rebutjar_canco(rp.canco, motiu)
                log_staff_action(
                    request,
                    "canco_rebutjar",
                    target=rp.canco,
                    motiu=motiu,
                    source="provisional_ranking",
                )
                rp.delete()
                total += 1
        recalcular_ml_si_cal()
        return Response({"ok": True, "n": total})
    if action == "rebutjar_artista":
        artista_ids = set(entries.values_list("canco__artista_id", flat=True))
        total_cancons = 0
        with transaction.atomic():
            for a in Artista.objects.filter(pk__in=artista_ids):
                total_cancons += rebutjar_artista(a, motiu)
                log_staff_action(
                    request,
                    "artista_rebutjar",
                    target=a,
                    motiu=motiu,
                    source="provisional_ranking",
                )
            TopProvisional.objects.filter(canco__artista_id__in=artista_ids).delete()
        recalcular_ml_si_cal()
        return Response(
            {"ok": True, "n_artistes": len(artista_ids), "n_cancons": total_cancons}
        )
    return Response({"error": "Acció desconeguda."}, status=400)
