"""Staff endpoint module — extracted from the legacy staff_views.py.

Generated by Sprint C (2026-04-25). Backward compatibility is
preserved via `web/api/staff_views.py`, which re-exports every public
name from the per-area modules. Keep changes inside the appropriate
module and let the shim handle the re-export.
"""

from __future__ import annotations

import datetime

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db import IntegrityError, transaction
from django.db.models import (
    Avg,
    Case,
    Count,
    Exists,
    F,
    IntegerField,
    Max,
    Min,
    OuterRef,
    Q,
    Value,
    When,
)
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404
from django.utils.dateparse import parse_date
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import BasePermission
from rest_framework.request import Request
from rest_framework.response import Response

from comptes.models import Feedback, PropostaArtista, Publicacio, UserArtista
from music.audit import log_staff_action
from music.constants import MOTIUS_REBUIG, MOTIUS_VALIDS, TERRITORI_NOMS
from music.ml import recalcular_ml_si_cal
from music.models import (
    Album,
    Artista,
    ArtistaDeezer,
    ArtistaLocalitat,
    Canco,
    HistorialRevisio,
    Municipi,
    StaffAuditLog,
)
from music.services import (
    aprovar_canco,
    rebutjar_album,
    rebutjar_artista,
    rebutjar_canco,
)
from ranking.models import (
    ConfiguracioGlobal,
    SenyalDiari,
    TopProvisional,
    TopSetmanal,
)

# Accent + apostrophe insensitive search helpers shared with the
# public endpoints — see `web/api/search_utils.py`.
from web.api.search_utils import normalize_search_term as _normalize_search_term
from web.api.search_utils import unaccent_field as _unaccent_field
from web.api.staff.propostes import _proposta_row
from web.api.staff.solicituds import _solicitud_row

Usuari = get_user_model()
# Shared helpers from the staff package.
from web.api.staff._common import IsStaff, _paginate

# ═════════════════════════════════════════════════════════════════════════
# Usuaris
# ═════════════════════════════════════════════════════════════════════════


@api_view(["GET"])
@permission_classes([IsStaff])
def usuaris_list(request: Request) -> Response:
    totp_exists = TOTPDevice.objects.filter(user=OuterRef("pk"), confirmed=True)
    qs = Usuari.objects.select_related("perfil", "perfil__localitat").annotate(
        n_propostes=Count("propostes_artista", distinct=True),
        n_sollicituds_aprovades=Count(
            "artistes_vinculats",
            filter=Q(artistes_vinculats__estat="aprovat"),
            distinct=True,
        ),
        n_publicacions=Count("publicacions", distinct=True),
        has_totp=Exists(totp_exists),
    )
    estat = request.GET.get("estat", "")
    if estat == "actius":
        qs = qs.filter(is_active=True)
    elif estat == "inactius":
        qs = qs.filter(is_active=False)
    rol = request.GET.get("rol", "")
    if rol == "staff":
        qs = qs.filter(is_staff=True)
    elif rol == "usuari":
        qs = qs.filter(is_staff=False)
    directori = request.GET.get("directori", "")
    if directori == "1":
        qs = qs.filter(perfil__visible_directori=True)
    elif directori == "0":
        qs = qs.filter(perfil__visible_directori=False)
    cerca = (request.GET.get("q") or "").strip()
    if cerca:
        qs = qs.filter(
            Q(email__icontains=cerca)
            | Q(username__icontains=cerca)
            | Q(perfil__nom_public__icontains=cerca)
        )
    qs = qs.order_by("-date_joined")
    page, meta = _paginate(qs, request)
    results = []
    for u in page.object_list:
        p = getattr(u, "perfil", None)
        localitat_nom = None
        if p and p.localitat_id:
            m = p.localitat
            localitat_nom = f"{m.nom}, {m.comarca}" if m else None
        results.append(
            {
                "pk": u.pk,
                "email": u.email,
                "username": u.username,
                "is_active": u.is_active,
                "is_staff": u.is_staff,
                "has_totp": bool(u.has_totp),
                "date_joined": (u.date_joined.isoformat() if u.date_joined else None),
                "last_login": (u.last_login.isoformat() if u.last_login else None),
                "n_propostes": u.n_propostes,
                "n_sollicituds_aprovades": u.n_sollicituds_aprovades,
                "n_publicacions": u.n_publicacions,
                # Profile flags — None when no PerfilUsuari row yet.
                "nom_public": p.nom_public if p else "",
                "rol_musical": p.rol_musical if p else None,
                "localitat": localitat_nom,
                "visible_directori": bool(p and p.visible_directori),
                "obert_colaboracions": bool(p and p.obert_colaboracions),
                "imatge_url": (p.imatge_url if p and p.imatge_url else None),
            }
        )
    return Response({"results": results, **meta})


@api_view(["GET"])
@permission_classes([IsStaff])
def usuari_detail(request: Request, pk: int) -> Response:
    u = get_object_or_404(Usuari, pk=pk)
    propostes = list(
        PropostaArtista.objects.filter(usuari=u)
        .select_related("artista_creat")
        .order_by("-created_at")
    )
    sollicituds = list(
        UserArtista.objects.filter(usuari=u)
        .select_related("artista")
        .order_by("-created_at")
    )
    audit_sobre = (
        StaffAuditLog.objects.filter(target_type="usuari", target_id=u.pk)
        .select_related("actor")
        .order_by("-created_at")[:30]
    )
    audit_per = []
    if u.is_staff:
        audit_per = list(
            StaffAuditLog.objects.filter(actor=u).order_by("-created_at")[:30]
        )
    has_totp = TOTPDevice.objects.filter(user=u, confirmed=True).exists()
    return Response(
        {
            "pk": u.pk,
            "email": u.email,
            "username": u.username,
            "is_active": u.is_active,
            "is_staff": u.is_staff,
            "date_joined": u.date_joined.isoformat() if u.date_joined else None,
            "last_login": u.last_login.isoformat() if u.last_login else None,
            "has_totp": has_totp,
            "propostes": [_proposta_row(p) for p in propostes],
            "sollicituds": [_solicitud_row(s) for s in sollicituds],
            "audit_sobre": [
                {
                    "pk": r.pk,
                    "action": r.action,
                    "actor_email": r.actor.email if r.actor else "",
                    "created_at": r.created_at.isoformat() if r.created_at else None,
                    "target_label": r.target_label or "",
                }
                for r in audit_sobre
            ],
            "audit_per_usuari": [
                {
                    "pk": r.pk,
                    "action": r.action,
                    "created_at": r.created_at.isoformat() if r.created_at else None,
                    "target_label": r.target_label or "",
                }
                for r in audit_per
            ],
        }
    )


@api_view(["POST"])
@permission_classes([IsStaff])
def usuari_toggle_actiu(request: Request, pk: int) -> Response:
    u = get_object_or_404(Usuari, pk=pk)
    if u.pk == request.user.pk:
        return Response({"error": "No pots desactivar-te a tu mateix."}, status=400)
    if u.is_staff:
        return Response(
            {
                "error": (
                    "No es pot desactivar un usuari staff des del panell. "
                    "Treu-li is_staff via SSH primer."
                )
            },
            status=400,
        )
    u.is_active = not u.is_active
    u.save(update_fields=["is_active"])
    action = "usuari_reactivar" if u.is_active else "usuari_desactivar"
    log_staff_action(
        request,
        action,
        target=u,
        email=u.email,
        nou_estat_actiu=u.is_active,
    )
    return Response({"ok": True, "is_active": u.is_active})


@api_view(["POST"])
@permission_classes([IsStaff])
def usuari_reset_2fa(request: Request, pk: int) -> Response:
    u = get_object_or_404(Usuari, pk=pk)
    totp_n = TOTPDevice.objects.filter(user=u).count()
    static_n = StaticDevice.objects.filter(user=u).count()
    if totp_n == 0 and static_n == 0:
        return Response({"ok": True, "msg": "L'usuari no té cap dispositiu 2FA."})
    TOTPDevice.objects.filter(user=u).delete()
    StaticDevice.objects.filter(user=u).delete()
    log_staff_action(
        request,
        "usuari_reset_2fa",
        target=u,
        email=u.email,
        totp_removed=totp_n,
        static_removed=static_n,
    )
    return Response({"ok": True, "totp_removed": totp_n, "static_removed": static_n})


@api_view(["POST"])
@permission_classes([IsStaff])
def usuari_esborrar(request: Request, pk: int) -> Response:
    """Hard-delete a user account. Staff-only, refuses to delete other staff."""
    u = get_object_or_404(Usuari, pk=pk)
    if u.is_staff:
        return Response(
            {"error": "No pots esborrar un altre staff des d'aquí."}, status=400
        )
    if u.pk == request.user.pk:
        return Response(
            {"error": "Usa el flux de compte per auto-esborrar-te."}, status=400
        )
    email = u.email
    label = str(u)
    pk_val = u.pk
    u.delete()
    log_staff_action(
        request,
        "usuari_esborrar",
        target=None,
        target_id_deleted=pk_val,
        target_label_deleted=label,
        email=email,
    )
    return Response({"ok": True})


@api_view(["POST"])
@permission_classes([IsStaff])
def usuari_reenviar_verificacio(request: Request, pk: int) -> Response:
    """Resend the account-activation email to an inactive user.

    Safeguard against the "blocked forever" trap: if a user never
    clicked their original activation link, staff can regenerate it
    without having to delete + recreate the account.
    """
    from comptes.views import _send_verification_email

    u = get_object_or_404(Usuari, pk=pk)
    if not u.email:
        return Response({"error": "L'usuari no té email."}, status=400)
    if u.is_active:
        return Response({"error": "L'usuari ja té el compte activat."}, status=400)
    _send_verification_email(request, u)
    log_staff_action(
        request,
        "usuari_reenviar_verificacio",
        target=u,
        email=u.email,
    )
    return Response({"ok": True, "email": u.email})


@api_view(["POST"])
@permission_classes([IsStaff])
def usuari_enviar_reset_password(request: Request, pk: int) -> Response:
    """Send a password-reset email to the user.

    Generates a token via Django's `default_token_generator` and builds
    a link to our custom `/compte/nova-clau/<uidb64>/<token>/` flow.
    """
    from django.contrib.auth.tokens import default_token_generator
    from django.core.mail import send_mail
    from django.utils.encoding import force_bytes
    from django.utils.http import urlsafe_base64_encode

    u = get_object_or_404(Usuari, pk=pk)
    if not u.email:
        return Response({"error": "L'usuari no té email."}, status=400)

    uidb64 = urlsafe_base64_encode(force_bytes(u.pk))
    token = default_token_generator.make_token(u)
    scheme = "https" if request.is_secure() else "http"
    host = request.get_host()
    url = f"{scheme}://{host}/compte/nova-clau/{uidb64}/{token}/"

    from django.template.loader import render_to_string

    subject = "TopQuaranta · nova contrasenya"
    text_body = (
        f"Hola,\n\n"
        f"L'equip de TopQuaranta ha generat un enllaç perquè estableixis una "
        f"nova contrasenya del teu compte ({u.email}).\n\n"
        f"{url}\n\n"
        f"L'enllaç caduca a les 24 hores. Si no has demanat aquest canvi, "
        f"pots ignorar aquest missatge.\n"
    )
    html_body = render_to_string(
        "comptes/email_reset_password.html",
        {"link": url, "email": u.email, "subject": subject},
    )
    try:
        send_mail(
            subject,
            text_body,
            None,
            [u.email],
            fail_silently=False,
            html_message=html_body,
        )
    except Exception as e:
        return Response({"error": f"No s'ha pogut enviar l'email: {e}"}, status=500)

    log_staff_action(
        request,
        "usuari_enviar_reset_password",
        target=u,
        email=u.email,
    )
    return Response({"ok": True, "email": u.email})
