# Generated by Django 5.2 on 2026-04-25 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0011_alter_perfilusuari_rol_musical"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuari",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AddField(
            model_name="propostaartista",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AddField(
            model_name="propostaartista",
            name="twitter_url",
            field=models.URLField(
                blank=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
