# Generated by Django 5.2 on 2026-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0012_perfilusuari_twitter_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuari",
            name="consent_newsletter_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="consent_termes_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted the terms + privacy policy.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="consent_termes_versio",
            field=models.CharField(
                blank=True,
                help_text="Version (publication date) of the docs accepted.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="vol_newsletter",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
