# Generated by Django 5.2.13 on 2026-05-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0013_legal_consent_fields"),
        ("music", "0061_album_source_deezer_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userartista",
            index=models.Index(
                fields=["usuari", "-created_at"], name="comptes_use_usuari__b271f8_idx"
            ),
        ),
    ]
