# Generated by Django 6.0.5 on 2026-05-20 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0017_userartista_email_aprovacio_at"),
        ("music", "0075_historialrevisio_reconsiderada"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudRevisio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pendents_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Llista de Canco.pk pendents de verificar incloses.",
                    ),
                ),
                (
                    "rebutjades_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Llista de dicts amb el snapshot de cada rebutjada inclosa: {historial_pk, deezer_id, isrc, nom, album_nom, motiu}.",
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent"),
                            ("revisada", "En revisió"),
                            ("resolta", "Resolta"),
                        ],
                        db_index=True,
                        default="pendent",
                        max_length=20,
                    ),
                ),
                ("nota_resolucio", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sollicituds_revisio",
                        to="music.artista",
                    ),
                ),
                (
                    "gestor",
                    models.ForeignKey(
                        help_text="Gestor que va crear la sol·licitud.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sollicituds_revisio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolt_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sollicituds_revisio_resoltes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sol·licitud de revisió",
                "verbose_name_plural": "Sol·licituds de revisió",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["estat", "-created_at"],
                        name="comptes_sol_estat_3a4a14_idx",
                    ),
                    models.Index(
                        fields=["artista", "-created_at"],
                        name="comptes_sol_artista_7bdeb6_idx",
                    ),
                ],
            },
        ),
    ]
