# Generated by Django 6.0.5 on 2026-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0018_solicitudrevisio"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipus", models.CharField(max_length=30)),
                ("territori", models.CharField(blank=True, default="", max_length=4)),
                (
                    "setmana",
                    models.DateField(
                        db_index=True, help_text="Dilluns de la setmana ISO del top."
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("narrative_html", models.TextField(blank=True, default="")),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent (s'enviarà)"),
                            ("enviat", "Enviat"),
                            ("cancellat", "Cancel·lat"),
                        ],
                        db_index=True,
                        default="pendent",
                        max_length=20,
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[("motor", "Motor narratiu"), ("llm", "LLM")],
                        default="motor",
                        max_length=10,
                    ),
                ),
                (
                    "editat",
                    models.BooleanField(
                        default=False,
                        help_text="True si l'staff ha editat subject o narrative_html.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enviat_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Esborrany de newsletter",
                "verbose_name_plural": "Esborranys de newsletter",
                "ordering": ["-setmana"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipus", "territori", "setmana"),
                        name="newsletterdraft_unique_slot",
                    )
                ],
            },
        ),
    ]
