# Generated by Django 6.0.5 on 2026-06-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0019_newsletterdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterdraft',
            name='publicacio',
            field=models.OneToOneField(blank=True, help_text="Publicació pública creada a partir d'aquest esborrany (pont Newsletter→Comunitat). Null si mai s'ha publicat al feed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_origen', to='comptes.publicacio'),
        ),
    ]
