# Generated by Django 6.0.5 on 2026-06-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0020_newsletterdraft_publicacio"),
        ("music", "0091_artista_nom_normalitzat"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuari",
            name="vol_avis_top",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name="AvisTopEnviat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setmana", models.DateField(help_text="ISO Monday of the top week.")),
                ("enviat_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos_top",
                        to="music.artista",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artista", "setmana"),
                        name="avistopenviat_unique_artista_setmana",
                    )
                ],
            },
        ),
    ]
