# Generated by Django 6.0.5 on 2026-06-14 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0021_perfilusuari_vol_avis_top_avistopenviat"),
    ]

    operations = [
        migrations.AddField(
            model_name="missatge",
            name="ocult",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="accepta_dm",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="BloqueigUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueigs_rebuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueigs_fets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["blocker", "blocked"],
                        name="comptes_blo_blocker_29054e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="bloqueigusuari_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DenunciaUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipus",
                    models.CharField(
                        choices=[
                            ("usuari", "Usuari"),
                            ("publicacio", "Publicació"),
                            ("comentari", "Comentari"),
                            ("missatge", "Missatge"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("motiu", models.TextField(blank=True, max_length=2000)),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent"),
                            ("revisada", "Revisada"),
                            ("desestimada", "Desestimada"),
                        ],
                        db_index=True,
                        default="pendent",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comentari",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comptes.comentari",
                    ),
                ),
                (
                    "missatge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comptes.missatge",
                    ),
                ),
                (
                    "publicacio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comptes.publicacio",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncies_fetes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolt_per",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denuncies_resoltes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuari_denunciat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncies_rebudes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["estat", "-created_at"],
                        name="comptes_den_estat_2cc718_idx",
                    )
                ],
            },
        ),
    ]
