# Generated by Django 6.0.5 on 2026-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0022_missatge_ocult_perfilusuari_accepta_dm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuari",
            name="busca",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="generes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="perfilusuari",
            name="nivell",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aspirant", "Vull ser músic"),
                    ("amateur", "Amateur"),
                    ("semipro", "Semiprofessional"),
                    ("professional", "Professional"),
                ],
                max_length=20,
            ),
        ),
    ]
