# Generated by Django 5.2 on 2026-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram_feed", "Instagram · Feed"),
                            ("instagram_story", "Instagram · Stories"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "tipus",
                    models.CharField(
                        choices=[
                            ("top_ppcc", "Top global"),
                            ("top_territorial", "Top territorial"),
                            ("nous_albums", "Nous àlbums"),
                            ("nous_singles", "Nous singles"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("territori", models.CharField(blank=True, default="", max_length=4)),
                (
                    "setmana",
                    models.DateField(
                        db_index=True, help_text="Monday of the ISO week."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent"),
                            ("publicat", "Publicat"),
                            ("error", "Error"),
                            ("omes", "Omès"),
                        ],
                        db_index=True,
                        default="pendent",
                        max_length=20,
                    ),
                ),
                ("instagram_media_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publicació social",
                "verbose_name_plural": "Publicacions socials",
                "ordering": ["-setmana", "platform", "tipus"],
                "unique_together": {("platform", "tipus", "territori", "setmana")},
            },
        ),
    ]
