# Generated by Django 5.2 on 2026-04-27 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_instagram_auth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram_feed", "Instagram · Feed"),
                    ("instagram_story", "Instagram · Stories"),
                    ("mastodon", "Mastodon"),
                    ("bluesky", "Bluesky"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BlueskyAuth",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("handle", models.CharField(blank=True, default="", max_length=120)),
                (
                    "app_password",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "did",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Decentralised identifier (resolved on first auth).",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorització Bluesky",
                "verbose_name_plural": "Autoritzacions Bluesky",
            },
        ),
        migrations.CreateModel(
            name="MastodonAuth",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instance_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("handle", models.CharField(blank=True, default="", max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorització Mastodon",
                "verbose_name_plural": "Autoritzacions Mastodon",
            },
        ),
    ]
