# Generated by Django 5.2 on 2026-04-27 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_socialpost_platform_blueskyauth_mastodonauth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram_feed", "Instagram · Feed"),
                    ("instagram_story", "Instagram · Stories"),
                    ("mastodon", "Mastodon"),
                    ("bluesky", "Bluesky"),
                    ("telegram", "Telegram"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TelegramAuth",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("bot_token", models.CharField(blank=True, default="", max_length=200)),
                (
                    "chat_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Channel handle (e.g. @topquaranta) or numeric ID.",
                        max_length=120,
                    ),
                ),
                (
                    "bot_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-resolved label (e.g. 'topquaranta_bot').",
                        max_length=80,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorització Telegram",
                "verbose_name_plural": "Autoritzacions Telegram",
            },
        ),
    ]
