# Generated by Django 5.2.13 on 2026-05-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_alter_socialpost_platform_telegramauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram_feed", "Instagram · Feed"),
                    ("instagram_story", "Instagram · Stories"),
                    ("mastodon", "Mastodon"),
                    ("bluesky", "Bluesky"),
                    ("telegram", "Telegram"),
                    ("newsletter", "Newsletter"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="tipus",
            field=models.CharField(
                choices=[
                    ("top_ppcc", "Top global"),
                    ("top_territorial", "Top territorial"),
                    ("nous_albums", "Nous àlbums"),
                    ("nous_singles", "Nous singles"),
                ],
                max_length=30,
            ),
        ),
    ]
