# Generated by Django 6.0.5 on 2026-07-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0091_artista_nom_normalitzat"),
        ("social", "0006_narrativephraseusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitacioColaboracioIG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_snapshot", models.CharField(max_length=64)),
                ("ig_media_id", models.CharField(db_index=True, max_length=40)),
                (
                    "tipus_publicacio",
                    models.CharField(
                        choices=[
                            ("top_ppcc", "Top global"),
                            ("top_territorial", "Top territorial"),
                            ("nous_albums", "Nous àlbums"),
                            ("nous_singles", "Nous singles"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_invitacio", models.DateTimeField(db_index=True)),
                (
                    "estat",
                    models.CharField(
                        choices=[
                            ("pendent", "Pendent"),
                            ("acceptada", "Acceptada"),
                            ("rebutjada", "Rebutjada"),
                        ],
                        default="pendent",
                        max_length=12,
                    ),
                ),
                ("data_resolucio", models.DateTimeField(blank=True, null=True)),
                (
                    "artista",
                    models.ForeignKey(
                        help_text="Artist we invited as a collaborator.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitacions_ig",
                        to="music.artista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitació de col·laboració IG",
                "verbose_name_plural": "Invitacions de col·laboració IG",
                "indexes": [
                    models.Index(
                        fields=["estat", "data_invitacio"],
                        name="social_invi_estat_518cec_idx",
                    ),
                    models.Index(
                        fields=["artista", "estat"],
                        name="social_invi_artista_1262ef_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artista", "ig_media_id"),
                        name="invitaciocolaboracioig_uniq_artista_media",
                    )
                ],
            },
        ),
    ]
