# Generated by Django 6.0.5 on 2026-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_invitaciocolaboracioig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitaciocolaboracioig",
            name="estat",
            field=models.CharField(
                choices=[
                    ("pendent", "Pendent"),
                    ("acceptada", "Acceptada"),
                    ("rebutjada", "Rebutjada"),
                    ("caducada", "Caducada"),
                ],
                default="pendent",
                max_length=12,
            ),
        ),
    ]
