# Generated by Django 6.0.5 on 2026-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_alter_invitaciocolaboracioig_estat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitaciocolaboracioig",
            name="tipus_publicacio",
            field=models.CharField(
                choices=[
                    ("top_ppcc", "Top global"),
                    ("top_territorial", "Top territorial"),
                    ("nous_albums", "Nous àlbums"),
                    ("nous_singles", "Nous singles"),
                    ("moviment", "Moviment de la setmana"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="tipus",
            field=models.CharField(
                choices=[
                    ("top_ppcc", "Top global"),
                    ("top_territorial", "Top territorial"),
                    ("nous_albums", "Nous àlbums"),
                    ("nous_singles", "Nous singles"),
                    ("moviment", "Moviment de la setmana"),
                ],
                max_length=30,
            ),
        ),
    ]
