# Generated by Django 6.0.5 on 2026-08-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0101_artista_instagram_suggerits_descartats"),
        ("social", "0009_alter_invitaciocolaboracioig_tipus_publicacio_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="socialpost",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="slot_key",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AlterField(
            model_name="invitaciocolaboracioig",
            name="tipus_publicacio",
            field=models.CharField(
                choices=[
                    ("top_ppcc", "Top global"),
                    ("top_territorial", "Top territorial"),
                    ("nous_albums", "Nous àlbums"),
                    ("nous_singles", "Nous singles"),
                    ("moviment", "Moviment de la setmana"),
                    ("canco_dia", "La cançó del dia"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="socialpost",
            name="tipus",
            field=models.CharField(
                choices=[
                    ("top_ppcc", "Top global"),
                    ("top_territorial", "Top territorial"),
                    ("nous_albums", "Nous àlbums"),
                    ("nous_singles", "Nous singles"),
                    ("moviment", "Moviment de la setmana"),
                    ("canco_dia", "La cançó del dia"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialpost",
            unique_together={("platform", "tipus", "territori", "setmana", "slot_key")},
        ),
        migrations.CreateModel(
            name="SondaStoryIG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                ("franja", models.CharField(max_length=10)),
                (
                    "story_media_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reach", models.PositiveIntegerField(blank=True, null=True)),
                ("baseline_mediana", models.FloatField(blank=True, null=True)),
                ("baseline_mad", models.FloatField(blank=True, null=True)),
                ("reaccio_auto", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sondes_ig",
                        to="music.artista",
                    ),
                ),
                (
                    "canco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sondes_ig",
                        to="music.canco",
                    ),
                ),
                (
                    "socialpost",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sondes",
                        to="social.socialpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sonda de story IG",
                "verbose_name_plural": "Sondes de story IG",
                "ordering": ["-data", "franja"],
                "indexes": [
                    models.Index(
                        fields=["artista", "-data"],
                        name="social_sond_artista_322d12_idx",
                    ),
                    models.Index(
                        fields=["reaccio_auto", "-data"],
                        name="social_sond_reaccio_35c598_idx",
                    ),
                ],
                "unique_together": {("data", "franja")},
            },
        ),
    ]
