# Generated by Django 5.2 on 2026-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0010_remove_configuracioglobal_max_factor_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingprovisional",
            name="age_factor",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rankingprovisional",
            name="monopoli_factor",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rankingprovisional",
            name="past_top_factor",
            field=models.FloatField(null=True),
        ),
    ]
