# Generated by Django 5.2 on 2026-04-25 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0013_rename_models_to_top"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="topprovisional",
            new_name="ranking_top_territo_8f6300_idx",
            old_name="ranking_ran_territo_498143_idx",
        ),
        migrations.RenameIndex(
            model_name="topsetmanal",
            new_name="ranking_top_setmana_ace8bb_idx",
            old_name="ranking_ran_setmana_05f28b_idx",
        ),
        migrations.RenameIndex(
            model_name="topsetmanal",
            new_name="ranking_top_territo_14d239_idx",
            old_name="ranking_ran_territo_dd327c_idx",
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="min_escoltes_top",
            field=models.IntegerField(
                default=5,
                help_text="Cançons amb menys d'aquestes escoltes setmanals queden fora del top. Si això fa que un territori no arribi a 40 cançons, el top és més curt — no s'omple amb soroll.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
