# Generated by Django 5.2 on 2026-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0014_add_min_escoltes_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="fase_distribucio",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Phase 1: només dissabte feed+stories PPCC. Phase 2: + dimecres territorial rotatori. Phase 3: + dilluns segon territorial. Phase 4: + divendres novetats singles. Phase 5: + dimarts novetats àlbums. Pujar de fase requereix avaluar Instagram Insights (criteris a docs/architecture/pipeline.md).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="instagram_actiu",
            field=models.BooleanField(
                default=True,
                help_text="Kill switch global. Si False, `publicar_social` surt immediatament sense fer res (els cron entries marquen 'omès').",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="story_max_cancons_ppcc",
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text="Quantes cançons del top PPCC publicar com a stories individuals. Per defecte 40 (totes); si la story completion rate cau per sota del 25 % al story #N, baixa aquí a N.",
            ),
        ),
    ]
