# Generated by Django 5.2 on 2026-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0015_sprint_i_instagram"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="bluesky_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Kill switch per al cron de Bluesky. Si False, `publicar_bluesky` surt sense fer res.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="mastodon_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Kill switch per al cron de Mastodon. Si False, `publicar_mastodon` surt sense fer res.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="newsletter_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Kill switch per al cron de newsletter setmanal. Si False, `enviar_newsletter` surt sense fer res.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="rss_actiu",
            field=models.BooleanField(
                default=True,
                help_text="Si False, els feeds /rss/*.xml retornen 503 (per a casos d'emergència — habitualment està sempre actiu).",
            ),
        ),
    ]
