# Generated by Django 5.2 on 2026-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0016_configuracioglobal_bluesky_actiu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="telegram_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Kill switch per al cron de Telegram. Si False, `publicar_canal --channel telegram` surt sense fer res.",
            ),
        ),
    ]
