# Generated by Django 6.0.4 on 2026-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0017_configuracioglobal_telegram_actiu"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="delay_bluesky_min",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minuts de retard addicional per a Bluesky. Tope 180.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="delay_instagram_min",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minuts de retard addicional per a publicar_social (IG). 0 = publica al moment cron. Tope 180.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="delay_mastodon_min",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minuts de retard addicional per a Mastodon. Tope 180.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="delay_newsletter_min",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minuts de retard addicional per a newsletter. Tope 180.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="delay_telegram_min",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minuts de retard addicional per a Telegram. Tope 180.",
            ),
        ),
    ]
