# Generated by Django 6.0.5 on 2026-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0018_configuracioglobal_delay_bluesky_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="distribucio_activa",
            field=models.BooleanField(
                default=True,
                help_text="Interruptor mestre de distribució. Si False, cap dels sis canals publica (IG, Mastodon, Bluesky, Telegram, newsletter, RSS). Independent dels switches per canal i de fase_distribucio.",
            ),
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="instagram_actiu",
            field=models.BooleanField(
                default=True,
                help_text="Switch per canal d'Instagram. Si False (o el mestre `distribucio_activa` False), `publicar_social` surt sense fer res. NO és el switch global; per a això hi ha `distribucio_activa`.",
            ),
        ),
    ]
