# Generated by Django 6.0.5 on 2026-06-09 06:59

from django.db import migrations, models

# Seed = exactly the (canal × tipus) combinations distributed TODAY, all
# actiu=True, so the matrix defaults to identical behaviour:
#   - instagram / mastodon / bluesky / telegram publish the four feed
#     tipus from the CALENDARI (top_ppcc, top_territorial, nous_singles,
#     nous_albums);
#   - newsletter sends only top_ppcc (enviar_newsletter, Sunday).
# Hardcoded (not imported from CALENDARI) so the migration is a stable
# point-in-time snapshot. 17 rows.
_FEED_CHANNELS = ["instagram", "mastodon", "bluesky", "telegram"]
_FEED_TIPUS = ["top_ppcc", "top_territorial", "nous_singles", "nous_albums"]
_NEWSLETTER_TIPUS = ["top_ppcc"]


def _seed(apps, schema_editor):
    Matriu = apps.get_model("ranking", "MatriuPublicacio")
    combos = [(c, t) for c in _FEED_CHANNELS for t in _FEED_TIPUS]
    combos += [("newsletter", t) for t in _NEWSLETTER_TIPUS]
    for canal, tipus in combos:
        # Idempotent: never clobber a staff-set actiu on re-run.
        Matriu.objects.get_or_create(canal=canal, tipus=tipus, defaults={"actiu": True})


def _unseed(apps, schema_editor):
    Matriu = apps.get_model("ranking", "MatriuPublicacio")
    Matriu.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0019_configuracioglobal_distribucio_activa"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatriuPublicacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("mastodon", "Mastodon"),
                            ("bluesky", "Bluesky"),
                            ("telegram", "Telegram"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipus", models.CharField(max_length=20)),
                ("actiu", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Matriu de publicació",
                "verbose_name_plural": "Matriu de publicació",
                "ordering": ["canal", "tipus"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("canal", "tipus"), name="matriu_canal_tipus_unique"
                    )
                ],
            },
        ),
        migrations.RunPython(_seed, _unseed),
    ]
