# Generated by Django 6.0.5 on 2026-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0020_matriu_publicacio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="editorial_veu",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Prompt de veu editorial per a la rutina de newsletter. Servit dins el brief; editable des de Configuració. Buit = la rutina usa el seu propi default.",
            ),
        ),
    ]
