# Generated by Django 6.0.5 on 2026-06-09 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0021_editorial_veu"),
    ]

    operations = [
        migrations.AddField(
            model_name="matriupublicacio",
            name="dia_setmana",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
