# Generated by Django 6.0.5 on 2026-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0022_matriu_dia_setmana"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="fase_distribucio",
        ),
        migrations.AlterField(
            model_name="configuracioglobal",
            name="distribucio_activa",
            field=models.BooleanField(
                default=True,
                help_text="Interruptor mestre de distribució. Si False, cap dels sis canals publica (IG, Mastodon, Bluesky, Telegram, newsletter, RSS). Independent dels switches per canal.",
            ),
        ),
    ]
