# Generated by Django 6.0.5 on 2026-06-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0024_editorial_veu_help"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matriupublicacio",
            name="dia_setmana",
        ),
    ]
