# Generated by Django 6.0.5 on 2026-06-09 17:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0025_remove_matriu_dia_setmana'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioglobal',
            name='soft_cap_actiu',
            field=models.BooleanField(default=False, help_text="Activa el sostre suau d'escoltes per a outliers. Si False, l'algorisme usa les escoltes brutes (comportament previ). El sostre és per territori i no afecta les cançons per sota del genoll."),
        ),
        migrations.AddField(
            model_name='configuracioglobal',
            name='soft_cap_base_top_n',
            field=models.IntegerField(default=10, help_text='Població per a la mediana del genoll: el cap top-N del top rodant del territori (NO tot el top — la cua arrossegaria la mediana avall). 10 → mediana del top ~10. Rang 1-40.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='configuracioglobal',
            name='soft_cap_floor_escoltes',
            field=models.IntegerField(default=500, help_text="Genoll mínim del sostre, en escoltes. Protegeix els territoris menuts o sense prou historial (mediana inestable): si multiplicador × mediana queda per sota, s'usa aquest terra. També és el genoll de seguretat quan encara no hi ha historial.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='configuracioglobal',
            name='soft_cap_multiplicador',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text="Genoll del sostre = valor × mediana d'escoltes del top del territori (últimes setmanes). Per damunt del genoll les escoltes es comprimeixen. 3 → es considera outlier qui supera 3× el charting típic del seu territori.", max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='topsetmanal',
            name='weekly_plays',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
