# Generated by Django 6.0.5 on 2026-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0026_soft_cap_outlier"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="feed_redisseny_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Si True, les tres slides de novetats del feed (portada del carrusel, slide d'àlbum i graella de singles) es renderitzen amb el redisseny editorial PIL (tokens a social/feed_design/feed-tokens.json). Si False, maquetació llegada. Additiu: no afecta selecció, bin-packing ni canals.",
            ),
        ),
    ]
