# Generated by Django 6.0.5 on 2026-06-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0026_soft_cap_outlier'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioglobal',
            name='newsletter_publicacio_pont_actiu',
            field=models.BooleanField(default=False, help_text="Si True, l'staff pot publicar un esborrany de newsletter com a Publicació pública a la comunitat. Si False (per defecte), el pont està desactivat i l'endpoint el rebutja. Cap automatisme; res no es dispara sol."),
        ),
    ]
