# Generated by Django 6.0.5 on 2026-06-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0028_configuracioglobal_newsletter_publicacio_pont_actiu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracioglobal",
            name="feed_redisseny_actiu",
        ),
    ]
