# Generated by Django 6.0.5 on 2026-06-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0029_remove_configuracioglobal_feed_redisseny_actiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioglobal',
            name='dia_setmana_ranking',
        ),
        migrations.RemoveField(
            model_name='configuracioglobal',
            name='story_max_cancons_ppcc',
        ),
    ]
