# Generated by Django 6.0.5 on 2026-06-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0030_remove_configuracioglobal_dia_setmana_ranking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="landing_editorial_veu",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Prompt de veu editorial per a la rutina de prosa de landings SEO (territoris, generes, decades). Independent de la veu del newsletter. Servit dins el brief de landing-routine; editable des de Configuració. Buit = la rutina no genera res.",
            ),
        ),
    ]
