# Generated by Django 6.0.5 on 2026-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0031_configuracioglobal_landing_editorial_veu"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="novetats_stories_per_pagina",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Novetats per story d'Instagram abans de passar a la següent (paginació). Les novetats es reparteixen en diverses stories perquè apareguen totes. Inicial 4; el renderer el limita a 1-8.",
            ),
        ),
    ]
