# Generated by Django 6.0.5 on 2026-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0032_configuracioglobal_novetats_stories_per_pagina"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="ig_collab_cooldown_a_dies",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Dies abans de reinvitar un artista de categoria A (ja acceptador).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="ig_collab_cooldown_c_dies",
            field=models.PositiveSmallIntegerField(
                default=90,
                help_text="Dies abans de reinvitar un artista rebutjat (categoria C).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="ig_collab_slots_acceptats",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Slots reservats a artistes que ja han acceptat abans (categoria A).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="ig_collab_slots_total",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Slots de col·laborador per publicació de feed. Límit dur de la Graph API = 3; la política aplica min(valor, 3).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="ig_collaboradors_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Flag mestre del sistema d'invitacions de col·laboradors d'Instagram (feed). Apagat = capa dormida: cap invitació, cap fila escrita, el poller fa no-op.",
            ),
        ),
    ]
