# Generated by Django 6.0.5 on 2026-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0033_configuracioglobal_ig_collab_cooldown_a_dies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="newsletter_desti_prova",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adreça opcional que rep TAMBÉ l'esborrany setmanal de la newsletter (a més de l'admin), per a provar el render als clients de correu. Buit = cap enviament extra. Mai s'usa per a l'enviament real als subscriptors.",
                max_length=254,
            ),
        ),
    ]
