# Generated by Django 6.0.5 on 2026-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0034_configuracioglobal_newsletter_desti_prova"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="feed_artwork_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Portades de feed amb l'artwork duotonat del protagonista (tops: portada del nº1; novetats: mosaic). Apagat = portada tipogràfica actual, render idèntic. Font de portada = la mateixa cadena del pipeline (local jpg → Deezer → placeholder).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="feed_artwork_mosaic_max",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Màxim de portades al mosaic de novetats. El renderer el limita a 4-6: amb <4 disponibles cau a la portada tipogràfica; 4-5 → graella 2×2; 6+ → 2×3 (retallat a aquest màxim).",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="moviment_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Tipus de publicació «moviment» (dijous, sobre el Top Global). Apagat = capa dormida: `publicar_social` no crea cap fila ni intenta res per al slot de dijous.",
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="moviment_pujada_minima",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Delta mínim de posicions per a publicar «la pujada» quan no hi ha cap entrada directa al top 10. Si la millor pujada no hi arriba, el post s'omet (mateix mecanisme que les novetats buides).",
            ),
        ),
    ]
