# Generated by Django 6.0.6 on 2026-07-27 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0037_remove_ig_robustness_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="tls_avis_dies",
            field=models.PositiveSmallIntegerField(
                default=21,
                help_text="Dies de marge abans de la caducitat a partir dels quals tq-health avisa. Per defecte 21: deixa tres setmanes de reacció i queda per damunt de la finestra de renovació de Let's Encrypt (~30 dies), de manera que una renovació que no arriba es nota abans no siga urgent.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="tls_endpoints_vigilats",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Endpoints TLS a vigilar, un per línia en format «host:port» (p. ex. mail.topquaranta.cat:993). Les línies buides i les que comencen amb # s'ignoren, així pots deixar-hi candidats apuntats sense activar-los. Buit = cap vigilància. Els ports 25 i 587 es negocien amb STARTTLS; la resta és TLS directe. Es mesura el certificat servit per la xarxa, mai un fitxer del disc.",
            ),
        ),
    ]
