# Generated by Django 6.0.5 on 2026-08-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0094_artista_youtube_channel_id_and_more"),
        ("ranking", "0038_configuracioglobal_tls_avis_dies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenyalYouTube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("views", models.BigIntegerField(null=True)),
                ("likes", models.IntegerField(null=True)),
                ("video_id", models.CharField(blank=True, max_length=16)),
                ("error", models.BooleanField(default=False)),
                ("error_msg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="senyals_youtube",
                        to="music.canco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Senyal de YouTube",
                "verbose_name_plural": "Senyals de YouTube",
                "ordering": ["-data"],
                "indexes": [
                    models.Index(
                        fields=["canco", "data"], name="ranking_sen_canco_i_287fb8_idx"
                    ),
                    models.Index(
                        fields=["data", "error"], name="ranking_sen_data_d7811c_idx"
                    ),
                ],
                "unique_together": {("canco", "data")},
            },
        ),
    ]
