# Generated by Django 6.0.5 on 2026-08-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0039_senyalyoutube"),
    ]

    operations = [
        migrations.AddField(
            model_name="senyalyoutube",
            name="n_videos",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="senyalyoutube",
            name="video_id",
            field=models.CharField(
                blank=True, help_text="L'Art Track; el carril primari.", max_length=16
            ),
        ),
    ]
