# Generated by Django 6.0.5 on 2026-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0040_senyalyoutube_n_videos_alter_senyalyoutube_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="senyalyoutube",
            name="views_per_video",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
