# Generated by Django 6.0.5 on 2026-08-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0040_senyalyoutube_n_videos_alter_senyalyoutube_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="canco_dia_actiu",
            field=models.BooleanField(
                default=False,
                help_text="Sondes «la cançó del dia» (stories dt/dj/dv/dg, matí i vesprada, artistes mai col·laboradors). Apagat = capa dormida: `publicar_social` no crea cap fila ni intenta res per als slots de sonda.",
            ),
        ),
    ]
