# Generated by Django 6.0.5 on 2026-08-18 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0041_senyal_youtube_views_per_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioglobal",
            name="min_senyal_combinat",
            field=models.IntegerField(
                default=200,
                help_text="Terra per a entrar al top quan YouTube està actiu. Substitueix min_escoltes_top, que és en unitats d'escoltes.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="youtube_dies_minims",
            field=models.IntegerField(
                default=7,
                help_text="Dies de detall per vídeo que demanem abans de deixar que YouTube compte al top. Quan se n'acumulen tants, s'activa sol. Més alt = més tard i amb un delta menys extrapolat.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="configuracioglobal",
            name="youtube_pes_escolta",
            field=models.IntegerField(
                default=1000,
                help_text="Quantes visualitzacions de YouTube val una escolta de Last.fm. Més alt = YouTube pesa menys. A 1000, YouTube només omple els buits i no reordena res del que Last.fm ja veu.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
