# Generated by Django 6.0.5 on 2026-08-19 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0042_youtube_dies_minims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracioglobal",
            name="min_senyal_combinat",
            field=models.IntegerField(
                default=200,
                help_text="Terra per a entrar al top quan YouTube està actiu. Substitueix min_escoltes_top, que és en unitats d'escoltes. A pes 1000 també vol dir «una cinquena part d'una escolta»: que una cançó entre amb una sola escolta és volgut.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
